chore(docs): fix typo in vacuum table reference
questdb/questdb.io pull request #1007
Opened 2022-08-19 15:48 UTC by puzpuzpuz

The typo was `automitically`

2022-08-22 14:41 UTC, amyshwang requested changes
I left suggestions but also many questions!

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
>  written to the disk. The old partition version directory is deleted once it is
```suggestion
When a table is appended in an out-of-order manner, the `VACUUM TABLE` command writes a new partition version to the disk. The old partition version directory is deleted once it is
```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +not read by SELECT queries. In the event of file system errors, physical
```suggestion
not read by `SELECT` queries. In the event of file system errors, physical
```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +deletion of old files can be interrupted and an outdated partition version may
```suggestion
deletion of old files may be interrupted and an outdated partition version may
```
I use may because I think this is a possibility, not a capacity (as this is a warning?)

Maybe this should be a note:

```
:::note
In the event of file system errors, physical deletion of old files can be interrupted and an outdated partition version may be left behind consuming the disk space.
:::
```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +In a similar manner executing `UPDATE` SQL statement copies column files. Old
```suggestion
In a similar manner to executing `UPDATE` SQL statement copies column files. Old
```
I don't understand this sentence. It is not complete. Are we trying to say:
Executing `VACUUM TABLE` SQL statement is similar to executing `UPDATE` SQL statement?
Or maybe:
Similar to the `UPDATE` SQL statement, `VACUUM TABL` also copies the column files (of the table?)?

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +column files are automatically deleted but in some limited circumstances can be
```suggestion
column files are automatically deleted but in certain circumstances, they can be
```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +left behind. In this case `VACUUM TABLE` will re-trigger delete process of
```suggestion
left behind. In this case, `VACUUM TABLE` will re-trigger the deletion process of the
```
So reading this my understanding is that if I tun `VACUUM TABLE` for a table with leftover partitions, the command will only do the deletion: it deletes the old files of the table. (And therefore does not write new partition?)

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +The `VACUUM TABLE` command starts a new scan over table partitions directories
```suggestion
The `VACUUM TABLE` command starts a new scan over table partition directories
```
The main noun here is the directories, right? If so, the above suggestion should work.

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +space and deletes them. `VACUUM` executes asynchronously, i.e. it may keep
```suggestion
space and deletes them. `VACUUM TABLE` executes asynchronously, i.e. it may keep
```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +scanning and deleting files after their response is returned to the SQL client.
It is not clear what kind of response is expected? Is "SQL client" the right term here? 
I think maybe a normal response should be explained first.
```When executed, `VACUUM TABLE` returns [a message] [...]. As the command executes asynchronously, the process of scanning and deleting may continue after the respond is sent.```

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +This command has to be executed rarely and provides a manual mechanism to
```suggestion
This command has to be executed sparingly and provides a manual mechanism to
```
Do we mean you should not use it too often (sparingly)? 
I also don't understand the second half of the line. Do we mean:
The command provides a manual mechanism to reclaim the disk space.
If so it should be at the start of the intro?

Or maybe it is an explanation to why we should not be using it too often?
Then:
"because it is a manual mechanism..."

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +reclaim the disk space. The implementation scans file system catalogs to detect
```suggestion
reclaim the disk space. The implementation scans file system catalog to detect
```
I am not sure about this but I think there is only one file system catalog?

2022-08-22 14:41 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +often.
```suggestion
duplicate directories and files and frequent usage of the command can be relatively expensive.
```

2022-08-24 06:05 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +deletion of old files can be interrupted and an outdated partition version may
I don't think we should break vacuum description into multiple sections. It's compact and logical. Also, notes are good for some hints while this sentence simply describes why vacuum table may be needed.

2022-08-24 06:07 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +In a similar manner executing `UPDATE` SQL statement copies column files. Old
Going to change this sentence to make it more logical.

2022-08-24 06:07 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +left behind. In this case `VACUUM TABLE` will re-trigger delete process of
Yes, your understanding is correct.

2022-08-24 06:08 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +scanning and deleting files after their response is returned to the SQL client.
> Is "SQL client" the right term here?

Yes, to me this term is a correct one.

2022-08-24 06:10 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +reclaim the disk space. The implementation scans file system catalogs to detect
Going to remove "catalog" to avoid confusion.

2022-08-24 06:12 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +This command has to be executed rarely and provides a manual mechanism to
Going to restructure this paragraph to make it more logical.

2022-08-24 06:12 UTC, puzpuzpuz commented
@amyshwang PTAL

2022-08-24 10:46 UTC, amyshwang reviewed
One question!

2022-08-24 10:46 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +In this case, `VACUUM TABLE` will re-trigger the deletion process of the updated
Just for my own understanding perhaps:
So `VACUUM TABLE` is used when `UPDATE` created left old column files behind? And when this happens, users should use `VACUUM TABLE` to tidy up disk space?
The current wording seems to say that you can use `UPDATE` and `VACUUM TABLE` will be triggered (automatically) in certain circumstances.
I am guess that this paragraph is explaining when `VACUUM TABLE` will be useful? I can suggest something once I confirm what it means!

2022-08-24 12:45 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +In this case, `VACUUM TABLE` will re-trigger the deletion process of the updated
Yes, your understanding is correct. Vacuum command is there for those rare cases when the database failed to clean up the old version files due to some circumstances (say, a crash).

2022-08-25 08:02 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +In this case, `VACUUM TABLE` will re-trigger the deletion process of the updated
But I suppose it is not limited to situation caused by `UPDATE`? 
I'd remove this paragraph from the description, as it is not a general behaviour. It is perhaps more suitable for the example section, to provide more context to the scenario for the command?
```When an UPDATE SQL statement is run, it copies column files. Old column files are automatically deleted but in certain circumstances, they can be left behind. In this case, VACUUM TABLE will re-trigger the deletion process of the updated column files.```

2022-08-25 08:59 UTC, puzpuzpuz commented on docs/reference/sql/vacuum-table.md
> +In this case, `VACUUM TABLE` will re-trigger the deletion process of the updated
This paragraph describes the main use case for the vacuum command, so I'd keep it in the description.

2022-08-25 10:39 UTC, amyshwang commented on docs/reference/sql/vacuum-table.md
> +In this case, `VACUUM TABLE` will re-trigger the deletion process of the updated
```suggestion
When an `UPDATE` SQL statement is run, it copies column files of the selected table. The old column files are automatically deleted but in certain circumstances, they can be left behind.
In this case, `VACUUM TABLE` can be used to re-trigger the deletion process of the updated
```

2022-08-25 15:17 UTC, puzpuzpuz commented
@amyshwang this one should be good to go.

2022-08-26 07:53 UTC, amyshwang approved these changes
LGTM!

2022-08-30 10:14 UTC, merged