docs: alter system lock/unlock table
questdb/questdb.io pull request #1020
Opened 2022-08-30 14:35 UTC by jerrinot

2022-09-01 09:47 UTC, amyshwang requested changes
I left some editorial feedback. As you mentioned, adding this as `ALTER SYSTEM` is confusing. Although there is only one `(UN)LOCK` option, I suggest that we follow the same pattern used by `ALTER TABLE`:
![image](https://user-images.githubusercontent.com/107401731/187884047-d32dfe97-e755-4d56-9fd3-edd5be567d88.png)

This means that we create a new `ALTER SYSTEM` side bar and nesting `ALTER SYSTEM (UN)LOCK` under it. It is not ideal to only have one item but I think separating `LOCK` and `UNLOCK` is an overkill.
This means that the filenames would need to be changed --> do you think this is a reasonable idea?

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +Lock and unlock tables. Locked tables are still available for reading, but inaccessible for writing until
```suggestion
Locks and unlocks tables. Locked tables are still available for reading, but inaccessible for writing until
```

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +unlocked. A locked table won't accept new data and its schema cannot be changed either.
Isn't this implied already by saying that the table is inaccessible for writing?

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +
```suggestion
This operation is intended to be used during maintenance procedures, to prevent a table from being manipulated in any way. 


```

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +perform lock/unlock. A table must exist before it's locked.
This is a piece of important information that I'd move to the start, around line 10.
```suggestion
A table must exist before it is locked. 
Locking and unlocking a table is considered to be a write operation. Users with a read-only access cannot perform `ALTER SYSTEM (UN)LOCK WRITER`. 
```

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +ALTER SYSTEM UNLOCK WRITER ratings ;
```suggestion
ALTER SYSTEM UNLOCK WRITER ratings;
```

2022-09-01 09:47 UTC, amyshwang commented on docs/reference/sql/alter-system.md
> +ALTER SYSTEM LOCK WRITER ratings ;
```suggestion
ALTER SYSTEM LOCK WRITER ratings;
```

2022-09-01 11:53 UTC, jerrinot commented on docs/reference/sql/alter-system.md
> +unlocked. A locked table won't accept new data and its schema cannot be changed either.
yes, you are right. it's redundant.

2022-10-19 12:03 UTC, amyshwang commented
Closing this for now as there are changes to this feature in core.

2022-10-19 12:03 UTC, closed without merging