add copenhagen atomics use case page
questdb/questdb.io pull request #1029
Opened 2022-09-06 13:14 UTC by argshook

2022-09-06 14:39 UTC, amyshwang requested changes
I tried to add the update needed but there are some that I am not sure!

2022-09-06 14:39 UTC, amyshwang commented on src/pages/customers.tsx
> +              src="/img/pages/case-study/copenhagen-atomics/banner.png"
The image is squashed - 
![image](https://user-images.githubusercontent.com/107401731/188660551-27eb6c47-dee0-4550-bc9d-66221ee86757.png)
What would be a better image proportion? I can redo it.

2022-09-06 14:39 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +
```suggestion
    "In this case study, Lasse Tarp, the Software Group Manager from Copenhagen Atomics, introduces us to the company's software architectural design with QuestDB at its core."

```

2022-09-06 14:39 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            . The plot shown above is a selection of some of the temperature
```suggestion
              <a href="https://www.copenhagenatomics.com/technology">
                equipment
              </a>
            that are not produced by us. The plot shown above is a selection of some of the temperature
```
Forgot to indicate which text to add the link. I think the link should go to "equipment" and the above is my attempt to add it...

2022-09-06 14:39 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +          </p>
For "Insights from the QuestDB team" could we add some formatting to make it stand out more? Italics? Indentation?

2022-09-06 14:39 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +              <span className={caCss.card__quote}>&rdquo;</span>
I forgot to indicate the source:

```
-- Lasse Tarp, Software Group Manager, Copenhagen Atomics
```

2022-09-06 15:46 UTC, argshook commented on src/pages/customers.tsx
> +              src="/img/pages/case-study/copenhagen-atomics/banner.png"
it's alrigh, i'll resize to fit better

2022-09-06 16:37 UTC, amyshwang reviewed
Sorry for changing my mind but for entry block image could we use this: 
![image (1)](https://user-images.githubusercontent.com/107401731/188689418-607a6258-5aa3-4580-b0a6-ff0581d1e55a.png)
From - https://www.copenhagenatomics.com/potential/

2022-09-06 16:59 UTC, amyshwang requested changes
I forgot to add a hyperlink in the original draft....

2022-09-06 16:59 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            Atomics aims to address one of the most burning issues for our
Sorry...I forgot to add a hyperlink to their site for "Copenhagen Atomics"
https://www.copenhagenatomics.com/
One day I will get it right:
```suggestion
            Founded by a group of scientists and engineers in 2014,{" "}
            <a href="https://www.copenhagenatomics.com">Copenhagen Atomics</a>{" "} aims to address one of the most burning issues for our
```

2022-09-06 17:01 UTC, argshook commented on src/pages/case-study/copenhagen-atomics.tsx
> +            Atomics aims to address one of the most burning issues for our
all good, don't worry, I'll add it

2022-09-07 08:01 UTC, amyshwang requested changes
Apologies - another request to add a diagram that I forgot about!

2022-09-07 08:01 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +
Apologies - I forgot to insert this image after the title:
![image](https://user-images.githubusercontent.com/107401731/188823473-2ca99f82-8d58-4d3b-8cec-bda5f46b41ab.png)

Caption: high-level overview of how Copenhagen Atomics deploys QuestDB.

2022-09-07 09:19 UTC, amyshwang requested changes

2022-09-07 09:19 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            BY.This way, we can adjust the granularity of the data by zooming in
```suggestion
            is fetched from QuestDB and downsampled with the query `SAMPLE
            BY`. This way, we can adjust the granularity of the data by zooming in
```

2022-09-07 09:19 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +          <p className="font-size--large">
In the preview, this section has a smaller font?
![image](https://user-images.githubusercontent.com/107401731/188840467-aceb55b7-918b-426d-aab2-8eb1f8978d23.png)
Really strange!

2022-09-07 09:34 UTC, argshook commented on src/pages/case-study/copenhagen-atomics.tsx
> +            BY.This way, we can adjust the granularity of the data by zooming in
the backticks around `SAMPLE BY` are not helping here, because this page is not `mdx` :(

i'll look into how to make it nicer

2022-09-07 09:38 UTC, argshook commented on src/pages/case-study/copenhagen-atomics.tsx
> +          <p className="font-size--large">
yep. docusaurus build system tries to optimize so much that sometimes it
just removes some styling. Like in this case class name
`font-size--large`

why? ¯\\\_(ツ)_/¯ 

regardless, i'll check it out

2022-09-07 10:58 UTC, amyshwang requested changes
Checking the output against the draft and adding Nic's comments.

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +    description: "Real-time IoT sensor monitoring",
```suggestion
    description: "Real time IoT sensor monitoring",
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +    "In this case study, Lasse Tarp, the Software Group Manager from Copenhagen Atomics, introduces us to the company's software architectural design with QuestDB at its core."
```suggestion
    "Copenhagen Atomics, manufacturer of next generation molten salt reactors, uses QuestDB to monitor their reactor environment  in real time."
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +    description: "Optimised query performance",
```suggestion
    description: "Optimised SQL query performance",
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            the production of the molten salt reactors to provide Energy as a
```suggestion
            the production of molten salt reactors to provide Energy as a
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            Service. Depending on the energy needs of a client, the company will
```suggestion
            Service. Depending on the energy needs of each client, the company will
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            In this case study, Lasse Tarp, the Software Group Manager from
```suggestion
            In this case study, Lasse Tarp, Software Group Manager at
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            src="/img/pages/case-study/copenhagen-atomics/architecture.png"
```suggestion
            description="Copenhagen Atomics' software stack to monitor nuclear reactors sensors in real time."
            src="/img/pages/case-study/copenhagen-atomics/architecture.png"
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +          </p>
```suggestion
            QuestDB&#39;s engine on Kubernetes. Each reactor sends thousands of data points to the API servers every 10 milliseconds. The number of reactor sensor values is likely to grow
            from 200 to near 1000 in the future.
          </p>
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            systems for fetching and displaying data.
```suggestion
            sensor data to QuestDB using the .NET ILP client and sending queried (downsampled) data to our plot systems for monitoring. We customize our own plot
            systems for fetching and displaying data.
```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +
There is one paragraph missing here:
```Reactors function in a sealed environment; monitoring this environment is a crucial step for anomaly detection. QuestDB is the time series database behind the growing number of reactor sensors, which continuously send back information such as temperature, liquid flow and pressure. The data is then filtered and presented to the plot systems, accessible via the web browser for monitoring purposes. ```

2022-09-07 10:58 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +
There is a line missing:
```
The query fetches 2,700 rows from QuestDB in 236 milliseconds.
```

2022-09-07 11:54 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            BY.This way, we can adjust the granularity of the data by zooming in
Added the missing space for now.

2022-09-07 11:55 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +          <p className="font-size--large">
It seems to have fixed itself...

2022-09-07 14:18 UTC, argshook commented on src/pages/case-study/copenhagen-atomics.tsx
> +          <p className="font-size--large">
looks like it. we changed the HTML structure a bit and current one
apparently is not getting "over-optimized"

2022-09-07 14:30 UTC, amyshwang requested changes

2022-09-07 14:30 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +            really impressed with response times when we query data.
```suggestion
            really impressed with response time when we query data.
```

2022-09-07 15:07 UTC, amyshwang approved these changes

2022-09-07 17:12 UTC, amyshwang commented on src/pages/case-study/copenhagen-atomics.tsx
> +                For QuestDB cloud, the team will provide a one-click solution to
```suggestion
                For QuestDB Cloud, the team will provide a one-click solution to
```

2022-09-07 18:33 UTC, merged