feat: HN Post
questdb/questdb.io pull request #105
Opened 2020-08-18 14:17 UTC by davidgs

First draft

2020-08-18 14:17 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=105) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=105) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=105) it.</sub>

2020-08-18 14:27 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +# QuestDB Performance
Missing headers:

---
title: QuestDB Performance
author: David G. Simmons
author_title: QuestDB Team
author_url: https://github.com/davidgs
author_image_url: https://avatars.githubusercontent.com/davidgs
description: @@@@@todo@@@@@@
tags: [performance]
image: @@@@@todo@@@@@@
---

2020-08-18 14:30 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +This, it turns out, is hugely inefficient. If(data is in frame) then (process that data) else (figure out where the rest of the data is, get that, then process it all). This kind of if-then-else spri
```suggestion
This, it turns out, is hugely inefficient. If (data is in frame) then (process that data) else (figure out where the rest of the data is, get that, then process it all). This kind of if-then-else sprinkled throughout the code is a) hard to debug and b) leads to lots of branching, which slows down execution.
```

2020-08-18 14:31 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +If your page size is bigger than the available memory, the kernel will handle swapping pages in and out for you as you try to access different parts of the page.So of course I asked "well then, why d
```suggestion
If your page size is bigger than the available memory, the kernel will handle swapping pages in and out for you as you try to access different parts of the page. So of course I asked "well then, why didn't you do this from the beginning?".
```

2020-08-18 14:31 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +Vlad, in his typically self-deprecating style, just said "we didn't know. We thought we should keep them to a certain size to keep them from growing out of control" which, quite frankly, seems like t
```suggestion
Vlad, in his typically self-deprecating style, just said "We didn't know. We thought we should keep them to a certain size to keep them from growing out of control" which, quite frankly, seems like the right answer.
```

2020-08-18 14:31 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +We'd just resize those smaller pages as needed. But as Vald explained, if you do that then you need to copy the data over to the new, resized page and "copying can take over your life." Databases are
```suggestion
We'd just resize those smaller pages as needed. But as Vald explained, if you do that then you need to copy the data over to the new, resized page and "copying can take over your life". Databases aren't built to maximize the efficiency of data copying. They are built to maximize the ability to extract value from data. Copying data from one page to another isn't extracting value.
```

2020-08-18 14:32 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +So they tried jusst allocating a new page, and jumping from one page to the next as needed to find the required data. This cut down on the copying of data, but it lead to the problems outlined in the
```suggestion
So they tried just allocating a new page, and jumping from one page to the next as needed to find the required data. This cut down on the copying of data, but it lead to the problems outlined in the previous section. You never knew which page your data was going to be on, and jumping from one page to another was hugely inefficient.
```

2020-08-18 14:32 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +So they tried having just the one page. One massive page (that you can grow as needed, without copying data around). Vlad, again in his style said the performance turned out to be "not bad" with this
```suggestion
So they tried having just the one page. One massive page (that you can grow as needed, without copying data around). Vlad, again in his style, said the performance turned out to be "not bad" with this approach. And by "not bad" he of course meant about a 60% performance improvement.
```

2020-08-18 14:33 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +The kernel allocated a full sized address space for your file when you requested the memory-mapped file. And apparently this is true across Linux, Mac OS and Windows. So from that point on, there's r
```suggestion
The kernel allocated a full sized address space for your file when you requested the memory-mapped file. And apparently this is true across Linux, macOS and Windows. So from that point on, there's really no further copying that needs to happen.
```

2020-08-18 14:34 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +Furthermore, the kernel is going to handle paging parts of that file in and out of memory as needed. Now, I'm old-school UNIX, and page-swapping which lead to thrashing was always something we worrie
```suggestion
Furthermore, the kernel is going to handle paging parts of that file in and out of memory as needed. Now, I'm old-school Unix, and page-swapping which lead to thrashing was always something we worried about back in the olden days. So I asked about it. According to Patrick, this could only happen really if you have a massive file that you are reading basically randomly at high speed. Other than that, the kernel will handle reading ahead and pre-loading pages as needed in order to be as efficient as possible.
```

2020-08-18 14:35 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +Kernels, it turns out, are smart. In fact, kernels are basically smarter than you or I will ever hope to be. Theyve been developed across decades to be hugley efficient at doing these things. It's wh
```suggestion
Kernels, it turns out, are smart. In fact, kernels are basically smarter than you or I will ever hope to be. They've been developed across decades to be hugely efficient at doing these things. It's what they do. The kernel will memory map the file into the file cache and even if it needs to move stuff around, it can move the address and it's still the same memory.
```

2020-08-18 14:35 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +If you think that you can take over caching the data from the OS and do a better job of managing the memory space, and the allocation and re-allocation of the memory, you're wrong. Again, this is wha
```suggestion
If you think that you can take over caching the data from the OS and do a better job of managing the memory space, and the allocation and re-allocation of the memory, you're wrong. Again, this is what the Kernel does, and at some level, even if you try to take this job away from the kernel, it is *still* doing some amount of it anyway. So your attempts to take this memory management and allocation away from the kernel has done little more than just add another layer on top of what the kernel is doing anyway. Another layer on top of something is basically never more efficient than the original thing.
```

2020-08-18 14:36 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +When I asked Vlad about this, and how it relates to query speed, he was quite explicit in saying that thinking you (a database devleoper) can beat the kernel is pure folly. Postgres tries this and, a
```suggestion
When I asked Vlad about this, and how it relates to query speed, he was quite explicit in saying that thinking you (a database developer) can beat the kernel is pure folly. Postgres tries this and, according to Vlad, an aggregation over a large (really large!) dataset can take 5 *minutes*, whereas the same aggregation on QuestDB takes only 60ms. Those aren't typos.
```

2020-08-18 14:37 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +It comes down to letting the kernel do its job, and us doing ours. And our job is to exploiut the kernel for every ounce of performance we can get out of it without trying to do it's job for it.
```suggestion
It comes down to letting the kernel do its job, and us doing ours. And our job is to exploit the kernel for every ounce of performance we can get out of it without trying to do it's job for it. 
```
```suggestion
It comes down to letting the kernel do its job, and us doing ours. And our job is to exploiut the kernel for every ounce of performance we can get out of it without trying to do it's job for it. 
```

2020-08-18 20:01 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +I've written multi-threaded applications, and they are not easy to do. It's hard to coordinate the work between multiple threads, and to make sure that there are not race consitions, collisions, etc.
I've written multi-threaded applications, and they are not easy to do. It's hard to coordinate the work between multiple threads, and to make sure that there are no race conditions, collisions, etc.

2020-08-18 20:40 UTC, patrickSpaceSurfer requested changes

2020-08-18 20:40 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +I've written multi-threaded applications, and they are not easy to do. It's hard to coordinate the work between multiple threads, and to make sure that there are not race consitions, collisions, etc.
```suggestion
I've written multi-threaded applications, and they are not easy to do. It's hard to coordinate the work between multiple threads, and to make sure that there are no race conditions, collisions, etc.
```

2020-08-18 20:40 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +You see, we store everything as 8-byte values. Every value takes up 8 bytes, so that all the columns are the same width. But strings and blobs can't be forced into 8 bytes without making them useless
```suggestion
You see, we store fixed length fields with fixed length values, such that aligning frames to 8 bytes would ensure that all our fixed length data does not straddle frames. Hence all the columns are the same frame width. But strings and blobs can't be forced into 8 bytes without making them useless.
```

2020-08-18 20:40 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +This, it turns out, is hugely inefficient. If(data is in frame) then (process that data) else (figure out where the rest of the data is, get that, then process it all). This kind of if-then-else spri
```suggestion
This, it turns out, is hugely inefficient. If (data is in frame) then (process that data) else (figure out where the rest of the data is, get that, then process it all). This kind of if-then-else sprinkled throughout the code is a) hard to debug and b) leads to lots of branching, which slows down execution.
In order to prevent variable length data from straddling frames we would need to have different frame lengths per column. Furthermore, calculating aligned frame lengths for variable length data is non trivial and requires scanning the entire data set which would reversing any performance gains from parallelization.```

2020-08-18 20:40 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +This is where Patrick jumped in to explain that when you reserve space for memory mapping a file, the operating system just reserves the space for the full size, so when you go to expand the memory-m
```suggestion
This is where Patrick jumped in to explain that when you have an area of memory mapped from a file, when the file grows and you remap the new size into memory. The operating system does not need to copy anything, the virtual memory model allows the OS to just remap the already mapped pages into the newly mapped memory region. In many cases the OS may have already reserved the entire address space for you, so your new mapping is in the same region as the old, just bigger.
```

2020-08-18 20:40 UTC, patrickSpaceSurfer commented on blog/2020-08-19-questdb-performance.md
> +Kernels, it turns out, are smart. In fact, kernels are basically smarter than you or I will ever hope to be. Theyve been developed across decades to be hugley efficient at doing these things. It's wh
```suggestion
Kernels, it turns out, are smart. In fact, kernels are basically smarter than you or I will ever hope to be. They've been developed across decades to be hugely efficient at doing these things. It's what they do. The kernel will memory map the file into the file cache and even if it needs to move stuff around, it can move the logical address and it's still the same underlying physical memory pages.
```

2020-08-19 13:15 UTC, mpsq requested changes

2020-08-19 13:15 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +It comes down to letting the kernel do its job, and us doing ours. And our job is to exploiut the kernel for every ounce of performance we can get out of it without trying to do it's job for it.
```suggestion
It comes down to letting the kernel do its job, and us doing ours. And our job is to exploit the kernel for every ounce of performance we can get out of it without trying to do it's job for it. 
```

2020-08-19 13:17 UTC, mpsq requested changes

2020-08-19 13:17 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +This is where Patrick jumped in to explain that when you have an area of memory mapped from a file, when the file grows and you remap the new size into memory. The operating system does not need to c
```suggestion
This is where Patrick jumped in to explain that when you have an area of memory mapped from a file, when the file grows and you remap the new size into memory. The operating system does not need to copy anything, the virtual memory model allows the OS to just remap the already mapped pages into the newly mapped memory region. In many cases, the OS may have already reserved the entire address space for you, so your new mapping is in the same region as the old, just bigger.
```

2020-08-19 13:20 UTC, mpsq requested changes

2020-08-19 13:20 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +<!-- -->
`<!--truncate-->` has to be set somewhere in the page:
https://v2.docusaurus.io/docs/blog/#summary-truncation

2020-08-19 16:23 UTC, davidgs commented on blog/2020-08-19-questdb-performance.md
> +# QuestDB Performance
Done except for the description.

2020-08-19 16:24 UTC, davidgs commented on blog/2020-08-19-questdb-performance.md
> +<!-- -->
Done

2020-08-20 09:24 UTC, mpsq commented on blog/2020-08-19-questdb-performance.md
> +# QuestDB Performance
Done

2020-08-25 13:36 UTC, mpsq approved these changes

2020-08-25 13:37 UTC, merged