[docs] Capture `power()` in docs/function/numeric
questdb/questdb.io pull request #1088
Opened 2022-10-02 05:55 UTC by sudiptog81

Adds documentation for `power()` function along with relevant examples in the relevant section. 
Tested on local development setup.

Closes #1082.

![image](https://user-images.githubusercontent.com/11232940/193440156-02b2a1ec-0903-4131-aad2-10217b86b946.png)

2022-10-02 05:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1088) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1088) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1088) it.</sub>

2022-10-03 10:22 UTC, amyshwang requested changes
Minor editorial comment.

2022-10-03 10:22 UTC, amyshwang commented on docs/reference/function/numeric.md
> +power of some number `exponent`.
```suggestion
power defined by `exponent`.
```

2022-10-03 11:09 UTC, puzpuzpuz approved these changes
@sudiptog81 thanks for the contribution!

2022-10-03 11:09 UTC, puzpuzpuz commented on docs/reference/function/numeric.md
> +SELECT power(2, 3)
nit:
```suggestion
SELECT power(2, 3);
```

2022-10-03 13:47 UTC, merged