issue#1081 -- documented regexp_replace function
questdb/questdb.io pull request #1091
Opened 2022-10-03 06:30 UTC by AnkitaMalik22

2022-10-03 06:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1091) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1091) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1091) it.</sub>

2022-10-03 10:37 UTC, amyshwang requested changes
Thank you for your contribution. However, as described in the [guide](https://github.com/questdb/questdb.io/issues/1085), please:
* Write in the issue you would like to take and say that you would like to take it on.

In addition, although other functions on this page do not have examples, we'd like to include some examples using this function, as described by the function template.

I will be able to review the PR again once it has been updated. Thank you again!

2022-10-03 10:37 UTC, amyshwang commented on docs/reference/operators/regex.md
> +`symbol regexp_replace regex` - replaces `symbol` value to regex
This does not seem to be a complete description?

2022-10-03 10:37 UTC, amyshwang commented on docs/reference/operators/regex.md
> +`string regexp_replace regex` -  replaces a sequence of characters in a string with another set of characters using regular expression pattern matching
Full stop missing - it is also missing from the description above; would you mind adding them too please?

2022-10-04 08:43 UTC, amyshwang requested changes
Thank you! Editorial review comments added.

2022-10-04 08:43 UTC, amyshwang commented on docs/reference/operators/regex.md
> +Regex functions will allow us to replace a sequence of characters in a string with another set of characters using regular expression pattern matching.
This is only needed on top of each page. Please delete.

2022-10-04 08:43 UTC, amyshwang commented on docs/reference/operators/regex.md
> +## regexp_replace (replace)
Consistency:

```suggestion
## regexp_replace
```

Could you please ensure that the section follows the pattern similar to:
![image](https://user-images.githubusercontent.com/107401731/193773704-b755e7f6-8f96-4629-8a6a-1dc61bafcd50.png)

2022-10-04 08:43 UTC, amyshwang commented on docs/reference/operators/regex.md
> +FROM dual;
```suggestion
SELECT REGEXP_REPLACE ('MYSQL is a great database', '^(\S*)', 'QuestDB');
```

2022-10-04 09:10 UTC, puzpuzpuz commented on docs/reference/operators/regex.md
> +`string regexp_replace regex` - The regexp_replace function provides substitution of new text for substrings that match POSIX regular expression patterns.
We use Java regex syntax, not POSIX, and it's worth mentioning that.

2022-10-04 09:10 UTC, puzpuzpuz commented on docs/reference/operators/regex.md
> +- regexp_replace ( string text, pattern text, replacement text [, flags text ] )
We don't support flag. Instead, we default to global case sensitive replacement.

2022-10-05 08:07 UTC, amyshwang requested changes
Minor editorial review.

2022-10-05 08:07 UTC, amyshwang commented on docs/reference/operators/regex.md
> +`regexp_replace ( value1, text , value2 )` - The regexp_replace function provides substitution of new text for substrings that match regular expression patterns.
```suggestion
`regexp_replace ( value1, text , value2 )` - provides substitution of new text for substrings that match regular expression patterns. 
```

2022-10-05 08:07 UTC, amyshwang commented on docs/reference/operators/regex.md
> +- `value2` is string value.
```suggestion
- `value1` is any `string` value.
- `text` is  any regular expression pattern.
- `value2` is any `string` value.
```

2022-10-07 08:01 UTC, amyshwang requested changes
A couple more comments - I think it is almost ready!

2022-10-10 09:56 UTC, amyshwang approved these changes
Thank you for your contribution! 🚀

2022-10-10 10:11 UTC, merged