Capturing like/llike functions in /docs/reference/operations/regex.md #1078
questdb/questdb.io pull request #1103
Opened 2022-10-05 04:46 UTC by orensaldanha

I have added documentation for the LIKE operator.

However, the ILIKE operator is not working as expected.

![Screenshot from 2022-10-04 21-44-40](https://user-images.githubusercontent.com/36854536/193983220-8d3b58bd-a5e9-43a7-8e29-f185ad4de370.png)

2022-10-05 04:46 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1103) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1103) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1103) it.</sub>

2022-10-05 06:21 UTC, puzpuzpuz commented
> However, the ILIKE operator is not working as expected.

Our ILIKE implementation does a case-sensitive matching. This aspect should be documented.

2022-10-05 06:31 UTC, orensaldanha commented
So the LIKE and ILIKE operator have the same functionality?
1) Should I copy the LIKE documentation for ILIKE as it is 
2) or should I make a small section for ILIKE operator that says ILIKE makes a case sensitive match similiar to LIKE , adding that  this is contrary to other database systems like Postgres which make a case insensitive match for ILIKE

2022-10-05 08:19 UTC, puzpuzpuz commented
As far as I can see in the code, LIKE and ILIKE use the same implementation, so ATM their behavior is the same.

2022-10-05 08:24 UTC, puzpuzpuz commented
I've created https://github.com/questdb/questdb/issues/2585 to track the ILIKE issue. Yet, I think we should document it properly, i.e. as case-insensitive. The bug should be fixed soon.

2022-10-05 09:36 UTC, amyshwang requested changes
Thank you for your contribution and the discussion on the bug! 😃 
Could you document the desired behaviours for both `LIKE` and 'ILIKE` (probably in the same section to make it concise but listing out the difference in a clear manner with examples). We can then mark this task completed, independent of whether the bug is fixed.

2022-10-05 09:36 UTC, amyshwang commented on docs/reference/operators/regex.md
> +The `LIKE` operator returns true if it matches the specified pattern
1. Please follow [the template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md#function_name) to document this:
 
'LIKE' - returns...
 This applies to the rest of the PR.
2. I think it is not just returns true but returns the row?

2022-10-05 10:36 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +The `LIKE` operator returns true if it matches the specified pattern
The operator itself returns a boolean but the WHERE clause returns the row if the operator result is true

![Screenshot from 2022-10-05 15-55-46](https://user-images.githubusercontent.com/36854536/194041163-484b77fb-7d1d-4a24-bf10-7777a6e40d20.png)

2022-10-06 11:12 UTC, amyshwang requested changes
Thank you for the update - more feedback on this!

2022-10-06 11:12 UTC, amyshwang commented on docs/reference/operators/regex.md
> +The pattern can contain wildcards which are interpreted as follows:
```suggestion
The Java regex syntax can contain wildcards which are interpreted as follows:
```

2022-10-06 11:12 UTC, amyshwang commented on docs/reference/operators/regex.md
> +| 'quest' LIKE 'quest'   |  true   |
Applying this to all:
```suggestion
|  SELECT 'quest' LIKE 'quest'   |  true   |
```

In this way, users can copy it and run it on the demo site directly.

2022-10-07 12:36 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +`symbol` is [string].
@amyshwang correct me if I'm wrong, but I don't think "pattern following the Java regex syntax" is an appropriate description for pattern here since the pattern does not support the whole range of regex meta characters rather it supports only the two wildcards '?' and '%'.

2022-10-10 09:54 UTC, amyshwang requested changes
Nearly there 👍

2022-10-10 09:54 UTC, amyshwang commented on docs/reference/operators/regex.md
> +`string` is a string which is commonly the name of a column.
```suggestion
`string` is an expression that evaluates to the `string` data type. 
```

2022-10-10 09:54 UTC, amyshwang commented on docs/reference/operators/regex.md
> +- `%` - matches any sequence of zero or more characters
Missing full stops.

2022-10-10 09:54 UTC, amyshwang commented on docs/reference/operators/regex.md
> +### Example
```suggestion
### Examples
```

2022-10-10 09:54 UTC, amyshwang commented on docs/reference/operators/regex.md
> +| symbol | side | price | amount | timestamp |
As mentioned, we'd like proper behaviours to be documented so this is not correct. In addition, https://github.com/questdb/questdb/issues/2585 has been merged.

2022-10-10 15:50 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +| symbol | side | price | amount | timestamp |
By proper behaviour do you mean:
1) the result it returns on the demo site (which is still not updated with the correct ILIKE implementation).
2) the assumed correct behaviour for the ILIKE operator.

In my PR, I have used the assumed behaviour.

2022-10-11 09:07 UTC, amyshwang commented on docs/reference/operators/regex.md
> +| symbol | side | price | amount | timestamp |
You're right! My bad!

2022-10-11 09:31 UTC, bziobrowski commented on docs/reference/operators/regex.md
> +
typo: `whuch`

2022-10-11 09:41 UTC, bziobrowski commented on docs/reference/operators/regex.md
> +| SELECT 'quest' LIKE 'quest'   |  true   |
Does : 
```sql
SELECT 'quest' LIKE 'quest_'
```
really return true ? 

It doesn't seem to be the case on master branch or demo instance .

2022-10-11 09:45 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +| SELECT 'quest' LIKE 'quest'   |  true   |
Yep my bad, 

it's supposed to be SELECT 'quest' LIKE 'ques_'

2022-10-11 09:53 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +| SELECT 'quest' LIKE 'quest'   |  true   |
As for the second one, 
I intended it to be: SELECT 'quest' LIKE '_ues_'
I added the '\' to escape the underscore as it was displaying it in italics.

![Screenshot from 2022-10-11 15-22-46](https://user-images.githubusercontent.com/36854536/195058681-c87c1517-02ce-41f6-bb4f-c2aae58e3c72.png)

2022-10-11 09:57 UTC, amyshwang commented on docs/reference/operators/regex.md
> +`symbol` is [string].
Yes you're right! Apologies for the confusion. But I think it should be "_" and "%"?

2022-10-11 10:01 UTC, amyshwang requested changes

2022-10-11 10:05 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +`symbol` is [string].
Yep my bad. It's '_' and not '?'

2022-10-11 10:06 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +`pattern` is a pattern which can contain wildcards like `?` and `%`.
Yep made a mistake. Sorry for the confusion.

2022-10-11 12:12 UTC, amyshwang commented on docs/reference/operators/regex.md
> +| SELECT 'quest' LIKE 'quest'   |  true   |
Could you please revert the change? We need to check the rendering, not the source!

2022-10-11 12:22 UTC, orensaldanha commented on docs/reference/operators/regex.md
> +| SELECT 'quest' LIKE 'quest'   |  true   |
yep done

2022-10-11 13:21 UTC, amyshwang approved these changes
Thank you for your contribution!

2022-10-11 13:30 UTC, merged