Update aggregation.md
questdb/questdb.io pull request #1104
Opened 2022-10-05 09:47 UTC by Smartmind12

Closes #1096

2022-10-05 09:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1104) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1104) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1104) it.</sub>

2022-10-05 11:09 UTC, amyshwang requested changes
Thank you for your contribution! 🚀 
I have left a few comment and in general could you follow [the template](https://github.com/questdb/questdb.io/blob/master/docs/__guidelines/template/function.md#function_name) for functions? 
1. In this case, moving the PARTITION BY and ORDER BY content to a Description section. `row_number()` itself takes no argument
2. Could we have more examples showing the complexity depending on whether `PARTITION BY` and `ORDER BY` is used? 
3. Use more real-world-like examples as shown in other functions?

2022-10-05 11:09 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +:::
Maybe incorporate this to the description above? `PARTITION BY` is an optional clause [...].

2022-10-05 11:09 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- `order by` is a clause defines the logical order of the rows within each partition of the result set.
This is also optional and can only be used with `PARTITION BY`?

2022-10-05 12:52 UTC, Smartmind12 commented
@amyshwang Kindly review if the updated changes are done as per your recommendations!

2022-10-05 15:07 UTC, javier commented on docs/reference/function/aggregation.md
> +`row_number() over(partition by [partition_expression1, partition_expression2], order by sort_expression1 [ASC | DESC]) as row_num` - returns the sequential number of a row within a partition of a re
row_number() over() starts from 0, as seen if you run this on the demo site

with t as (
select *
 ,ROW_NUMBER OVER(partition by symbol order by timestamp asc) as r 
from 'trades' where timestamp IN '2022-09-16T17:10:00'
) select * from t order by symbol, r asc

2022-10-05 15:10 UTC, javier commented on docs/reference/function/aggregation.md
> +`row_number() over(partition by [partition_expression1, partition_expression2], order by sort_expression1 [ASC | DESC]) as row_num` - returns the sequential number of a row within a partition of a re
however row_number() without over starts at 1

2022-10-05 15:13 UTC, javier commented on docs/reference/function/aggregation.md
> +```questdb-sql title="Using `row_number() OVER(PARTITION BY[], ORDER BY [])` to display names in a sequential order according to alphabetical sequence of country name"
I'd rewrite to use one of the demo tables instead of this example which is inconsistent with all the other examples at our docs

2022-10-05 15:39 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +```questdb-sql title="Using `row_number() OVER(PARTITION BY[], ORDER BY [])` to display names in a sequential order according to alphabetical sequence of country name"
@javier could you help me find out as to which tables are you referring to so that i can update the commit accordingly!

2022-10-06 11:08 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +```questdb-sql title="Using `row_number() OVER(PARTITION BY[], ORDER BY [])` to display names in a sequential order according to alphabetical sequence of country name"
@Smartmind12 the demo site is here: https://demo.questdb.io/ Using the `trades` table as Javier suggested would make it easier for users to run tests.

2022-10-07 03:18 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +```questdb-sql title="Using `row_number() OVER(PARTITION BY[], ORDER BY [])` to display names in a sequential order according to alphabetical sequence of country name"
> @Smartmind12 the demo site is here: https://demo.questdb.io/ Using the `trades` table as Javier suggested would make it easier for users to run tests.

I have updated the file so kindly review the same...Thanks!

2022-10-07 07:59 UTC, amyshwang requested changes
Thank you. I resolved all the comments that have been addressed but there are a couple more and existing ones that have not been picked up (e.g. https://github.com/questdb/questdb.io/pull/1104#discussion_r988039376).

2022-10-07 07:59 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- `PARTITION BY` is an optional clause that divides the result set into partitions(group of rows). If skipped then row_number() function will conside the result to be a single partition.
These are all SQL keywords - do we really need them here?
Instead of prescribe strict query, could you add more high level principles for when `row_number()` could be useful?

2022-10-07 07:59 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
As mentioned below, I would delete this. The example has shown a way to combine the function with other key words.

2022-10-07 07:59 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +```questdb-sql title="Using `row_number()` to display amount in a sequential order"
What are the examples trying to show? Please add more explanation!

2022-10-07 10:01 UTC, javier commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
As highlighted on another comment, row_number starts at number 1, but row_number over() starts at 0

2022-10-07 13:12 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
> As mentioned below, I would delete this. The example has shown a way to combine the function with other key words.

Here which line would you liked to be deleted...Line 371 or 372 or both?

2022-10-07 13:14 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +- `PARTITION BY` is an optional clause that divides the result set into partitions(group of rows). If skipped then row_number() function will conside the result to be a single partition.
> These are all SQL keywords - do we really need them here? Instead of prescribe strict query, could you add more high level principles for when `row_number()` could be useful?

By "high level principles" do you mean Use cases or do you mean advanced queries & term definations?

2022-10-07 13:18 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
@javier I will update it ...But in the above comment i believe @amyshwang want the whole section of description to be deleted so i await her reply on it and will do the needful accordingly!

2022-10-10 09:38 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
@Smartmind12 sorry for the confusion I think in this case we need a new section "Description", as shown in the template file. The combination with `OVER` should be deleted from its current section, and moved to this Description section, as it is more complicated.

2022-10-10 09:40 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
As mentioned, the first section should be a simple overview of the function. A new Description section can be added to elaborate on what you had in line 372, with more text explaining why users should try using this function with `OVER` etc.

2022-10-10 09:42 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- `PARTITION BY` is an optional clause that divides the result set into partitions(group of rows). If skipped then row_number() function will conside the result to be a single partition.
I meant to answer these questions:
- What does row_window() do? 
- Why would users use this function with some other SQL key words?

2022-10-10 13:33 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
Update - I think we don't need to document the zero indexing as it is a bug: https://github.com/questdb/questdb/issues/2611 @Smartmind12 I think if we document the expected behaviour it'd be sufficient :)

2022-10-11 02:01 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +- `PARTITION BY` is an optional clause that divides the result set into partitions(group of rows). If skipped then row_number() function will conside the result to be a single partition.
> I meant to answer these questions:
> 
> * What does row_window() do?
> * Why would users use this function with some other SQL key words?

Sure will do!

2022-10-11 02:02 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
> As mentioned, the first section should be a simple overview of the function. The Description section should be used to elaborate on what you had in line 372, with more text explaining why users should try using this function with `OVER` etc.

I understand and make changes accordingly!

2022-10-11 16:32 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +`row_number() OVER(PARTITION BY [partition_expression1, partition_expression2], ORDER BY sort_expression1 [ASC | DESC]) as [row_num]` - returns the sequential number of a row within a partition of a
Thanks for the comments and i am currently updating the same!

2022-10-12 02:53 UTC, Smartmind12 commented
@amyshwang I have updated as per your request so kindly review!

Also, Can you help me with the "questdb sql title" formatting as i am unable to figure out the right use of ``` in the example titles.

2022-10-14 10:18 UTC, amyshwang requested changes
Please confirm whether the example queries and output work. Thank you.

2022-10-16 05:56 UTC, Smartmind12 commented
@amyshwang I have updated as per your request so kindly review!

2022-10-17 08:35 UTC, amyshwang requested changes
Thank you. Please could you ensure that the example output is the actual result from our demo site?

2022-10-17 08:35 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +"Using `row_number()` for "trades" to arrange the table in a sequential manner to depict the transaction history & order these transactions in respect with lowest to highest amount of coins traded"
Please remove the quotation marks and replace the use of "&".

2022-10-17 08:35 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +FROM trades;
I think I mentioned it but this is currently not supported by QuestDB

2022-10-17 08:35 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +
Please remove the quotation marks and add missing full stop.

2022-10-17 08:35 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +| 2.      | ETH-USD   | Sell   |  2615.54 | 0.00044 |
This is not the actual output on the demo site.

2022-10-17 16:53 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +| 2.      | ETH-USD   | Sell   |  2615.54 | 0.00044 |
Yes I know but then the as per the actual output, the partition feature wont be displayed as all the BTC will be displayed before all ETC and the table would be very long to demonstrate in the docs. Hence I used this as an example.

2022-10-17 16:55 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +SELECT symbol,side,price,amount,
I tried various of the queries ad the query suggested by you but none of them seem working in the demo site. Partition query works but issue of timeout occurs. So kindly let me know how to resolve this @amyshwang

2022-10-18 09:28 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +SELECT symbol,side,price,amount,
Does this work?

```
SELECT symbol,side,price,amount, row_number() OVER(PARTITION BY symbol ORDER BY price) AS row_num
FROM trades
where timestamp > dateadd('d', -1, now())
ORDER BY row_num;
```

2022-10-18 09:28 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +| 2.      | ETH-USD   | Sell   |  2615.54 | 0.00044 |
See above my suggested query.

2022-10-22 04:18 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +| 2.      | ETH-USD   | Sell   |  2615.54 | 0.00044 |
@amyshwang Yeaa i have used the query and it works! I was thinking of using another order by symbol function in the same query to show partition between BTC & ETH. But that is more of a sort function so i believe it wont make much difference here.

2022-10-22 04:19 UTC, Smartmind12 commented
@amyshwang let me know if there are any more changes to be made!

2022-10-26 16:40 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- If there are duplicate tuples for the combination of `partitioning` and `order by` columns list, then the function can assign the row numbers in any order for such duplicates leading to non-determi
```suggestion
- If there are duplicate tuples for the combination of `PARTITION BY` and `ORDER BY` columns list, then the function can assign the row numbers in any order for such duplicates leading to non-deterministic results.
```

2022-10-26 16:42 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- If there are duplicate tuples for the combination of `partitioning` and `order by` columns list, then the function can assign the row numbers in any order for such duplicates leading to non-determi
This can be deleted as L386 explains it?

2022-10-26 16:42 UTC, amyshwang commented on docs/reference/function/aggregation.md
> +- Since the rows are returned dynamically, there is no guarantee that the rows returned will be ordered exactly the same with each execution of the query. Hence SQL keywords such as `OVER` & `PARTITI
```suggestion
- Since the rows are returned dynamically, there is no guarantee that the rows returned will be ordered exactly the same with each execution of the query. Hence SQL keywords such as `OVER` and `PARTITION BY` are specified to set unique parameters and organise the row indexing.
```

2022-10-26 17:05 UTC, Smartmind12 commented on docs/reference/function/aggregation.md
> +- If there are duplicate tuples for the combination of `partitioning` and `order by` columns list, then the function can assign the row numbers in any order for such duplicates leading to non-determi
Got it and have made the changes so kindly review! @amyshwang

2022-10-26 19:23 UTC, amyshwang approved these changes
Thank you for your effort! 🚀

2022-10-27 14:52 UTC, merged