Fix documentation inaccuracy (close #1060)
questdb/questdb.io pull request #1116
Opened 2022-10-07 12:12 UTC by 3t8

Change documentation for default partition strategy
#1060

2022-10-07 12:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1116) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1116) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1116) it.</sub>

2022-10-10 16:13 UTC, amyshwang requested changes
This default is used in ingestion via ILP: 
https://questdb.io/docs/reference/configuration/#influxdb-line-protocol
![image](https://user-images.githubusercontent.com/107401731/194909932-4bcecf49-dad8-4e86-84cb-a915c8e94b31.png)

Could we also incorporate the info into the paragraph?

2022-10-10 16:13 UTC, amyshwang commented on docs/reference/api/ilp/overview.md
> +  [partition strategy](/docs/concept/partitions) set to `DAY`. If you would
The partition strategy page has similar wording that needs changing - please ensure that consistency is maintained throughout the document.

2022-10-10 16:14 UTC, amyshwang requested changes
Thank you for your submission! 
Please ensure consistency across the whole Docs and I added a couple of comments too.

2022-10-17 13:21 UTC, jerrinot commented on docs/concept/partitions.md
> +- Default behavior is `PARTITION BY DAY`.
this is misleading. it's BY DAY for tables implicitly created via ILP ingestion and NONE for tables explicitly created via SQL.

2022-10-17 13:23 UTC, jerrinot commented on docs/reference/sql/create-table.md
> +partitioning strategy is `DAY` and tables can be partitioned by one of the
I believe this change should not be done at all. This is the reference documentation for SQL. Tables created via SQL have default partitioning NONE.

2022-10-17 13:27 UTC, amyshwang commented on docs/reference/sql/create-table.md
> +partitioning strategy is `DAY` and tables can be partitioned by one of the
How about changing it to "By default, tables do not have partition.

2022-10-17 13:28 UTC, amyshwang commented on docs/concept/partitions.md
> +- Default behavior is `PARTITION BY DAY`.
We can list both and specify the context.

2022-11-02 21:38 UTC, amyshwang commented
Hi this PR has not been active for a while, I will close this.

2022-11-02 21:38 UTC, closed without merging