Add blog post for SQL Extensions Part II
questdb/questdb.io pull request #1134
Opened 2022-10-15 10:52 UTC by kovid-r

Tutorial blog post for SQL Extensions. This is part II, following up from the previously published [part I](https://towardsdatascience.com/sql-extensions-for-time-series-data-in-questdb-f6b53acf3213). This blog post covers all the features and functionalities revolving around the `SAMPLE BY` keyword.

2022-10-15 10:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1134) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1134) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1134) it.</sub>

2022-10-17 13:00 UTC, amyshwang commented on blog/2022-10-15-sql-extensions-part-ii.md
> +## Understanding the Basics of `SAMPLE BY`
Sentence case, this applies for the rest.

2022-10-17 13:03 UTC, amyshwang commented on blog/2022-10-15-sql-extensions-part-ii.md
> +QuestDB offers an easy way to generate and fill missing data with the `SAMPLE BY` clause. Take the following example: I've deliberately removed data from 4 am to 5 am for the 1st of February 2018. No
My previous comment has not been addressed:

4. Dealing with missing data
“I’ve deliberately removed data from 4 am to 5 am for the 1st of February 2018.” Could you also add more details about how to do so? I had to create a new table:
```
CREATE TABLE 'taxi_trips_missing' AS (
  SELECT * FROM 'taxi_trips'
  WHERE pickup_datetime NOT BETWEEN '2018-02-01T04:00:00' AND '2018-02-01T04:59:59');
```

This is because with the partition (by month) it is not possible to run:

```
ALTER TABLE 'taxi_trips'
DROP PARTITION
WHERE pickup_datetime < ('2018-02-01T04:59:59') AND pickup_datetime > ('2018-02-01T04:00:00');
```

More details will help the reader follow the tutorial?

2022-10-17 13:04 UTC, amyshwang commented on blog/2022-10-15-sql-extensions-part-ii.md
> +QuestDB offers an easy way to generate and fill missing data with the `SAMPLE BY` clause. Take the following example: I've deliberately removed data from 4 am to 5 am for the 1st of February 2018. No
FILL keyword hyperlink should be this: https://questdb.io/docs/reference/sql/sample-by#fill-options

2022-10-17 13:05 UTC, amyshwang commented on blog/2022-10-15-sql-extensions-part-ii.md
> +The `SAMPLE BY` extension also enables you to work change timezones and add or subtract offsets from your timestamp columns to adjust for any issues you might encounter when dealing with different so
```suggestion
The `SAMPLE BY` extension also enables you to change timezones and add or subtract offsets from your timestamp columns to adjust for any issues you might encounter when dealing with different source systems, especially in other geographic areas. It is important to note that, by default, QuestDB aligns its [sample calculation](https://questdb.io/docs/reference/sql/sample-by/#sample-calculation) based on the `FIRST OBSERVATION`, as shown in the example below:
```

2022-10-17 13:08 UTC, amyshwang requested changes
CI build is broken - please update.

2022-10-19 13:34 UTC, kovid-r reviewed
@amyshwang - I have updated the post based on your comments and suggestions. The build is good now. Tested locally.

2022-10-19 13:34 UTC, kovid-r commented on blog/2022-10-15-sql-extensions-part-ii.md
> +  - timeseries
@amyshwang - This is fixed now.

2022-10-19 13:34 UTC, kovid-r commented on blog/2022-10-15-sql-extensions-part-ii.md
> +QuestDB offers an easy way to generate and fill missing data with the `SAMPLE BY` clause. Take the following example: I've deliberately removed data from 4 am to 5 am for the 1st of February 2018. No
I have added the `ALTER TABLE` query for more context. The `FILL` keyword hyperlink was also updated.

2022-10-19 13:34 UTC, kovid-r commented on blog/2022-10-15-sql-extensions-part-ii.md
> +image: /img/blog/2022-08-05/banner.png
@amyshwang - Removed.

2022-10-19 13:34 UTC, kovid-r commented on blog/2022-10-15-sql-extensions-part-ii.md
> +## Understanding the Basics of `SAMPLE BY`
All the headings are in sentence case now.

2022-10-19 13:34 UTC, kovid-r commented on blog/2022-10-15-sql-extensions-part-ii.md
> +The `SAMPLE BY` extension also enables you to work change timezones and add or subtract offsets from your timestamp columns to adjust for any issues you might encounter when dealing with different so
@amyshwang - Updated based on your suggestion.

2022-11-21 14:34 UTC, amyshwang commented
replaced by https://github.com/questdb/questdb.io/pull/1199

2022-11-21 14:34 UTC, closed without merging