chore(docs)Adding pointers in Get started section
questdb/questdb.io pull request #1144
Opened 2022-10-21 09:42 UTC by amyshwang

1. Move Design for performance to Operations, having checked section description in introduction
2. Add a new section in the last page of Get started pointing to some concepts and pages

2022-10-24 16:47 UTC, puzpuzpuz commented on docs/introduction.md
> +- - [Design for performance](/docs/operations/design-for-performance) for configuring
```suggestion
- [Design for performance](/docs/operations/design-for-performance) for configuring
```

2022-10-26 13:18 UTC, amunra requested changes
My suggestions are opinionated: Feel free to accept them / discard them as you see fit.

2022-10-26 13:47 UTC, amyshwang commented on docs/get-started/learn-more.md
> +  ingestion processes out-of-order data
I tweaked it a bit - 
"out-of-order data ingestion and associated configuration parameters."

2022-10-26 13:49 UTC, amyshwang commented on docs/get-started/learn-more.md
> +- [Symbol](/docs/concept/symbol/): a data type designed for repetitive strings
Capitalised the first letters but I don't think full stops should be used as these are not complete sentences.

2022-10-26 14:13 UTC, amunra approved these changes
Lookin' good!

2022-10-26 15:52 UTC, merged