chore(docs) capturing U+
questdb/questdb.io pull request #1158
Opened 2022-10-26 21:52 UTC by amyshwang

Capturing changes in https://github.com/questdb/questdb/pull/2688

2022-10-26 22:01 UTC, amyshwang commented
To add some examples in `micro()`. Currently observation:

```
SELECT micros(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSU'))
FROM long_sequence(1);
```
Returns - 456

```
SELECT micros(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSUU'))
FROM long_sequence(1);
``` 
Returns 560

```
SELECT micros(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSUUU'))
FROM long_sequence(1);
```
Returns 456

```
SELECT millis(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSUU')), 
micros(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSUU'))
FROM long_sequence(1);
```
Returns millis -123; micros - 560

To check the result for:

```
SELECT micros(to_timestamp('2020-03-01:15:43:21.123456', 'yyyy-MM-dd:HH:mm:ss.SSSU+'))
FROM long_sequence(1);
```

2022-11-01 13:55 UTC, bluestreak01 requested changes

2022-11-01 13:55 UTC, bluestreak01 commented on docs/reference/function/date-time.md
> +| `U`    | Microsecond (3 digits)                                                | Number             | 698                                   |
`U` has two personalities:
- when `U` is followed by another `unit` symbols, it will parse 1 digit
- when `U` is followed by a non-`unit` character or line end - 3 digits

2022-11-01 13:56 UTC, bluestreak01 commented on docs/reference/function/date-time.md
> +| `U`    | Microsecond (3 digits)                                                | Number             | 698                                   |
same thing with `S` by the way

2022-11-07 19:39 UTC, amyshwang commented
Capture by https://github.com/questdb/questdb.io/pull/1177

2022-11-07 19:39 UTC, closed without merging