chore(docs) document Kafka ILP connector
questdb/questdb.io pull request #1165
Opened 2022-11-01 13:22 UTC by jerrinot

2022-11-01 22:22 UTC, amyshwang requested changes
Hi I have gone through `ilp.md`. I only understand the high level concept of Kafka so I worry some suggestions might be wrong - however I try to come up with suggestion so you can just add them to one commit.
One thing I am not sure is the terms. I think for people knowing Kafka well, it does not matter. But for document consistency, I think we should decide on fix ways of describing:
- The connector: I use the Kafka Connection connector or just "the connector" in this page. I like how you introduced the concept at the beginning but then I am dropping the "ILP" piece of info. Is this okay? Maybe we can contextualise the connector with ILP in the intro?
- Kafka: I think it is Apache Kafka? I am not sure but I think we should specify what it is in page and section titles at least.

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +
Should "arrives" be changed to "is committed" to be more accurate? Is this correct at all?

```suggestion
When a target table does not exist in QuestDB, it will be automatically created when the first row arrives. This approach is only recommended for development and testing.
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +. This gives you more control over the table schema, allow per-table partitioning, creating indexes, etc.
```suggestion
In production, it's recommended to use the SQL [CREATE TABLE](https://questdb.io/docs/reference/sql/create-table/) keyword, because it gives you more control over the table schema, allowing per-table partitioning, creating indexes, etc.
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +### FAQ
```suggestion
## FAQ
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +**A**: The Connector does not care about serialization strategy used. It relies on Kafka Connect converters to
I would avoid saying 'does not care about' but not sure if this is correct:

```suggestion
**A**: The Connector works independently of the serialization strategy used. It relies on Kafka Connect converters to
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +are using JSON converter, you need to set `value.converter.schemas.enable=false` or `key.converter.schemas.enable=false`
```suggestion
connector does not require schemas, so you need to configure the converter to not expect a schema. For example, if you
are using a JSON converter, you need to set `value.converter.schemas.enable=false` or `key.converter.schemas.enable=false`
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +is available. Bear in mind that QuestDB is meant to be used as append-only database hence updates should be translated
```suggestion
is available. Bear in mind that QuestDB is meant to be used as an append-only database;  hence, updates should be translated
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +record. The transform by default drops DELETE events so no need to handle it explicitly.
```suggestion
record. The transformation by default drops DELETE events, so there is no need to handle them explicitly.
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +**Q**: QuestDB is a time-series database, how does it fit into Change Data Capture via Debezium?
```suggestion
**Q**: QuestDB is a time series database, how does it fit into Change Data Capture via Debezium?  
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +Imagine you have a Postgres table with the most recent stock prices. Whenever a stock price changes an application
```suggestion
Imagine you have a PostgreSQL table with the most recent stock prices. Whenever a stock price changes an application
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +updates the Postgres table. Debezium capture each UPDATE/INSERT and pushes it as an event to Kafka. Kafka Connect
```suggestion
updates the PostgreSQL table. Debezium captures each UPDATE/INSERT and pushes it as an event to Kafka. Kafka Connect
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +prices and QuestDB will have the history of changes. You can use QuestDB to build a dashboard with the most recent stock
Question:
If the most recent prices are in PostgreSQL, then how is it possible to build a price dashboard using QuestDB? 

```suggestion
QuestDB connector reads the events and inserts them into QuestDB. In this way, PostgreSQL will have the most recent stock
prices and QuestDB will have the history of changes. You can use QuestDB to build a dashboard with the most recent stock
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +and `questdb-VERSION.jar`. You can use replace the latter with `questdb-VERSION-jdk8.jar` from
```suggestion
and `questdb-VERSION.jar`. You can replace the latter with `questdb-VERSION-jdk8.jar` from
```

2022-11-01 22:22 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +the [Maven central](https://mvnrepository.com/artifact/org.questdb/questdb/6.5.4-jdk8). Bear in mind this setup is not
```suggestion
the [Maven central](https://mvnrepository.com/artifact/org.questdb/questdb/6.5.4-jdk8). Please note that this setup is not
```

2022-11-02 08:26 UTC, jerrinot commented on docs/third-party-tools/kafka/ilp.md
> +- Kafka
Apache Kafka is the full name and trademark. Surely the Apache Foundation (the trademark owner) would prefer to use the full name exclusively. I feel it's too repetitive and the project is colloquially called just "Kafka". I'm good with either option, up to you, dear editor :)

2022-11-02 08:31 UTC, jerrinot commented on docs/third-party-tools/kafka/ilp.md
> +
I will double-check, but I believe the target table is created even before ILP data are physically committed.

2022-11-02 08:32 UTC, jerrinot commented on docs/third-party-tools/kafka/ilp.md
> +**A**: The Connector does not care about serialization strategy used. It relies on Kafka Connect converters to
you suggestion is correct, thanks!

2022-11-07 15:54 UTC, amyshwang reviewed
Highlighting points to discuss!

2022-11-07 15:54 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +- Kafka
Agree we can drop Apache. Reading through this again I wonder if   we should be consistent in using Kafka or Kafka Connect? (Cf L10)

2022-11-07 15:54 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +A `>` greater-than symbol indicates that a message can be published to the
```suggestion
A greater-than symbol, `>`, indicates that a message can be published to the
```

2022-11-07 15:54 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +| topics                            | STRING  | orders                                                      | N/A                | Topics to read from                                        |
I don't think we use capital letters for data type elsewhere. I think `string` would do?

2022-11-07 15:54 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +**A**: The Connector does not care about serialization strategy used. It relies on Kafka Connect converters to
TBD this has not been incorporated.

2022-11-07 15:54 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
>  description: QuestDB ships a Kafka Connect connector for ingesting messages from a Kafka via the ILP protocol.
A Kafka - a Kafka Connect instance?

2022-11-07 16:24 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
>  description: QuestDB ships a Kafka Connect connector for ingesting messages from a Kafka via the ILP protocol.
- "Kafka connector" using Kafka Connect
- Apache to be mentioned in the first instance and then just Kafka
- ILP connector using Kafka Connect --> QuestDB Kafka connector (Kafka Connect connector)

2022-11-07 16:47 UTC, amyshwang commented
To summarise our discussion with @jerrinot :

1. Naming ILP connector to QuestDB Kafka connector so we will have:

- QuestDB Kafka connector (using ILP)
- JDBC connector (using JDBC)

They are both base on Kafka Connect. 
2. Mentioning Apache Kafka in the first instance and then it should just be Kafka
3. Kafka Connect is a framework on with both QuestDB Kafka connector and JDBC connector are based

2022-11-07 17:48 UTC, amyshwang commented on docs/third-party-tools/kafka/ilp.md
> +
TBD as "arrives" is vague - as a user, I don't know if it means the row will be visible to me

2022-11-07 19:33 UTC, amyshwang reviewed
Highlighting some points about my changes and places I am less sure about.

2022-11-07 19:33 UTC, amyshwang commented on docs/third-party-tools/kafka/questdb-kafka.md
> +complete installing the connector, an archive needs to be downloaded from
I change the wording here because the original gives the impression that Kafka Connect is external to the connector, which I think has changed since our discussion. I don't have a word for "the connector minus Kafka Connect" so this is what I came up with.

2022-11-07 19:33 UTC, amyshwang commented on docs/third-party-tools/kafka/questdb-kafka.md
> +be created for Kafka Connect in the standalone mode. The QuestDB host must match
I don't understand what the standalone mode is but I assume users would know! This section (L57-60) is the part that I understand the least, especially "the QuestDB host" and "the destination QuestDB". I think the destination is where the messages will be sent to. I am not sure about the host. I think it is again another concept that users would understand.

2022-11-07 22:11 UTC, jerrinot commented on docs/third-party-tools/kafka/questdb-kafka.md
> +be created for Kafka Connect in the standalone mode. The QuestDB host must match
what I wanted to say: the config option "host" must point to the IP address (or host/domain/whatever) where QuestDB is running at. 

does it make sense?

2022-11-07 23:30 UTC, amyshwang commented on docs/third-party-tools/kafka/questdb-kafka.md
> +complete installing the connector, an archive needs to be downloaded from
Thanks! Changed parts to components and added this to `dd5a3`

2022-11-07 23:32 UTC, amyshwang commented on docs/third-party-tools/kafka/questdb-kafka.md
> +be created for Kafka Connect in the standalone mode. The QuestDB host must match
I see! I wonder if this step is before or after a user starts the connector? I think the standalone mode refers to:


> 3. Start the QuestDB Kafka connector:
> 
> ```shell
> bin/connect-standalone.sh config/connect-standalone.properties config/questdb-connector.properties
> ```

So I move this little section on config as step 4. If this is not correct, I'd move it to step 3 and the current step 3 should become step 4.

2022-11-08 12:34 UTC, jerrinot commented on docs/third-party-tools/kafka/questdb-kafka.md
> +be created for Kafka Connect in the standalone mode. The QuestDB host must match
indeed, first you have to create the `questdb-connector.properties` file and only then you can start the connector.

2022-11-08 15:30 UTC, amyshwang commented on docs/third-party-tools/kafka/questdb-kafka.md
> +be created for Kafka Connect in the standalone mode. The QuestDB host must match
Understood - reverting this in `0ab998` with bullet points.

2022-11-08 15:30 UTC, amyshwang commented on docs/third-party-tools/kafka/overview.md
> +- Kafka Connect: It is part of the Apache Kafka distribution and provides a framework
It's better indeed - added this to the commit `0ab998`

2022-11-08 16:05 UTC, amyshwang approved these changes
Both @jerrinot and I are happy with the content.

2022-11-08 16:09 UTC, jerrinot commented on docs/third-party-tools/kafka/ilp.md
> +number, the connector will interpret it as a Unix timestamp in milliseconds.
this now says:
> When the field is set to an integer the connector will interpret it as a Unix timestamp in milliseconds.

2022-11-08 16:15 UTC, jerrinot commented on docs/third-party-tools/kafka/ilp.md
> +- Kafka
it should be just Kafka. 
Kafka Connect is part of (Apache) Kafka distribution.

2022-11-08 17:16 UTC, argshook approved these changes

2022-11-08 17:16 UTC, merged