chore(docs) Refining millis and micros unit format
questdb/questdb.io pull request #1166
Opened 2022-11-01 15:08 UTC by amyshwang

1. Separating the following:

- `SSS`
- `S`
- `UUU`
- `U`
2. Amending wording for microsecond precision
3. Updating date and timestamp format section
Adding examples in the function sections too.

2022-11-01 15:30 UTC, bluestreak01 requested changes

2022-11-01 15:30 UTC, bluestreak01 commented on docs/reference/function/date-time.md
> +| `S`    | 3-digit millisecond parsing 1 digit when followed by another `unit`. Otherwise, parsing 3 digits. | Number             | 900                                   |
Can we say:

`1- or 3-digit millisecond....` ?

2022-11-01 15:41 UTC, amyshwang commented on docs/reference/function/date-time.md
> +| `S`    | 3-digit millisecond parsing 1 digit when followed by another `unit`. Otherwise, parsing 3 digits. | Number             | 900                                   |
Updated the text - it is also possible to have 2-digit output so I did not use exactly your wording.

2022-11-02 13:51 UTC, bluestreak01 commented
Lets not rush things and proof read thoroughly

![image](https://user-images.githubusercontent.com/7276403/199506840-1ac6ba52-e57b-4cc7-b73d-a779feb1e9cf.png)

2022-11-02 13:53 UTC, bluestreak01 commented
```
The date and timestamp format is a combination of units from the table below. These units are case-sensitive
```

I'm not sure why we say "and they used as they are, without any prefix". What prefix is implied?

2022-11-02 13:55 UTC, bluestreak01 commented
The title should probably be:

```
Date and timestamp format and units
```

We're describing date format, which is a combination of units and text.

2022-11-02 14:15 UTC, amyshwang commented
I took the decision to use "letters" in the intro because you cannot really say units are case-sensitive. I will probably rewrite the whole thing...

2022-11-02 14:30 UTC, amyshwang commented
I rewrote the intro to:

```
## Date and timestamp formats

Each date or time component is represented by units and arbitrary text. A unit is a combination of letters as defined by the table below. The letters used to form a unit are case-sensitive.
```
I think it is clearer...

2022-11-03 13:34 UTC, bluestreak01 approved these changes

2022-11-03 13:35 UTC, merged