feat(docs) Devoxx article
questdb/questdb.io pull request #1175
Opened 2022-11-04 16:37 UTC by amyshwang

2022-11-08 15:21 UTC, javier requested changes
Looking good. Made two (totally ignorable) comments

2022-11-08 15:21 UTC, javier commented on blog/2022-11-8-questdb-devoxx-belgium-2022.md
> +nearly a quarter of our company should be enough, but the attendees were eager
it is actually a fifth of the company

2022-11-08 15:21 UTC, javier commented on blog/2022-11-8-questdb-devoxx-belgium-2022.md
> +Vlad showcased how CSV import speed is improved thanks to `io_uring`.
Not sure if this is an opportunity to link to our documentation

2022-11-09 16:14 UTC, amunra submitted a review, later dismissed

2022-11-09 16:14 UTC, amunra commented on blog/2022-11-8-questdb-devoxx-belgium-2022.md
> +thanks to `io_uring`.
Maybe a link to https://en.wikipedia.org/wiki/Io_uring for those who don't know what it is?

2022-11-09 16:14 UTC, amunra commented on blog/2022-11-8-questdb-devoxx-belgium-2022.md
> +></iframe>
I feel the article doesn't really have an ending.

Maybe pointers on how to learn more about QuestDB, how to engage with us on Slack or a mention of what upcoming events we'll be at?

Otherwise it's a good post. Reads nice and easy. :+1:

2022-11-10 15:57 UTC, tris0laris approved these changes

2022-11-10 16:07 UTC, javier approved these changes

2022-11-10 16:08 UTC, merged