feat(core): document attach partition when partition.attachable is a symlink
questdb/questdb.io pull request #1176
Opened 2022-11-05 10:17 UTC by marregui

this is the documentation for feature https://github.com/questdb/questdb/pull/2650 :

Users can detach a partition, then detached partitions can be moved to a different volume, perhaps renamed according to some business logic.

To attach one such partition, users must create a symlink [1] inside the table's data folder with the name of the partition to attach followed by .attachable, with target the desired archived partition folder, e.g. for a partition-by-day table 2022-10-19.attachable -> /var/some/random/place/the/user/deemed/2022-10-19.detached.by.andreas

The original copy of the partition attached via soft link will remain READ ONLY for insert, detach/drop partition, add/drop index, add/drop/rename column operations. For instance, this means inserting a new row on the "cold" partition will result in a copy of the partition being made into the "hot" volume where regular partitions for the table exist. Detach/drop partition operations result in the link being removed, not the content being pointed, so the original partition folder is not deleted.

The original copy of the partition attached via soft link WILL BE CHANGED by UPDATE operations, as these use cursors that are unaware of the location of the files being accessed, in terms of whether they contain a soft link. The mechanism to stop the update is lacking at present.

On windows, the operation isSoftLink does not work well, but it is not relevant as deleting the link, instead of unliking it, has the same effect as unlink in other systems, i.e. it removes the link, not the content being pointed.

I have not written all ^ ^ in the docs, as the docs are a reference. Instead I have summarised the above as much as possible while still conveying the same information. This extended version is for context.

Note, there will be a follow up PR to amend UPDATE so that it is also RO

2022-11-07 15:13 UTC, amyshwang requested changes
There are some ambiguity!

2022-11-07 15:16 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +  The copy operation will be costly if the partition volume has a slower disk. The original partition folder is not changed in any way.
This PR also seems to contradict the original [PR description](https://github.com/questdb/questdb/pull/2650): 
>The original copy of the partition attached via soft link will remain READ ONLY for detach/drop partition operations.
>The original copy of the partition attached via soft link WILL BE CHANGED by insert/update operations, as well as add/drop index, add/drop/rename column operations.

2022-11-07 17:08 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +- _insert_, _add index_/_drop index_, _add column_/_drop column_, _rename column_: the partition is copied to the table folder under a new transaction version, where the operation is executed.
Hi Amy, I have amended the text to include your comments, in particular:
- I have capitalised the keywords
- the list has been amended to reflect the current state of questdb/master. There is no copy involved, except in the case when an insert into the partition comes out of order (not worth including in the documentation page, too much detail for an unusual situation).

2022-11-07 17:14 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +  The copy operation will be costly if the partition volume has a slower disk. The original partition folder is not changed in any way.
I have added an info sandwich in the document, to make users aware of disk speeds and their effect on SQL statements that hit partitions attached via symlink.

symlinks are a normal file system concept. They are a file which refers to another file. You have to imagine files as labelled boxes that contain data. A symlink is like a box, it has a label too, but it is empty, instead the bottom is broken and you magically enter the box the symlink is pointing to. So in effect, opening the symlink box is like opening the target box, except you can hit the symlink box with a hammer and the data within the target box will be ok. I have added a wikipedia link.

I have updated the text in general to reflect the current state of questdb/master, where attaching via symlink is not read-only yet.

2022-11-07 17:14 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +- _drop partition_/_detach partition_: the partition is unlinked, the symlink is removed but not the content of the partition folder. Detaching a partition that was attached via symlink does not
the detach page points right back to this page.

2022-11-07 21:44 UTC, amyshwang reviewed
I refactored the content and added some examples.
I added a few questions as well.

2022-11-07 21:44 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +    - _UPDATE_: the partition folder's data files are modified in place.
What is the difference between this and L64?

2022-11-07 21:44 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +      are modified in place as a result of the operation. The name of the symbolic link will change as a result.
>The name of the symbolic link will change as a result.
Isn't this mean that further operations won't be possible, because the name is changed?

2022-11-08 13:33 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +    - _UPDATE_: the partition folder's data files are modified in place.
none, I will merge these two items.

2022-11-08 16:03 UTC, amyshwang requested changes
I made a few suggestions that can be committed directly but the example codes are not something I am confident in making suggestions, so I left some comments.

2022-11-08 16:03 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +lrwxr-xr-x  1 marregui  staff     28 Nov  8 15:13 2022.attachable -> ../../cool/tab/2022.detached
Should we try to remove your name and make this more generic?

2022-11-08 16:03 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +In windows, symlinks require admin privileges, and thus it is not recommended its use.
```suggestion

- SQL statements that hit partitions attached via symbolic links may have slower runtimes
if their volumes have a slower disk.

- In Windows, symbolic links require admin privileges, and thus this method is not recommended.
```

2022-11-08 16:28 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +questdb@NYC:~/QUEST/db/tab$ ls -l
listing the folder, I will amend.

2022-11-08 17:33 UTC, amyshwang requested changes
Only one minor suggestion!

2022-11-08 17:33 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +- The very last partition cannot be detached, however it can be dropped.
```suggestion
- The latest partition cannot be detached. However, it can be irreversibly deleted using [DROP TABLE](/docs/reference/sql/drop/).
```

2022-11-08 19:42 UTC, amyshwang approved these changes
Thank you!

2022-11-09 07:50 UTC, argshook approved these changes

2022-11-09 07:51 UTC, merged