chore(docs) `N+` and `U+`
questdb/questdb.io pull request #1177
Opened 2022-11-07 19:39 UTC by amyshwang

Capturing
- https://github.com/questdb/questdb/pull/2709
- https://github.com/questdb/questdb/pull/2688

2022-11-08 04:20 UTC, bluestreak01 requested changes

2022-11-08 04:20 UTC, bluestreak01 commented on docs/reference/function/date-time.md
> +| `N`    | Nanosecond. QuestDB provides microsecond resolution so the parsed nanosecond will be truncated.                | Number             | N/A (truncated)                       |
These “units” solve a problem, but when I read description in isolation I cannot relate to anything. This is a specially the case of “+” units that were bourn out of real need

2022-11-08 22:27 UTC, amyshwang commented on docs/reference/function/date-time.md
> +| `N`    | Nanosecond. QuestDB provides microsecond resolution so the parsed nanosecond will be truncated.                | Number             | N/A (truncated)                       |
I am keeping this section slim but linking and adding to the timestamp guide. Will ned to verify the result when 6.5.5 is available either on demo or on Homebrew though.

2022-11-11 12:55 UTC, bluestreak01 approved these changes

2022-11-11 12:55 UTC, bluestreak01 commented on docs/reference/function/date-time.md
> +| `N+`   | 9-digit nanosecond. QuestDB provides microsecond resolution so the parsed nanosecond will be truncated.        | Number             | N/A (truncated)                       |
do you think it would make sense to link the section you added with N+ example to this reference manual ?

2022-11-11 17:15 UTC, amyshwang commented on docs/reference/function/date-time.md
> +| `N+`   | 9-digit nanosecond. QuestDB provides microsecond resolution so the parsed nanosecond will be truncated.        | Number             | N/A (truncated)                       |
I did - L989-992. This is a big section so it is a bit far away from this line...

2022-11-11 17:25 UTC, merged