feat(docs) INSERT INTO WITH AS
questdb/questdb.io pull request #1180
Opened 2022-11-09 21:19 UTC by amyshwang

- Capturing https://github.com/questdb/questdb/pull/2724
- Removing references to outdated import guide

2022-11-11 13:00 UTC, bluestreak01 requested changes

2022-11-11 13:00 UTC, bluestreak01 commented on docs/reference/sql/with.md
> +WITH up AS (
this is incorrect SQL, you got to try these, can't be opportunistic here

2022-11-11 13:04 UTC, bluestreak01 commented on docs/reference/sql/with.md
> +WITH up AS (
correct QuestDB syntax is this:

```sql
insert into 'ilp_test' 
WITH confirmed_id AS (
    SELECT * FROM 'ilp_test'
    )
SELECT * FROM confirmed_id;
```

a) this is my fault, syntax I implemented is not compatible with PG
b) you can't take PG syntax on face value and hope it will work, there are tests in the codebase showing how it works:

https://github.com/questdb/questdb/pull/2724
https://github.com/questdb/questdb/pull/2724/files

2022-11-11 17:08 UTC, amyshwang commented
Convert to draft as we will implement the PG syntax.

2022-11-14 15:14 UTC, amyshwang commented on docs/reference/sql/with.md
> +WITH up AS (
This will be changed by https://github.com/questdb/questdb/pull/2773

2022-11-15 13:54 UTC, bluestreak01 approved these changes

2022-11-15 13:54 UTC, merged