chore(docs) python example for PG data insertion
questdb/questdb.io pull request #1192
Opened 2022-11-17 16:03 UTC by amyshwang

Current problem:
```
Table created.
2022-11-17 15:58:26.715278
2022-11-17
Traceback (most recent call last):
  File "/Users/work/Repos/python_amy/pg.py", line 25, in <module>
    cur.execute('''
  File "/opt/homebrew/lib/python3.10/site-packages/psycopg/cursor.py", line 725, in execute
    raise ex.with_traceback(None)
psycopg.DatabaseError: `
```

2022-11-24 16:55 UTC, amyshwang commented on docs/develop/insert-data.md
> +        for x in range(10):
`        for x in range(10):
            now = dt.now()
            now_timestamp = dt.timestamp(now)
            print(now_timestamp)
            date = dt.today()
            print(date)
            date_timestamp = dt.timestamp(date)

            cur.execute('''
                INSERT INTO test_pg
                    VALUES (%s, %s, %s, %s);
                ''',
                (now_timestamp, date_timestamp, 'python example', x))`

2022-11-25 13:42 UTC, amyshwang commented on docs/develop/insert-data.md
> +from datetime import datetime as dt
What is the difference between the existing and:
```suggestion
import datetime as dt
```
Sometimes you want to import some of the module?
I have seen:
`from datetime import date`

2022-11-25 13:44 UTC, amyshwang commented on docs/develop/insert-data.md
> +            timestamp = int(dt.timestamp(dt.now())*1000000)
This feels very hacky...

2022-11-25 13:45 UTC, amyshwang commented on docs/develop/insert-data.md
> +            # Converting datetime into millisecond for QuestDB
```suggestion
            # Convert "datetime" timestamp (double) into millisecond for QuestDB
```

2022-11-25 15:55 UTC, amyshwang commented on docs/develop/insert-data.md
> +from datetime import datetime as dt
p.s. `import datetime as dt` causes this error:
```
➜  python_amy python3 pg.py
Table created.
Traceback (most recent call last):
  File "/Users/work/Repos/python_amy/pg.py", line 18, in <module>
    timestamp = int(dt.timestamp(dt.now())*1000000)
AttributeError: module 'datetime' has no attribute 'timestamp'
````

2022-11-30 12:11 UTC, amunra requested changes
Looks good.
A few touch-ups required.

2022-11-30 12:11 UTC, amunra commented on docs/develop/insert-data.md
>  [psychopg3](https://github.com/psycopg/psycopg3/projects/1) adapter.
Swap out link for: https://www.psycopg.org/psycopg3/docs/

2022-11-30 12:11 UTC, amunra commented on docs/develop/insert-data.md
>  [psychopg3](https://github.com/psycopg/psycopg3/projects/1) adapter.
Add:
-------


To [install](https://www.psycopg.org/psycopg3/docs/basic/install.html) the client library, use `pip`:

```bash
python3 -m pip install "psycopg[binary]"
```

2022-12-01 10:09 UTC, amunra commented on docs/develop/insert-data.md
> +from datetime import datetime as dt
> p.s. `import datetime as dt` causes this error:
> 
> ```
> ➜  python_amy python3 pg.py
> Table created.
> Traceback (most recent call last):
>   File "/Users/work/Repos/python_amy/pg.py", line 18, in <module>
>     timestamp = int(dt.timestamp(dt.now())*1000000)
> AttributeError: module 'datetime' has no attribute 'timestamp'
> ```

**TL;DR**: All code that previously read `dt.SOMETHING` should now read `dt.datetime.SOMETHING`.

Here's the why:

```python
>>> # this imports the _module_. It contains classes and functions to work with dates, times, intervals etc.
>>> import datetime
>>> datetime
<module 'datetime' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/datetime.py'>

>>> # the suggested change also imports the module, but aliased.
>>> import datetime as dt
>>> dt
<module 'datetime' from '/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/datetime.py'>

>>> # these really are the same thing and the alias just reduces keystrokes.
>>> dt is datetime
True

>>> # there's also a `datetime.datetime` class which represents a point in time.
>>> datetime.datetime
<class 'datetime.datetime'>
>>> # or, using our alias (which I think is actually clearer in this specific case).
>>> dt.datetime
<class 'datetime.datetime'>

>>> # if we create an instance of it with the current time (UTC timezone)
>>> utc_now = dt.datetime.utcnow()
>>> utc_now
datetime.datetime(2022, 12, 1, 10, 5, 22, 825853)

>>> # We can now convert it to a timestamp
>>> utc_now.timestamp()
1669889122.825853
```

2022-12-01 10:14 UTC, amunra commented on docs/develop/insert-data.md
> +            timestamp = int(dt.timestamp(dt.now())*1000000)
this should probably obtain the current `utc` time and not the current local time:

```
timestamp = int(dt.datetime.utcnow().timestamp() * SEC_TO_MICROS)
```

and there should be a global set (right after the import statements) with:

```
SEC_TO_MICROS = 1000000
```

It's worth doing a quick check to be sure the date that appears in the DB is the same as the one you expect and isn't skewed by a few hours because of timezone differences.

2022-12-01 10:22 UTC, amunra commented on docs/develop/insert-data.md
> +            timestamp = int(dt.timestamp(dt.now())*1000000)
Scratch that.. there's actually a more accurate way to this altogether:

```python
import time

...

timestamp = time.time_ns() // 1000
```

This approach avoids getting confused with timezones, intermediate objects and float to integer conversions.

^^^^^ Do this ^^^^^

It probably means you can drop the `import datetime` part as well.

2022-12-01 10:26 UTC, amunra commented on docs/develop/insert-data.md
> +from datetime import datetime as dt
Scratch this... there's a better way to do this with `time.time_ns()`. See comment later on. No need to `import datetime`.

2022-12-02 12:54 UTC, merged