feat(docs) Aligning with commit lag change for 6.6
questdb/questdb.io pull request #1197
Opened 2022-11-18 17:41 UTC by amyshwang

Closes [#1188](https://github.com/questdb/questdb.io/issues/1188)

2022-11-22 13:07 UTC, bluestreak01 requested changes

2022-11-22 13:07 UTC, bluestreak01 commented on docs/reference/sql/alter-table-set-param.md
> +[configuring commit lag of out-of-order data](/docs/guides/out-of-order-commit-lag)
we need to describe the meaning of o3MaxLag here:

`o3MaxLag` defines the max size of in-memory buffer in millis. Buffer is allocated dynamically thru analysing shape of the incoming data with `o3MaxLag` being the upper limit.

2022-11-22 13:07 UTC, bluestreak01 commented on docs/reference/sql/insert.md
> +## Parameters for QuestDB 6.5.5 and earlier versions
`batch` parameter is still relevant and should be documented

2022-11-22 13:07 UTC, bluestreak01 commented on docs/reference/sql/select.md
> +- For QuestDB 6.5.5 and earlier versions, data ingested via ILP may not be
lets remove any mention of lag from `SELECT` doc, it is highly confusing

2022-11-22 13:07 UTC, bluestreak01 commented on docs/troubleshooting/faq.md
> +into commit batches. Fos QuestDB 6.5.5 and earlier versions, this results in
this is a confusing statement. I would remove the entire paragraph. What is `false` here is that server does actually commit on disconnect.

2022-11-22 13:07 UTC, bluestreak01 commented on docs/troubleshooting/faq.md
> +data not being visible in `SELECT` queries immediately after being received.
lets not mess with explaining immediacy, data is immediate - should be non-issue for the user. If data is not immediate - upgrade to 6.6.

2022-11-22 13:07 UTC, bluestreak01 commented on sidebars.js
> +        "guides/out-of-order-commit-lag",
remove

2022-11-22 15:39 UTC, amyshwang commented on docs/reference/sql/alter-table-set-param.md
> +[configuring commit lag of out-of-order data](/docs/guides/out-of-order-commit-lag)
Wording added to the configuration section.
If we add the explanation of o3MaxLag here, we might also want to use it in the diagram and the rest of the page?

2022-11-22 15:55 UTC, amyshwang commented on docs/reference/sql/alter-table-set-param.md
> +[configuring commit lag of out-of-order data](/docs/guides/out-of-order-commit-lag)
Marking "Deprecated content" at the top of the page.

2022-11-24 16:48 UTC, jerrinot commented on docs/concept/designated-timestamp.md
>  ## Out-of-order policy
maybe we can remove this box? 
<img width="870" alt="image" src="https://user-images.githubusercontent.com/158619/203834330-a8061b63-fb1a-42ce-afb5-7d43ef40f5fb.png">

nobody should be using version before 6.0.

2022-11-24 16:53 UTC, jerrinot commented on sidebars.js
> -        "guides/out-of-order-commit-lag",
I believe we removed it from the menu, because it's no longer relevant and we do not want to bother users with details required for old versions only. and at the same time the page is not entirely removed, because it's indexed by Google? Is that right? If I go to https://deploy-preview-1197--unruffled-blackwell-31bfb2.netlify.app/docs/guides/out-of-order-commit-lag/ then I see the page, but it looks a bit lost. Like it's not part of the docs. Is that intentional?

<img width="1324" alt="image" src="https://user-images.githubusercontent.com/158619/203835148-ba5cbd8a-1f0e-458e-878a-3b06d4e56530.png">

2022-11-24 17:00 UTC, jerrinot commented on docs/reference/configuration.md
> +| line.tcp.commit.interval.default           | 1000         | Default commit interval in milliseconds. Used when no commit lag set for a table or the fraction is set to 0.
> Used when no commit lag set [...]
What does it mean? There is no commit lag configuration anymore. Is it when max.lag is set to 0?

2022-11-24 17:04 UTC, jerrinot commented on docs/reference/function/meta.md
> +| id  | name        | designatedTimestamp | partitionBy | maxUncommittedRows |
it's missing the `o3MaxLag` column. (also the walEnabled, but I am not sure if we want to talk about WAL yet)
![Uploading image.png…]()

2022-11-24 17:04 UTC, jerrinot commented on docs/reference/function/meta.md
> +| id  | name        | designatedTimestamp | partitionBy | maxUncommittedRows |
<img width="1187" alt="image" src="https://user-images.githubusercontent.com/158619/203836814-2f736713-884a-4735-b693-ec55d6ddfcae.png">

2022-11-24 17:07 UTC, jerrinot commented on docs/reference/sql/create-table.md
> +:::note
I'm a bit confused here. specifically the `maxUncommittedRows` parameter. I don't know how the new commit works, but `tables()` in 6.6 still shows the `maxUncommittedRows` hence I presume it's configurable per-table? While this deprecation notice makes the impression it's gone for good?

2022-11-24 17:09 UTC, jerrinot commented on docs/troubleshooting/faq.md
> +Please upgrade to QuestDB 6.6 or later versions for dynamic data ingestion
Even in 6.6 it's not available immediately. It's just the configuration is automatic. but I assume for heavily O3 data the dynamic lag will grow -> data will not be visible -> users will still be confused?

2022-11-24 17:12 UTC, jerrinot requested changes
I don't really understand the new impl, but here are the 2 most important notes:
1. there is a confusion about the `maxUncommitedRows` configuration. Is it really gone for good? Why is `tables()` showing it?
2. I think we should not pretend the O3 lag is gone and the problem is solved. There will still be users who won't be confused why there don't see data their inserted. I assume the new impl makes life much easier for users without O3 inserts. But users will O3 will still experience the delay and we should describe it.

2022-11-24 18:44 UTC, amyshwang commented on sidebars.js
> -        "guides/out-of-order-commit-lag",
Vlad suggested removing it from the sidebar - as you said, it is irrelevant and we don't want people to land on it unless they have to.
However, I did not notice the behaviour so I will add it back.

2022-11-24 18:52 UTC, amyshwang commented on docs/reference/configuration.md
> +| line.tcp.commit.interval.default           | 1000         | Default commit interval in milliseconds. Used when no commit lag set for a table or the fraction is set to 0.
I think the system uses it when commit lag (which is dynamic between max.lag and min.lag) value is 0. I will remove this...

2022-11-24 18:58 UTC, amyshwang commented on docs/reference/function/meta.md
> +| id  | name        | designatedTimestamp | partitionBy | maxUncommittedRows |
Reverted the deletion and added it back as o3MaxLag

2022-11-24 18:59 UTC, amyshwang commented on docs/reference/sql/create-table.md
> +:::note
My misunderstanding - only commitLag is gone.

2022-11-24 19:03 UTC, amyshwang commented on docs/troubleshooting/faq.md
> +Please upgrade to QuestDB 6.6 or later versions for dynamic data ingestion
Yes but in this case it is the nature of the data. I feel the answer is not really adding much. I suggest deleting this and collect new FAQ later if required.

2022-11-24 19:55 UTC, jerrinot approved these changes

2022-11-25 09:59 UTC, insmac approved these changes

2022-11-25 10:03 UTC, tris0laris commented on docs/guides/out-of-order-commit-lag.md
> +visible for any relevant queries.
"any relevant" : i would remove

2022-11-25 10:05 UTC, tris0laris commented on docs/introduction.md
> +  guide for once QuestDB is running
I think we need to delete "for" ?

2022-11-25 10:06 UTC, tris0laris commented on docs/introduction.md
> +  topics into QuestDB
from topics or from Kafka topics?

2022-11-25 10:08 UTC, tris0laris commented on docs/introduction.md
>  - [JIT compiler](/docs/concept/jit-compiler) to speed up queries
should it not be "WHERE" queries specifically?

2022-11-25 10:10 UTC, tris0laris commented on docs/introduction.md
> +  benefits on calculations and queries
this is a bit convoluted. what about: 
should be used to lift less data for time-based queries

2022-11-25 10:17 UTC, amyshwang commented on docs/guides/out-of-order-commit-lag.md
> +visible for any relevant queries.
```suggestion
visible for queries.
```

2022-11-25 10:17 UTC, amyshwang commented on docs/introduction.md
> +  guide for once QuestDB is running
```suggestion
  guide once QuestDB is running
```

2022-11-25 10:21 UTC, amyshwang commented on docs/introduction.md
> +  benefits on calculations and queries
```suggestion
- [Partitions](/docs/concept/partitions) can be used to perform time-based queries more efficiently
```

2022-11-25 10:23 UTC, amyshwang commented on docs/introduction.md
> +  benefits on calculations and queries
I find "list less data" very vague but agree it could be simplified -edited your suggestion. I will keep "can" too because it is a suggestion.

2022-11-25 10:30 UTC, amyshwang commented on docs/introduction.md
>  - [JIT compiler](/docs/concept/jit-compiler) to speed up queries
Sorry I don't understand what you meant, this is reflecting the sidebar so the items are fixed?

2022-11-25 10:33 UTC, tris0laris commented on docs/introduction.md
>  - [JIT compiler](/docs/concept/jit-compiler) to speed up queries
- [JIT compiler](/docs/concept/jit-compiler) to speed up queries

my question is: should we be more specific, saying that we speed "WHERE" queries ? its a question btw, not asking you to do it

2022-11-25 10:36 UTC, amyshwang commented on docs/introduction.md
>  - [JIT compiler](/docs/concept/jit-compiler) to speed up queries
```suggestion
- [JIT compiler](/docs/concept/jit-compiler) to speed up `WHERE` clauses
```

2022-11-25 11:11 UTC, tris0laris approved these changes

2022-11-25 11:13 UTC, merged