chore(docs) blog post SAMPLE BY
questdb/questdb.io pull request #1199
Opened 2022-11-21 14:03 UTC by amyshwang

Also fixing formatting issue in Prediko

2022-11-21 15:14 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +title: SQL extensions for time series data in QuestDB - part II
```suggestion
title: SQL Extensions for Time Series Data in QuestDB - Part II
```

2022-11-21 17:03 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +line chart, a bar graph, or an area chart to
```suggestion
line, bar, or an area chart to
```

2022-11-21 17:04 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +example of a bar chart drawn from the query mentioned above:
```suggestion
example of a bar chart drawn from the above query:
```

2022-11-21 17:07 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +clause with the help of the `NOT BETWEEN` keyword. Alternatively, you can create
```suggestion
data with the help of the `NOT BETWEEN` keyword. Alternatively, you can create
```

2022-11-21 17:07 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +Ideally, you should use `DROP PARTITION` to emulate missing data, but because
Why should we use `DROP PARTITION`?

2022-11-21 17:09 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +encounter when dealing with different source systems, especially in other
```suggestion
encounter when dealing with different source systems, especially in different
```

2022-11-21 17:10 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +Note now the `1d` sample calculation starts at `13:35:52` and ends at `13:35:51`
```suggestion
Note that now the `1d` sample calculation starts at `13:35:52` and ends at `13:35:51`
```

2022-11-21 17:11 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +the next day. Apart from the one demonstrated above, there are two other ways to
```suggestion
the next day. Apart from the option demonstrated above, there are two other ways to
```

2022-11-21 17:11 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +Let's look at the other two alignment methods now.
```suggestion
Let's take a look at the other two alignment methods.
```

2022-11-21 17:13 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +When moving data from one system to another or via a complex pipeline, you can
```suggestion
When moving data across systems, pipelines, and warehouses, you can
```

2022-11-21 17:15 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +that you've identified that the data set you've loaded into the database is not
```suggestion
that you're working in New York City, but you've identified that the timestamps of the data set you've loaded into the database are in Australian Eastern Time (instead of New York's EST).  Traditionally, this could lead to extra conversion work to ensure that this new data is comparable to the rest of your data in EST.
```

2022-11-21 17:20 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +QuestDB allows you to fix this issue by aligning your data to another timezone
```suggestion
QuestDB allows you to easily fix this issue by aligning your data to another timezone
```

2022-11-21 17:20 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +that you've identified that the data set you've loaded into the database is not
^ replaces the rest of the paragraph

2022-11-21 17:21 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +`ALIGN TO CALENDAR TIME ZONE ('AEST')` has helped align the `pickup_datetime`,
```suggestion
`ALIGN TO CALENDAR TIME ZONE ('AEST')` has aligned the `pickup_datetime`,
```

2022-11-21 17:21 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +Similar to the previous example, you can also align your sample calculation by
```suggestion
Similar to the previous example, you can also align the sample calculation by
```

2022-11-21 17:21 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +the `SAMPLE BY` extension also allows you to fix specific common problems with
```suggestion
the `SAMPLE BY` extension also allows you to fix common problems with
```

2022-11-21 17:22 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +extensions like `SAMPLE BY` provide a significant advantage when working with
```suggestion
extensions in QuestDB, like `SAMPLE BY`, provide a significant advantage when working with
```

2022-11-22 09:20 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +detail about the [`SAMPLE BY` extension](/docs/reference/sql/sample-by/) in
```suggestion
that make time-series analysis easier. Today, you will learn about the [`SAMPLE BY` extension](/docs/reference/sql/sample-by/) in detail,
```

2022-11-22 09:20 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +QuestDB, which will enable you to work with time-series data efficiently because
```suggestion
which will enable you to work with time-series data efficiently because
```

2022-11-22 09:24 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +By converting the `pickup_datetime` column to timestamp, you'll allow QuestDB to
I will change it this way:

```suggestion
By converting the `pickup_datetime` column to `timestamp`, you allow QuestDB to
```

2022-11-22 09:25 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +microseconds to months and everything in between, i.e., millisecond, second,
```suggestion
microseconds to months and everything in between (millisecond, second,
```

2022-11-22 09:29 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +and are in very different time zones.
```suggestion
that you're working in New York City, but you've identified that the timestamps of the data set you've loaded into the database are in Australian Eastern Time (instead of New York's EST). Traditionally, this could lead to extra conversion work to ensure that this new data is comparable to the rest of your data in EST.
```

2022-11-22 10:23 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +Ideally, you should use `DROP PARTITION` to emulate missing data, but because
Using drop partition, there is no need to create a new table. I think it is a digression and will delete it and move the CREATE TABLE section to the end of this section as additional info.
Fixed in `1a5b8f`

2022-11-22 10:23 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +starting at 4 am and fill it with some data:
Yes details added in `1a5b8f`.

2022-11-22 10:32 UTC, amyshwang commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +QuestDB mandates the use of an ordered timestamp column, so you'll have to cast
It's needed to use SAMPLE BY and it works with the designated timestamp so yes one per table - the information is in the paragraph after the code and ti is not ideal. I will add something here in `1a5b8f`.

2022-11-22 15:11 UTC, sklarsa approved these changes
A few small changes, otherwise lgtm

2022-11-22 15:11 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +By converting the `pickup_datetime` column to `timestamp`, you allow QuestDB to
```suggestion
By converting the `pickup_datetime` column to `timestamp`, you are allowing QuestDB to
```

2022-11-22 15:11 UTC, sklarsa commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +microseconds to months and everything in between (millisecond, second, minute,
```suggestion
microseconds to months and everything in between (milliseconds, seconds, minutes,
```

2022-11-23 09:46 UTC, argshook requested changes

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/f5lVlQL.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/8hD7Lmw.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/gN0LO6g.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/U9m6k6s.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/szB7CMD.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> +![](https://i.imgur.com/3xyC6kt.png)
let's not use a 3rd-party provider to host our images.
Images should be in `/static/img/blog/2022-11-23`

this is repeated in multiple places in this file.
I'm leaving the same comment on each as a mark.

2022-11-23 09:46 UTC, argshook commented on blog/2022-11-23-sql-extensions-time-series-data-questdb-part-ii.md
> + SAMPLE BY 1h;
nit: some queries in this blog post have off-looking indentation.

To keep formatting consistent i usually use the `format selection`
function on our [demo web-console](https://demo.questdb.io/): 

![image](https://user-images.githubusercontent.com/4284659/203515279-a6d0e899-a8b9-4a03-a5e4-34a3509f79d2.png)

after formatting this query it looks like this:

```suggestion
SELECT
  pickup_datetime,
  COUNT() total_trips
FROM
  'taxi_trips' SAMPLE BY 1h;
```

usually it works really nice but sometimes it might be too "new-liney".

Just wanted to share my approach, feel free to decide whether it's worth
doing this on this blog post.

2022-11-23 10:38 UTC, argshook submitted a review, later dismissed

2022-11-23 11:31 UTC, argshook approved these changes

2022-11-23 11:38 UTC, merged