feat(sql): added documentation for trigonometric functions sin, cos, tan, cot, asin, acos, atan, atan2, radians, degrees, pi
questdb/questdb.io pull request #1245
Opened 2022-12-30 11:42 UTC by marregui

Documents https://github.com/questdb/questdb/pull/2890

2023-01-03 09:50 UTC, amyshwang requested changes
I will add commits for general formatting and wording but some questions to be clarified:

1. Some special cases are just how trigonometric works - do we need to specify them? (e.g. sin 0 = 0)
2. `atan2` has wrong example. Also I found the input (y, x) strange...

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +- `angleRadians` numeric value for the angle, in radians.
```suggestion
- `angleRadians` is a numeric value for the angle in radians.
```

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +The sine of the argument, of type `Double``.
```suggestion
Return value type is `double`.
```

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +- If the argument is zero, then the result is a zero with the same sign as the argument.
I am not sure if `sin 0 = 0` is a special case. I don't know what you mean "with the same sign as the argument" though.

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +- If the argument is zero, then the result is a 1.0.
Again this is always the case not specific to this function - do we need to mention this?

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +| 0.7853981633974483 |
This does not make sense to me: there should be 2 inputs and the function is `tan2`?

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +`atan2(valueY, valueX)` returns the angle *theta* from the conversion of rectangular coordinates (x, y) to polar (r, theta).
The input is asking for (y, x) so the description might need to change to:
```suggestion
`atan2(valueY, valueX)` returns the angle *theta* from the conversion of rectangular coordinates (y, x) to polar (r, theta).
```
I am also not sure the design for the input to be (y, x) - (x, y) is more intuitive?

2023-01-03 09:50 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +SELECT PI()/2 angle, sin(PI()/2) sin;
PI should be pi?

2023-01-03 10:16 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +`atan2(valueY, valueX)` returns the angle *theta* from the conversion of rectangular coordinates (x, y) to polar (r, theta).
Checked PostgreSQL atan2 and this might work better:
```
Inverse tangent of y/x, result in radians
```

2023-01-03 10:50 UTC, marregui commented on docs/reference/function/trigonometric.md
> +- If the argument is zero, then the result is a zero with the same sign as the argument.
```sql
select sin(0.0), sin(-0.0), cos(0.0), cos(-0.0), tan(0.0), tan(-0.0)
```
| sin | sin1  | cos | cos1 | tan | tan1 |
|----|-----|-----|------|----|------|
| 0.0 | -0.0 | 1.0  | 1.0.   | 0.0 | -0.0 |

2023-01-03 10:51 UTC, marregui commented on docs/reference/function/trigonometric.md
> +- If the argument is zero, then the result is a 1.0.
this documents the expected result for those cases

2023-01-03 10:54 UTC, marregui commented on docs/reference/function/trigonometric.md
> +`atan2(valueY, valueX)` returns the angle *theta* from the conversion of rectangular coordinates (x, y) to polar (r, theta).
lol. this is just a pass through call to Math.atan2, with documentation extracted verbatim.

2023-01-03 10:56 UTC, marregui commented on docs/reference/function/trigonometric.md
> +SELECT PI()/2 angle, sin(PI()/2) sin;
ok

2023-01-04 15:53 UTC, amyshwang commented on docs/reference/function/trigonometric.md
> +- If the argument is zero, then the result is a 1.0.
`cos0 = 1` should not need special documentation as this is just math? Unless you meant that it is special in that it is a double, `1.0` instead of `1` - in which case the "return value" section conveys it already?

2023-01-09 13:49 UTC, marregui commented on docs/reference/function/trigonometric.md
> +- If the first argument is negative zero and the second argument is positive, or
bug in web console

2023-01-09 13:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1245) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1245) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: amyshwang<br/>:white_check_mark: marregui<br/>:white_check_mark: bziobrowski<br/>:white_check_mark: argshook<br/>:white_check_mark: insmac<br/>:x: dependabot[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1245) it.</sub>

2023-01-20 10:38 UTC, amyshwang approved these changes

2023-01-22 22:19 UTC, merged