chore(docs) Adding pandas to third-party tool
questdb/questdb.io pull request #1253
Opened 2023-01-06 15:53 UTC by amyshwang

The officla Pytthon client page containt the main info so this is more like a pointer...

2023-01-06 17:09 UTC, amunra approved these changes
Thanks!

2023-01-06 17:09 UTC, amunra commented on docs/introduction.md
> +- [Prometheus](/docs/third-party-tools/prometheus/) monitoring and alerting.
Why some lines end with '.' and others don't?

2023-01-06 17:09 UTC, amunra commented on docs/third-party-tools/pandas.md
> +- [Sender.dataframe()](https://py-questdb-client.readthedocs.io/en/latest/api.html#questdb.ingress.Sender.dataframe)
Can you add a link to all the dataframe examples?

https://py-questdb-client.readthedocs.io/en/latest/examples.html#data-frames

2023-01-06 17:10 UTC, amunra requested changes
Sorry.. hit the wrong button.

A few minor changes required.

2023-01-16 12:49 UTC, amunra requested changes
Minor tidy-up.

2023-01-16 13:42 UTC, amyshwang commented on docs/third-party-tools/pandas.md
> +provides native support for ingesting Pandas DataFrame via the InfluxDB Line Protocol (ILP).
```suggestion
provides native support for ingesting Pandas dataframes via the InfluxDB Line Protocol (ILP).
```

2023-01-16 13:42 UTC, amyshwang commented on docs/third-party-tools/pandas.md
> +- Python 3.7 or later
```suggestion
- Python 3.8 or later
```

2023-01-16 13:42 UTC, amyshwang commented on docs/introduction.md
> +- [Pandas](/docs/third-party-tools/pandas/) for ingesting Pandas DataFrames via ILP
```suggestion
- [Pandas](/docs/third-party-tools/pandas/) for ingesting Pandas dataframes via ILP
```

2023-01-16 16:58 UTC, amunra approved these changes
Lookin' good now.

2023-01-16 17:11 UTC, merged