add newsletter no. 3 as blog post
questdb/questdb.io pull request #1262
Opened 2023-01-09 18:32 UTC by argshook

2023-01-10 18:25 UTC, amyshwang requested changes
Preview and banner images not working.

2023-01-10 18:25 UTC, amyshwang commented on blog/2021-03-02-newsletter-3.md
> +image: /img/blog/newsletter-preview.png
Not showing.

2023-01-10 18:25 UTC, amyshwang commented on blog/2021-03-02-newsletter-3.md
> +  src="/img/blog/newsletter.png"
Not rendering - although I updated the PR with master...

2023-01-10 18:42 UTC, argshook commented on blog/2021-03-02-newsletter-3.md
> +image: /img/blog/newsletter-preview.png
oops, clicked `resolve` accidentally.

although these images do load for me ok it seems.
i'm looking at netlify preview [here in the blog posts list](https://deploy-preview-1262--unruffled-blackwell-31bfb2.netlify.app/blog/tags/newsletter/) and [here on the blog post itself](https://deploy-preview-1262--unruffled-blackwell-31bfb2.netlify.app/blog/newsletter-out-of-order-inserts/)

could it be you checked it before preview got updated?

2023-01-12 11:51 UTC, amyshwang commented on blog/2021-03-02-newsletter-3.md
> +slug: newsletter-out-of-order-inserts
```suggestion
slug: newsletter-release-out-of-order-ingestion-capacity-planning
```

2023-01-12 13:44 UTC, amyshwang approved these changes

2023-01-12 13:51 UTC, merged