feat(docs): time-series blog post
questdb/questdb.io pull request #1307
Opened 2023-01-16 10:38 UTC by amyshwang

1. Deleting the old content
2. Adding new file with the URL time-series-data based on the draft
3. Updating content
4. Adding links to demo and descriptions to additional reading links

2023-01-16 14:07 UTC, bluestreak01 requested changes

2023-01-16 14:07 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +[QuestDB 6.0](/blog/2021/05/10/questdb-release-6-0-tsbs-benchmark/) to support
bad link description, e.g. "QuestDB 6.0" leads to article titled "How we achieved write speeds of 1.4 million rows per second". Perhaps paragraph needs to be rephrased to set user expectations for the link

2023-01-16 14:07 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +  [`ASOF`](/docs/reference/sql/join#asof-join) joins. Below, the two tables,
we need better link description here, perhaps "There are known as ASOF joins, we have [example of asof join](/docs/reference/sql/join/#asof-join) in our documentation

2023-01-16 14:10 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +  [`IN`](/docs/reference/sql/where/#time-range) for timestamp search is fast and
Paragraph need to be re-phrased to ensure link is descriptive

2023-01-16 14:10 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +  [`WHERE`](/docs/reference/sql/where#symbol-and-string) and
same for `where` - link description is too short

2023-01-16 14:14 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +  keyword [`SAMPLE BY`](/docs/reference/sql/sample-by#examples). This SQL
`SAMPLE BY` link description is too short

2023-01-16 14:15 UTC, bluestreak01 commented on blog/2023-01-18-time-series-data.mdx
> +  [partitioned by time](/docs/concept/partitions/) (hourly, daily, weekly or
link description is too short

2023-01-16 14:38 UTC, argshook commented on blog/2023-01-18-time-series-data.mdx
> +slig: time-series-data
```suggestion
slug: time-series-data
```

2023-01-16 14:38 UTC, argshook commented on blog/2023-01-18-time-series-data.mdx
> +  alt="Example of time-series data use cases"
```suggestion
  alt="Table showing time series data use cases by segment"
```

Same suggestion as from Vlad, just in a `suggestion` format for easy committing

2023-01-17 12:09 UTC, argshook requested changes

2023-01-17 12:09 UTC, argshook commented on netlify.toml
> +  from = "/blog/2020-11-26-why-timeseries-data/"
```suggestion
  from = "/blog/2020/11/26/why-timeseries-data/"
```

The date part is separated by forward slash. You can confirm this by checking other rules in this file that redirect blog post pages or other blog posts, like, for example [this one](https://deploy-preview-1307--unruffled-blackwell-31bfb2.netlify.app/blog/2023/01/03/change-data-capture-with-questdb-and-debezium) (notice how URL is separated with forward slash for date part)

2023-01-17 14:30 UTC, argshook approved these changes

2023-01-17 14:58 UTC, merged