feat(docs): add first explain blog post
questdb/questdb.io pull request #1325
Opened 2023-01-19 17:43 UTC by bziobrowski

2023-01-20 09:40 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +
Could we not copy from the Docs as things might change. Maybe rephrase this?

2023-01-20 09:47 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +[now() function](https://questdb.io/docs/reference/function/date-time/#now):
```suggestion
it over the former one. To understand the difference, we need to understand the `sysdatetime()` function: `sysdatetime()` changes within the query execution timeframe.
```

I am guess from the context that the first query uses sysdatetime() which is costly. The function now() is not really mentioned above so using it could be confusing...

2023-01-20 10:07 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +[now() function](https://questdb.io/docs/reference/function/date-time/#now):
I agree . Maybe it'd be better to add the warning to systimestamp() and sysdate() functions and then use excerpt from the former here ?

2023-01-23 09:14 UTC, amyshwang requested changes

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +For hot data response times are consistent:
I think this is just for my own understanding: why these are consistent? Query A tends to take longer than B in a consistent way?

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +EXPLAIN SELECT count(*) FROM trades WHERE price = 0.0f;
Query A is not 0.0f but 2.1f, does this matter?
```suggestion
EXPLAIN SELECT count(*) FROM trades WHERE price = 2.1f;
```

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +EXPLAIN SELECT count(*) FROM trades WHERE price = 0.0;
Again if we refer to query B why is it 0.0 here?
```suggestion
EXPLAIN SELECT count(*) FROM trades WHERE price = 2.1;
```

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +[Just-In-Time-compiled](/blog/2022/01/12/jit-sql-compiler/) filter!
```suggestion
[Just-In-Time-compiled](/docs/concept/jit-compiler/) filter!
```
I think using Doc is better than a blog post?

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +Let's inspect the plan:
Should we add the explain query here?

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +which scans the whole table (3).
the ref for (3) is unclear to me because you did not mention DataFrame...

2023-01-23 09:14 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +In effect, the response time shrinks to 3ms, about 400 times.
400 times less?

2023-01-23 10:04 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +Let's inspect the plan:
It'd simply repeat the query above with explain prefix, so a bit verbose and not really offer much considering that there's a number of exaplain examples earlier  .  What do you think ?

2023-01-23 10:18 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +For hot data response times are consistent:
Removed the word.  I meant to say that times a 'stable' .

2023-01-23 10:18 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +EXPLAIN SELECT count(*) FROM trades WHERE price = 0.0f;
Fixed.

2023-01-23 10:18 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +EXPLAIN SELECT count(*) FROM trades WHERE price = 0.0;
Fixed.

2023-01-23 10:21 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +which scans the whole table (3).
I added (3) to both subnodes of DataFrame .

2023-01-23 10:21 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +In effect, the response time shrinks to 3ms, about 400 times.
Fixed.

2023-01-23 10:22 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +[Just-In-Time-compiled](/blog/2022/01/12/jit-sql-compiler/) filter!
Quality-wise blog post is better but doc does refer to it so I think it's fine and applied your suggestion .

2023-01-24 08:44 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +these [concepts](https://questdb.io/docs/concept/storage-model/#read-model) is
I am linking it to docs/introduction/concepts/!

2023-01-24 08:53 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +which scans the whole table (3).
```suggestion
The query counts (1) records filtered by an asynchronous, multi-threaded filter (2),
which scans the whole table (3).
```

So now I understand what the numbers are referring to. The current sentence does not convert a sequence. It describes a nesting relationship, but I wonder if the number corresponds to the sequence of the operation? Does it mean that it follows the following steps:
1. record count
2. apply filter
3. scan table

I don't think so and I think the steps are in reverse. Should we use a number list to describe the steps and number the them differently? As:
1. A full table scan is triggered.
2. An asynchronous, multi-threaded filter is applied to the record.
3. Filtered records are counted.
And we number the plan accordingly too...

Maybe I get it al wrong...

2023-01-24 10:40 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> +which scans the whole table (3).
These numbers were meant to point to pieces of execution plan, not show the sequence of operation .
You're right about the actual steps.

2023-01-25 13:01 UTC, bziobrowski commented on blog/2023-01-26-introducing-explain.mdx
> -that the index on `id` wasn't used.
v.s. -> vs. ?

2023-01-25 13:10 UTC, amyshwang commented on blog/2023-01-26-introducing-explain.mdx
> +Considering the number of records (678 rows in the result v.s. 120M in the whole
```suggestion
Considering the number of records (678 rows in the result vs 120M in the whole
```

2023-01-25 16:22 UTC, bluestreak01 submitted a review, later dismissed

2023-01-25 16:22 UTC, bluestreak01 commented on blog/2023-01-26-introducing-explain.mdx
> +The [EXPLAIN](https://questdb.io/docs/reference/sql/explain) SQL keyword shows
```suggestion
The [EXPLAIN](https://questdb.io/docs/reference/sql/explain/) SQL keyword shows
```

2023-01-25 20:05 UTC, amyshwang approved these changes

2023-01-26 07:01 UTC, merged