feat(docs) adding CREATE TABLE IN VOLUME docs
questdb/questdb.io pull request #1341
Opened 2023-01-25 06:56 UTC by amyshwang

Documentation for https://github.com/questdb/questdb/pull/2931

2023-01-25 07:00 UTC, amyshwang commented on docs/reference/sql/create-table.md
> +  ```
I think this is also okay, based on the code PR:

```suggestion
  ```questdb-sql
  CREATE TABLE my_table (i symbol, ts timestamp) IN VOLUME 'SECONDARY_VOLUME';
  ```
```
However, I think it is a bit over-complicated so I am not adding this to the syntax diagram. Could we leave it out from the docs?

2023-01-25 09:06 UTC, marregui commented on docs/reference/sql/create-table.md
> +  ```
ofcourse, I do not think i adds much in the diagrams. The gist of this is that if you define a volume:

```
other volume -> /absolute/path/to/other/volume
```

then you can:

```
CREATE TABLE my_table ( ... ) ... IN VOLUME 'other volume';
CREATE TABLE my_table ( ... ) ... IN VOLUME 'other voluMe';
...
```

If alias was just `othervolume`, or `other_volume`, then this would be possible:

```
CREATE TABLE my_table ( ... ) ... IN VOLUME other_volume;
CREATE TABLE my_table ( ... ) ... IN VOLUME othervolume;
...
```

I expect users to define aliases that make sense for them, omitting quotes is just nice (I forgot them all the time while testing).

2023-01-25 11:06 UTC, marregui submitted a review, later dismissed
LGTM

2023-01-25 16:11 UTC, bluestreak01 requested changes

2023-01-25 16:11 UTC, bluestreak01 commented on docs/reference/sql/drop.md
> +[backups](/docs/reference/sql/backup) of your data.
trailing slash missing

2023-01-25 16:12 UTC, bluestreak01 commented on docs/reference/sql/drop.md
> +[backups](/docs/reference/sql/backup) of your data.
```suggestion
[backups](/docs/reference/sql/backup/) of your data.
```

2023-01-25 16:13 UTC, bluestreak01 submitted a review, later dismissed
missing trailing slash

2023-01-25 20:13 UTC, amyshwang commented on docs/reference/sql/create-table.md
> +  ```
Ah in this case they are used in a specific situation so I'd add the option to the diagram.

2023-01-27 07:01 UTC, amyshwang commented on docs/reference/sql/create-table.md
> +  ```
Diagram and text updated!

2023-01-30 09:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1341) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1341) before we can accept your contribution.<br/>**3** out of **4** committers have signed the CLA.<br/><br/>:white_check_mark: amyshwang<br/>:white_check_mark: marregui<br/>:white_check_mark: insmac<br/>:x: dependabot[bot]<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1341) it.</sub>

2023-01-30 10:04 UTC, marregui approved these changes
I have added a few missing slashes in the md docs affected by this review, as my understanding is it helps.

2023-02-09 12:01 UTC, glasstiger approved these changes

2023-02-09 23:45 UTC, merged