chore(blog) update time-series blog post for SEO
questdb/questdb.io pull request #1365
Opened 2023-02-02 04:44 UTC by amyshwang

- Remove the second half of the article
- Update tags
- Rename one image file --> I don't want to make it too complicated as this can handicape writing process
- Remove a coupld of hylerlinks as too many links could hurt SEO

2023-02-02 11:10 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +    startup,
i would remove startup

2023-02-02 11:10 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +    entrepreneurship,
remove entrepreneurship

2023-02-02 11:17 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
Change intro paragraph to:

This blog post covers the basics of time-series data and its most common use cases 
and applications. We introduce time-series database category, which 
have seen an explosion in popularity since a decade ago. 
Additionally, we will cover the design and trade-off for a time-series database and
show how SQL can deal with time-series data workloads, using QuestDB SQL syntax as 
an example.

2023-02-02 11:18 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +    story,
remove story

2023-02-02 12:13 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +description: An article on time-series data and time-series databases (TSDB)
I also rewrite the following titles:

Time-series databases design > The design of a time-series database
Time-series databases' most important features and trade-offs > Most important features and trade-offs for a time-series database

Finally, I would delete the "Time series data and characteristics of TSDBs#"
 paragraph entirely because it is redundant.

2023-02-03 10:19 UTC, argshook requested changes

2023-02-03 10:19 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
> +    startup,
```suggestion
```

2023-02-03 10:19 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
> +    entrepreneurship,
```suggestion
```

2023-02-03 10:19 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
> +    story,
```suggestion
```

2023-02-03 10:25 UTC, argshook submitted a review, later dismissed

2023-02-03 10:37 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +cases and applications. We introduce time-series database category, which have
We introduce time-series database category, which have > We introduce the time-series database category, which has

2023-02-03 10:40 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
> +syntax as an example.
using QuestDB SQL syntax as an example. > using QuestDB's ANSI SQL syntax as an example.

2023-02-03 10:41 UTC, tris0laris commented on blog/2023-01-17-time-series-data.mdx
>  Time series is a succession of data points ordered by time. Time-series data is
Time series is a succession of data points ordered by time. > Time-series is a succession of data points ordered by time

2023-02-03 10:49 UTC, argshook requested changes

2023-02-03 10:49 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
> +cases and applications. We introduce time-series database category, which have
```suggestion
cases and applications. We introduce the time-series database category, which has
```

2023-02-03 10:49 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
> +syntax as an example.
```suggestion
and show how SQL can deal with time-series data workloads, using QuestDB's ANSI SQL syntax as an example.
```

2023-02-03 10:49 UTC, argshook commented on blog/2023-01-17-time-series-data.mdx
>  Time series is a succession of data points ordered by time. Time-series data is
```suggestion
Time-series is a succession of data points ordered by time. Time-series data is
```

2023-02-03 10:53 UTC, argshook approved these changes

2023-02-03 11:31 UTC, argshook approved these changes

2023-02-03 13:02 UTC, tris0laris approved these changes

2023-02-03 13:02 UTC, merged