feat(doc) blog: data integration strategies
questdb/questdb.io pull request #1366
Opened 2023-02-02 06:15 UTC by amyshwang

- Used SEO tools to check the content
- Added background to images
- TODO check image preview once GH preview is completed

2023-02-02 08:48 UTC, jerrinot commented on blog/2023-02-06-data-integration-strategies-for-tsdb.mdx
> +Given the need for real-time insights for time series data, most modern
> most modern event-driven architectures now implement data streaming with CDC.
I am not sure if there are data to back this claim up. I'd either change the word _most_ to _many_ or omit it completely. Or keep it to sparkle discussion; that's OK as long as it's a conscious decision.

2023-02-02 16:38 UTC, jerrinot submitted a review, later dismissed

2023-02-02 18:34 UTC, bluestreak01 requested changes

2023-02-02 18:34 UTC, bluestreak01 commented on blog/2023-02-06-data-integration-strategies-for-tsdb.mdx
> +[Change Data Capture with QuestDB and Debezium](/blog/2023/01/03/change-data-capture-with-questdb-and-debezium).
guys, can we pls ensure trailing slashes on our own links?

2023-02-02 18:39 UTC, bluestreak01 commented on blog/2023-02-06-data-integration-strategies-for-tsdb.mdx
> +  alt="Overview of the CDC model"
pretend you cannot see and screen reader pronounces "alt" for you. How satisfied are you on scale 1 to 10 ? :)

`alt` could say
```
Three cylinders showing data flow. Cylinders are connected by errors showing flow from left to right. First cylinder is labelled 'data source', second - 'cdc' and third - 'target system' 
```

2023-02-07 09:34 UTC, jerrinot approved these changes

2023-02-07 10:24 UTC, merged