blog: uuid
questdb/questdb.io pull request #1377
Opened 2023-02-06 14:04 UTC by jerrinot

2023-02-08 06:00 UTC, amyshwang requested changes
I have changed the content directly so these are things I am not sure about.
As it is we have a good balance of text and hyperlinks, decent keywords used :)

2023-02-08 06:00 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +title: "UUID: Coordination-free unique keys"
I'd use book title case for first level title. And maybe this:

```suggestion
title: "UUID: Coordination-Free Unique Keys and Why They are Useful"
```

2023-02-08 06:00 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +without any coordination at all. This is what we call coordination-free unique
This makes me ask the question: Are all the UUID coordination free? The name 'UUID' does not really convey this piece of information. We could perhaps make this point clearer (either we are only focusing on the UUID that are coordination-free or all UUID are coordination free).

2023-02-08 06:00 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +Version 7 uses clock and random bits as inputs. Unlike versions 1, 2, or 6, it
I am not sure what clock means. Clock time?

Maybe (I googled it)

```suggestion
Version 7 uses a 48-bit timestamp and random data. Unlike versions 1, 2, or 6, it
```

2023-02-08 06:00 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +UUIDs are popular as synthetic IDs because they can be generated without any
```suggestion
UUIDs are popular synthetic IDs because they can be generated without any
```

But I am not sure if the meaning may be changed...

2023-02-08 10:08 UTC, jerrinot commented on blog/2023-02-10-uuid.mdx
> +without any coordination at all. This is what we call coordination-free unique
I *think* all UUIDs can be considered coordination-free. 

Technically, the versions with a MAC address or wall-clock are not entirely coordination free: As MAC address assignment is coordinated, and so is time-tracking. but that's would be just nit-picking; I think they are coordination-free for practical purposes.

2023-02-08 10:09 UTC, jerrinot commented on blog/2023-02-10-uuid.mdx
> +UUIDs are popular as synthetic IDs because they can be generated without any
no, the meaning is still the same, thanks!

2023-02-09 02:58 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +time and save storage space.
We discuss the need for an intro. This is only useful on the blog landing page.
This is a separate task relating to the layout of blog posts. I'd still keep some wording here for now as this is consistent and required to have the landing page function.

2023-02-09 05:18 UTC, amyshwang reviewed
One minor comment when running the demo myself. Otherwise all good.

2023-02-09 05:18 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +INSERT INTO tab_s SELECT rnd_uuid4() FROM long_sequence(1000000000);
Does this work for you? I got timeout:

timeout, query aborted [fd=142]

Inserting less worked for me:
```suggestion
INSERT INTO tab_s SELECT rnd_uuid4() FROM long_sequence(100000000);
```

2023-02-09 09:07 UTC, jerrinot commented on blog/2023-02-10-uuid.mdx
> +INSERT INTO tab_s SELECT rnd_uuid4() FROM long_sequence(1000000000);
hm, you might need to increase the query timeout. let me add a note about it.

2023-02-09 09:07 UTC, jerrinot commented on blog/2023-02-10-uuid.mdx
> +time and save storage space.
agree

2023-02-09 09:37 UTC, jerrinot commented on blog/2023-02-10-uuid.mdx
> +INSERT INTO tab_s SELECT rnd_uuid4() FROM long_sequence(1000000000);
I pushed an update, let me know what you think.

2023-02-10 03:55 UTC, amyshwang submitted a review, later dismissed

2023-02-10 05:05 UTC, amyshwang commented on blog/2023-02-10-uuid.mdx
> +your QuestDB instance can help reduce query time and save storage space.
```suggestion
Learn more about the universally unique identifier (UUID) and how using UUID in
your QuestDB instance can help reduce query time as well as save storage space.
```

2023-02-10 05:23 UTC, amyshwang approved these changes

2023-02-10 05:23 UTC, merged