blog: adding New Stack post
questdb/questdb.io pull request #138
Opened 2020-09-24 16:45 UTC by TheTanc

2020-09-24 17:04 UTC, NicQuestDB reviewed
Reflexions >> Thoughts

Tag's: is it important for SEO? If so, lets do something else than moore's law ?

2020-09-25 09:05 UTC, mpsq requested changes
minor tweaks

2020-09-25 09:05 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +# Time Series Data Is Explosive
```suggestion
## Time series data is explosive
```

2020-09-25 09:05 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +# The End of Moore’s Law Is in Sight
```suggestion
## The end of Moore’s law is in sight
```

2020-09-25 09:05 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +# It Reduces Your Cloud Bills
```suggestion
## It reduces your cloud bills
```

2020-09-28 10:44 UTC, mpsq requested changes

2020-09-28 10:44 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +  Reflexions on why speed and performance are crucial to time-series databases ingestion and analysis.
```suggestion
  Thoughts on why speed and performance are crucial to time-series databases ingestion and analysis.
```

2020-09-28 10:44 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +Reflexions on why speed and performance are crucial to time-series databases ingestion and analysis, originally posted in [The New Stack](https://thenewstack.io/why-performance-matters-in-time-series
```suggestion
Thoughts on why speed and performance are crucial to time-series databases ingestion and analysis, originally posted in [The New Stack](https://thenewstack.io/why-performance-matters-in-time-series-data/).
```

2020-09-28 10:45 UTC, mpsq approved these changes

2020-09-28 10:48 UTC, merged