Add questdb.exe install to binaries.md
questdb/questdb.io pull request #1414
Opened 2023-02-22 11:04 UTC by erjenkins29

Just now trying to "hello world" questdb, needed to run the `install` command first before getting the start command to work.  Should help the next person trying to get it to run in windows for the first time.  I can't speak for the linux case, but I assume it is a similar process.

2023-02-22 15:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1414) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1414) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: amyshwang<br/>:x: erjenkins29<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1414) it.</sub>

2023-02-22 15:55 UTC, amyshwang requested changes
Welcome to QuestDB and thank you for your contribution. Please ensure that the Contributor License Agreement is signed!

I have made a small suggestion. Hope it makes sense!

2023-02-22 15:55 UTC, amyshwang commented on docs/get-started/binaries.md
>  questdb.exe start
Maybe be specific about the mode used:
```suggestion
-- To run the instance as a windows service (preferably as a privileged account):
questdb.exe install
questdb.exe start

-- To run a one-off instance in the current work directory:

questdb.exe
```

2023-03-08 09:48 UTC, amyshwang commented
@erjenkins29 Hello! I was wondering if you could sign the Contributor License Agreement and we can proceed to merge this? Thanks!

2023-03-11 09:00 UTC, erjenkins29 commented
Hi @amyshwang -- apologies for the delay.  just signed this.  Thanks for the hard work, big fan of the project here.

2023-03-13 10:49 UTC, amyshwang approved these changes

2023-03-13 12:25 UTC, insmac approved these changes

2023-03-17 15:48 UTC, merged