blog: maven troubleshooting story
questdb/questdb.io pull request #1424
Opened 2023-02-27 13:44 UTC by jerrinot

2023-02-27 13:45 UTC, jerrinot commented
I was unsure whether using the xkcd comic was OK legal-wise, but it looks it is: https://xkcd.com/license.html
> [...] I'm also okay with people reprinting occasional comics (with clear attribution) in publications like books, blogs, newsletters, and presentations. If you're not sure whether your use is noncommercial, feel free to [email me](mailto:licensing@xkcd.com) and ask (if you're not sure, it's probably okay).

2023-02-27 14:47 UTC, amyshwang requested changes
Made some small suggestions.
There are too many hyperlinks - I removed the one for QuestDB for this post. I can see the reason to add all the others but if we could have another look to ensure that we cannot sacrifice any then it is okay.

2023-02-27 14:47 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +![A screenshot from Slack where I say: the Maven connection reset issues should be fixed for all new PR builds. Let me know if you experience it again.](/img/blog/2023-02-28/slack1.png)
Looking at the screenshot, could we get one without:
![image](https://user-images.githubusercontent.com/107401731/221588631-7eb1cf54-40f9-4a39-ab0c-cd2d597922bf.png)

2023-02-27 14:47 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +results. There was only one answer: **WE NEED MOAR LOGS!** Running Maven with
I was not sure if this is a wordplay that I don't understand:

```suggestion
results. There was only one answer: **WE NEED MORE LOGS!** Running Maven with
```

2023-02-27 14:47 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +`-Dmaven.wagon.httpconnectionManager.ttlSeconds=30`
"Even my fist fix attempt [...]"
I don't understand this. The first attempt has done something to Wagon so you expected to see something about it?

2023-02-27 14:50 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +![A screenshot from Slack where I say: the Maven connection reset issues should be fixed for all new PR builds. Let me know if you experience it again.](/img/blog/2023-02-28/slack1.png)
good catch!

2023-02-27 14:53 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +results. There was only one answer: **WE NEED MOAR LOGS!** Running Maven with
Yeah, this is intentional. I was trying to be funny. Maybe I come across as childish instead. https://www.dictionary.com/e/slang/moar/
So up to you, dear editor :)

2023-02-27 14:54 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +`-Dmaven.wagon.httpconnectionManager.ttlSeconds=30`
I wanted to say this: The first (unsuccessful) fix attempt was poking a Wagon-related property too.

2023-02-27 15:11 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +`-Dmaven.wagon.httpconnectionManager.ttlSeconds=30`
but this would make it clearer?
> Even my previous fix attempt...

wdyt?

2023-02-27 15:15 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +`-Dmaven.wagon.httpconnectionManager.ttlSeconds=30`
Actually ignore me I read it from the source and automatically skip the anchor text for some reason...

2023-02-27 15:16 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +results. There was only one answer: **WE NEED MOAR LOGS!** Running Maven with
Ha let's keep it.

2023-02-27 15:38 UTC, amyshwang approved these changes

2023-02-28 10:50 UTC, amyshwang requested changes
I made most suggestions commit-ready.

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +evil comes from spuriously failing builds. Nothing steals my confidence in a
Since we added CI/CD as a keyword, could we add it to the intro:

```suggestion
evil comes from spuriously failing CI/CD builds. Nothing steals my confidence in a
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +the infrastructure we all use and take for granted.
```suggestion
This is a story about unstable builds and troubleshooting. More
importantly, this story is written to thank all contributors to basic software infrastructure -
the infrastructure we all use and take for granted.
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +></Banner>
preview not picking the latest image

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +all similar to this:
```suggestion
was the culprit, causing non-deterministic outcomes. Therefore, I was surprised
to discover the actual reasons for the recent build failures. They were
all similar to this:
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +TTL to 30s, announced it in company Slack and felt good about myself :)
```suggestion
TTL to 30s, announced it in company Slack, and felt good about myself :)
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +So it was suspicious I could not see anything Wagon-related in the exception
```suggestion
So it was suspicious that I could not see anything Wagon-related in the exception
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +The new
This is a dangling phrase?

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +projects is impossible. Maven is a basic software infrastructure we all take for
```suggestion
ubiquitous that it is impossible to find a Java developer who has never used it. Maven is a basic software infrastructure we all take for
```

2023-02-28 10:50 UTC, amyshwang commented on blog/2023-02-28-maven-troubleshooting.mdx
> +bug. I [opened a ticket](https://issues.apache.org/jira/browse/MNG-7708) and wanted to
```suggestion
Volunteers maintain it. I felt the least I could do was report my experience to
the Maven team so they could clarify whether it was an intentional behavior or a
bug. I [opened a ticket](https://issues.apache.org/jira/browse/MNG-7708) and wanted to
```

2023-02-28 12:29 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +evil comes from spuriously failing builds. Nothing steals my confidence in a
nah, this would feel very forced in this context. it can be any build. even a manually triggered build.

2023-02-28 12:33 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +The same evening I saw one of the Maven maintainers created a
Grammarly kept suggesting the exact change. I thought it was nonsense. 
And now it's both you and Grammarly against me -> I should study English! :)))

2023-02-28 13:25 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +The new
good one!

2023-02-28 13:30 UTC, jerrinot commented on blog/2023-02-28-maven-troubleshooting.mdx
> +></Banner>
what do you mean?

2023-03-01 12:10 UTC, jerrinot commented on blog/2023-03-01-maven-troubleshooting.mdx
> +uses the Apache HTTP Client internally, and it configures the client with a
a good change!

2023-03-01 12:11 UTC, amyshwang approved these changes

2023-03-01 12:12 UTC, amyshwang commented on blog/2023-03-01-maven-troubleshooting.mdx
> +=======
:(

2023-03-01 12:14 UTC, amyshwang requested changes

2023-03-01 12:14 UTC, amyshwang commented on blog/2023-03-01-maven-troubleshooting.mdx
> +There was still one question left unanswered: Why did we started getting this
```suggestion
There was still one question left unanswered: Why did we start getting this
```

2023-03-01 12:35 UTC, amyshwang approved these changes

2023-03-01 12:36 UTC, merged