feat(docs): document SHOW PARTITIONS FROM table
questdb/questdb.io pull request #1473
Opened 2023-03-20 18:43 UTC by marregui

documentation for PR https://github.com/questdb/questdb/pull/3060

2023-03-21 16:59 UTC, amyshwang commented on docs/reference/function/meta.md
> +  [attached via soft link](/docs/reference/sql/alter-table-attach-partition/#symbolic-links) (unless it is detached)
(unless it is detached): I don't understand this. Is it going to be true is a partition is detached too?

2023-03-21 16:59 UTC, amyshwang commented on docs/reference/function/meta.md
> +SELECT * FROM table_partitions('my_table') WHERE active = true
I think this returns nothing as no partition is active?
Should we indicate the output (NULL?) or text explaining that nothing will be returned? What is the actual behaviour?

2023-03-27 15:53 UTC, marregui commented on docs/reference/function/meta.md
> +  [attached via soft link](/docs/reference/sql/alter-table-attach-partition/#symbolic-links) (unless it is detached)
indeed, that is debris, apologies, removed, made no sense.

2023-03-27 15:54 UTC, marregui commented on docs/reference/function/meta.md
> +SELECT * FROM table_partitions('my_table') WHERE active = true
mistake, I have amended the example to show the correct answer.

2023-03-29 13:24 UTC, amyshwang requested changes
Are all the queries in `SHOW` not supporting filters? I think we should add a note if this is the case.

2023-03-29 13:24 UTC, amyshwang commented on docs/reference/function/meta.md
> +The quick syntax `SHOW PARTITIONS FROM my_table` does not support filters.
Add link and move this to an earlier section

2023-03-29 13:24 UTC, amyshwang commented on docs/reference/function/meta.md
> +The quick syntax `SHOW PARTITIONS FROM my_table` does not support filters.
```suggestion
The SQL keyword [`SHOW PARTITIONS`](/docs/reference/sql/show/#show-partitions) does not support filters.
```

2023-03-29 13:30 UTC, amyshwang commented on docs/reference/function/meta.md
> +SELECT column, type, designated FROM table_columns('my_table') WHERE designated
Git blame shows this update - https://github.com/questdb/questdb.io/commit/56878f38111cc1777e0d920f95a824c1d2074003

I guess it should be:

```
SELECT column, type, designated FROM table_columns('my_table') WHERE designated = 'true';
```
Is it correct?

2023-04-02 09:20 UTC, amyshwang commented on docs/reference/function/meta.md
> +SELECT column, type, designated FROM table_columns('my_table') WHERE designated = true
Missing ;

2023-04-02 09:20 UTC, amyshwang commented on docs/reference/function/meta.md
> +SELECT column, type, designated FROM table_columns('my_table') WHERE designated = true
```suggestion
SELECT column, type, designated FROM table_columns('my_table') WHERE designated = true;
```

2023-04-02 10:30 UTC, amyshwang approved these changes

2023-04-06 01:36 UTC, merged