Aw/refresh jupyter notebook post
questdb/questdb.io pull request #1479
Opened 2023-03-23 16:33 UTC by amyshwang

TODO:
- Come up with a better title and update URL too
- Update content
- Run the steps to ensure that it still works

2023-03-29 13:46 UTC, amunra requested changes
Minor clean-up needed.

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +  pip3 install requests matplotlib pandas
Urllib is an old dependency: It's no longer needed.
Running `pip3 install requests matplotlib pandas` should indeed be enough.

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +  pip3 install requests matplotlib pandas
What do you mean by "I still need to run pip3 install for each library installation when running the code..."

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +Python 3.x `jupytper --path` will let you know if Jupyter is using 2.7 or 3.x
Tpyo: `jupyter` not `jupytper`.

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
>  - make sure you are running Python 3.x and not Python 2.7. If you're in doubt,
I think it's fair to remove Python 2.7 references now. Here and later in the blog post.

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +    ' balance_ccy sym,'\
Try it.. I thought it needs to be `symbol`, not `sym`. Is there an extra alias that I was unaware of?

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +currency = ["USD", "EUR", "GBP", "JPY"]
I think it is a bit more realistic to use the currency ISO code, yes.

2023-03-29 13:46 UTC, amunra commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +rawData = pd.read_csv(io.StringIO(queryData.decode('utf-8')), parse_dates=['timestamp'])
You'd need to re-run it, but I'm pretty sure that you can drop the `io.StringIO` bit. I.e.:

```python
rawData = pd.read_csv(queryData.decode('utf-8'), parse_dates=['timestamp'])
```

2023-04-04 08:37 UTC, amyshwang commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +    ' balance_ccy sym,'\
Yes I changed the code I was running but not here...

2023-04-04 08:37 UTC, amyshwang commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +rawData = pd.read_csv(io.StringIO(queryData.decode('utf-8')), parse_dates=['timestamp'])
I tried to tweak it too but failed. Using your code I got a complicated looking error:
```
FileNotFoundError                         Traceback (most recent call last)
Cell In[9], line 13
     11 r = requests.get("http://localhost:9000/exp?query=" + query)
     12 queryData = r.content
---> 13 rawData = pd.read_csv(queryData.decode('utf-8'), parse_dates=['timestamp'])
     14 print(rawData)

File /opt/homebrew/lib/python3.10/site-packages/pandas/util/_decorators.py:211, in deprecate_kwarg.<locals>._deprecate_kwarg.<locals>.wrapper(*args, **kwargs)
    209     else:
    210         kwargs[new_arg_name] = new_arg_value
--> 211 return func(*args, **kwargs)

File /opt/homebrew/lib/python3.10/site-packages/pandas/util/_decorators.py:331, in deprecate_nonkeyword_arguments.<locals>.decorate.<locals>.wrapper(*args, **kwargs)
    325 if len(args) > num_allow_args:
    326     warnings.warn(
    327         msg.format(arguments=_format_argument_list(allow_args)),
    328         FutureWarning,
    329         stacklevel=find_stack_level(),
    330     )
--> 331 return func(*args, **kwargs)

File /opt/homebrew/lib/python3.10/site-packages/pandas/io/parsers/readers.py:950, in read_csv(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, encoding_errors, dialect, error_bad_lines, warn_bad_lines, on_bad_lines, delim_whitespace, low_memory, memory_map, float_precision, storage_options)
    935 kwds_defaults = _refine_defaults_read(
    936     dialect,
    937     delimiter,
   (...)
    946     defaults={"delimiter": ","},
    947 )
    948 kwds.update(kwds_defaults)
--> 950 return _read(filepath_or_buffer, kwds)

File /opt/homebrew/lib/python3.10/site-packages/pandas/io/parsers/readers.py:605, in _read(filepath_or_buffer, kwds)
    602 _validate_names(kwds.get("names", None))
    604 # Create the parser.
--> 605 parser = TextFileReader(filepath_or_buffer, **kwds)
    607 if chunksize or iterator:
    608     return parser

File /opt/homebrew/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1442, in TextFileReader.__init__(self, f, engine, **kwds)
   1439     self.options["has_index_names"] = kwds["has_index_names"]
   1441 self.handles: IOHandles | None = None
-> 1442 self._engine = self._make_engine(f, self.engine)

File /opt/homebrew/lib/python3.10/site-packages/pandas/io/parsers/readers.py:1735, in TextFileReader._make_engine(self, f, engine)
   1733     if "b" not in mode:
   1734         mode += "b"
-> 1735 self.handles = get_handle(
   1736     f,
   1737     mode,
   1738     encoding=self.options.get("encoding", None),
   1739     compression=self.options.get("compression", None),
   1740     memory_map=self.options.get("memory_map", False),
   1741     is_text=is_text,
   1742     errors=self.options.get("encoding_errors", "strict"),
   1743     storage_options=self.options.get("storage_options", None),
   1744 )
   1745 assert self.handles is not None
   1746 f = self.handles.handle

File /opt/homebrew/lib/python3.10/site-packages/pandas/io/common.py:856, in get_handle(path_or_buf, mode, encoding, compression, memory_map, is_text, errors, storage_options)
    851 elif isinstance(handle, str):
    852     # Check whether the filename is to be opened in binary mode.
    853     # Binary mode does not support 'encoding' and 'newline'.
    854     if ioargs.encoding and "b" not in ioargs.mode:
    855         # Encoding
--> 856         handle = open(
    857             handle,
    858             ioargs.mode,
    859             encoding=ioargs.encoding,
    860             errors=errors,
    861             newline="",
    862         )
    863     else:
    864         # Binary mode
    865         handle = open(handle, ioargs.mode)

FileNotFoundError: [Errno 2] No such file or directory: '"cust_id","balance","balance_ccy","inactive","timestamp"\r\n21,146.77,"JPY",false,"2023-04-04T08:33:37.308450Z"\r\n21,49.33,"GBP",true,"2023-04-04T08:33:37.717813Z"\r\n21,69.73,"GBP",false,"2023-04-04T08:33:37.972450Z"\r\n'
```

2023-04-14 12:36 UTC, javier requested changes
There are several issues that need addressing. Please see comments

2023-04-14 12:36 UTC, javier commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +    " and balance_ccy = 'USD'"\
This code snippet is wrong. Has extra parenthesis and doesn't work in any case because we are doing something weird.

Please replace the whole snippet with this

2023-04-14 12:36 UTC, javier commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +    " and balance_ccy = 'USD'"\
import urllib.parse

q = "select cust_id,"\
    " balance,"\
    " balance_ccy,"\
    " inactive,"\
    " timestamp"\
    " from balances"\
    " where cust_id = 26"\
    " and balance_ccy = 'USD'"\
    " and not inactive"

query = urllib.parse.quote(q)
r = requests.get("http://localhost:9000/exp?query=" + query)
queryData = pd.read_csv(io.StringIO(r.text), parse_dates=['timestamp'])
print(queryData)

2023-04-14 12:36 UTC, javier commented on blog/2020-06-15-python-questdb-tutorial.mdx
> +    " and balance_ccy = 'USD'"\
Also.. the snipped above has a problem. Since we are inserting random data, if might be the case we have ZERO records for customer id 26 with not inactive status, in which case we have no results.

I would rather change the condition to something like where cust_id IN(26,27,28,29,30,31)

2023-04-14 12:36 UTC, javier commented on blog/2020-06-15-python-questdb-tutorial.mdx
>  from matplotlib import pyplot as plt
in the matplotlib cell, we need to use now this code, as we change the snippet above and the variable is not named "rawData" anymore.

from matplotlib import pyplot as plt

queryData.plot("timestamp", ["balance"], subplots=True)

2023-04-17 09:57 UTC, amyshwang commented
As the content is outdated, we have decided to delete this and set up a redirect when new content is ready.

2023-04-17 09:57 UTC, closed without merging