chore(docs) Adding log info as a new page and improve the links in Get started
questdb/questdb.io pull request #1495
Opened 2023-03-28 15:28 UTC by amyshwang

Closes #1489

2023-03-28 17:11 UTC, amyshwang commented
TBD - Debug examples

2023-03-29 13:09 UTC, amyshwang commented on docs/troubleshooting/log.md
> +
I suggest that we delete this. Information should be easier to access from the Cloud UI.
At the moment this is the only Cloud specific docs so I will at least hide it and make it visible when more cloud docs are ready.

2023-03-29 13:10 UTC, amyshwang commented on docs/troubleshooting/log.md
> +
Debug exmple needed

2023-03-29 13:54 UTC, amunra commented on docs/troubleshooting/log.md
> +
Quite the opposite.

I think we should merge both of our OSS and Cloud docs together, at least by a bit.

The rationale here is that it would:
* Improve SEO for the cloud.
* Remind OSS users that the cloud exists and what the features are.
* Hopefully, if we document enough good features, give OSS users a bit of a FOMO and encourage them to sign up.

Maybe I'm wrong here.

What is our documentation strategy for the cloud product supposed to be? We should align with that.

2023-03-31 11:48 UTC, amunra requested changes
Some tweaks needed.

2023-03-31 11:48 UTC, amunra commented on docs/troubleshooting/log.md
> +
```
2023-03-31T11:47:05.723599Z D i.q.c.TableUtils loaded clean txn, version 0, offset=64, size=148, txn=0
2023-03-31T11:47:05.723605Z D i.q.c.ColumnVersionReader read clean version 0, offset 0, size 0
2023-03-31T11:47:05.723620Z D i.q.c.v.MemoryCMRImpl unmapped [pageAddress=139695957975040, size=40, tag=7]
2023-03-31T11:47:05.723623Z D i.q.c.v.MemoryCMRImpl closed [fd=234]
2023-03-31T11:47:05.723628Z D i.q.c.v.MemoryCMRImpl unmapped [pageAddress=139695957979136, size=4096, tag=0]
2023-03-31T11:47:05.723629Z D i.q.c.v.MemoryCMRImpl closed [fd=233]
2023-03-31T11:47:05.723631Z D i.q.c.p.WalWriterPool 'testServerMainCreateWalTableInVolumeTableExists1~23' is assigned [at=0:0, thread=1]
2023-03-31T11:47:05.723715Z D i.q.g.FunctionParser call cast(investmentMill,INT) -> cast(Li)
2023-03-31T11:47:05.723729Z D i.q.g.FunctionParser call rnd_symbol(4,4,4,2) -> rnd_symbol(iiii)
2023-03-31T11:47:05.723749Z D i.q.g.FunctionParser call investmentMill * 950399 -> *(LL)
2023-03-31T11:47:05.723794Z D i.q.g.FunctionParser call cast(1672531200000000L,TIMESTAMP) -> cast(Ln)
2023-03-31T11:47:05.723803Z D i.q.g.FunctionParser call cast(1672531200000000L,TIMESTAMP) + investmentMill * 950399 -> +(NL)
```

2023-04-18 03:18 UTC, amyshwang commented on docs/troubleshooting/log.md
> +
I discussed this with Nic - we're focusing on blog post revamp atm. While I have drafted some Cloud docs plans, we are not implementing them yet. I added information about logs here but I am hiding them for when we're pushing Cloud docs.

2023-04-18 03:18 UTC, amyshwang commented on docs/troubleshooting/log.md
> +the java option `-Debug` or setting the environment variable `QDB_DEBUG=true`.
It's not possible to get it atm. As mentioned in the other comment, we're leaving out Cloud for now.

2023-04-18 09:53 UTC, amunra commented on docs/troubleshooting/log.md
> +
Good, I just wanted to be sure this was a conscious decision to leave cloud stuff out, that's all :-).

2023-04-18 09:54 UTC, amunra approved these changes

2023-04-18 23:22 UTC, merged