chore(blog) update grafana
questdb/questdb.io pull request #1496
Opened 2023-03-29 08:26 UTC by amyshwang

- instructions and screenshot to be updated after the 7.1 release
- Minor editorial changes to update wording and reduce the number of links

2023-04-11 12:13 UTC, javier commented on blog/2020-10-19-grafana-tutorial.mdx
> +title: Build a monitoring dashboard with Grafana and QuestDB
maybe we can change to "Build a time-series monitoring dashboard with Grafana and QuestDB"? Or "Time-series monitoring with Grafana and QuestDB"? Asking as people might want to search for time-series monitoring and grafana but they might not know questdb

2023-04-11 12:13 UTC, javier commented on blog/2020-10-19-grafana-tutorial.mdx
> +slug: build-monitoring-dashboard-grafana-questdb
if we change the title, change the slug accordingly to include time-series

2023-04-11 15:16 UTC, javier commented on blog/2020-10-19-grafana-tutorial.mdx
> +the Grafana conatiner, we add the `--add-host` parameter:
typo: container

2023-04-11 15:18 UTC, javier commented on docs/third-party-tools/grafana.md
> +docker run -it --rm --name=grafana -p 3000:3000 grafana/grafana:latest
Should we use grafana/grafana:latest or grafana/grafana-oss:latest ?

2023-04-11 15:32 UTC, javier commented on blog/2020-10-19-grafana-tutorial.mdx
> +Grafana is a data visualization tool consisting of a server that connects to one
If we started this section saying "Grafana is..." I find it weird that we now say it is a different thing

2023-04-11 16:19 UTC, javier requested changes
Left several comments. I believe some can be ignored, but some need addressing

2023-04-12 07:24 UTC, amyshwang commented on blog/2020-10-19-grafana-tutorial.mdx
> +title: Build a monitoring dashboard with Grafana and QuestDB
I think "Time-Series Monitoring Dashboard with Grafana and QuestDB" would benefit from having "monitoring dashboard" keyword so I am using this!

2023-04-12 08:12 UTC, javier commented on blog/2020-10-19-grafana-tutorial.mdx
> +Toggle the query editor by using the builder or code panel. The query editor
Interesting. I see a different thing. You are probably using the grafana docker image, not the grafana-oss docker image. I would recommend using grafana-oss, as it is open source. The other is enterprise. I addressed this on a previous comment. This is what I see on oss

![image](https://user-images.githubusercontent.com/3839/231395097-0edf9f1e-52d8-42fd-86ed-3b055bb08712.png)


If I start with the grafana enterprise version, I see what you see

2023-04-12 08:22 UTC, amyshwang commented on blog/2020-10-19-grafana-tutorial.mdx
> +Toggle the query editor by using the builder or code panel. The query editor
I see! I have updated the screenshot and revert my changes.

2023-04-12 10:09 UTC, javier commented on blog/2023-04-12-grafana-tutorial.mdx
> +To protect against this, we have set a dedicated QuestDB instance **read-only
This is not a dedicated read only mode instance anymore. It is enabling a read only user

2023-04-12 10:19 UTC, javier approved these changes
Looking great!

2023-04-12 10:20 UTC, merged