fix links from screenshots to web console documentation
questdb/questdb.io pull request #1509
Opened 2023-04-01 22:29 UTC by winne42

hope this works :-)

2023-04-01 22:30 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1509) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1509) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1509) it.</sub>

2023-04-03 01:43 UTC, amyshwang requested changes
Thank you for your contribution @winne42! Very minor suggestions added as we're trying to be consistent with using trailing slash for hyperlinks.

2023-04-03 01:43 UTC, amyshwang commented on docs/develop/connect.md
> +<a href="/docs/develop/web-console">
```suggestion
<a href="/docs/develop/web-console/">
```

2023-04-03 01:43 UTC, amyshwang commented on docs/develop/query-data.md
> +<a href="/docs/develop/web-console">
```suggestion
<a href="/docs/develop/web-console/">
```

2023-04-03 04:50 UTC, winne42 commented
> Thank you for your contribution @winne42! Very minor suggestions added as we're trying to be consistent with using trailing slash for hyperlinks.

Allright, thanks!

2023-04-05 06:12 UTC, amyshwang approved these changes
Thank you!

2023-04-05 06:16 UTC, merged