docs(get-started): show correct docker volume path for different platforms
questdb/questdb.io pull request #1513
Opened 2023-04-03 08:18 UTC by argshook

This PR adds tabs to docker run command on `/docs/get-started/docker`
page

2023-04-03 08:26 UTC, amyshwang requested changes
Correcting root dir path

2023-04-03 08:26 UTC, amyshwang commented on docs/get-started/docker.md
> +  { label: "Linux", value: "linux", volumePath: "/var/lib/questdb" },
```suggestion
  { label: "Linux", value: "linux", volumePath: "$HOME/.questdb" },
```

2023-04-03 08:26 UTC, amyshwang commented on docs/get-started/docker.md
> +  { label: "Mac with M1/M2", value: "mac-arm", volumePath: "/var/lib/questdb" },
```suggestion
  { label: "Mac with M1/M2", value: "mac-arm", volumePath: "/opt/homebrew/var/questdb" },
```

2023-04-03 08:26 UTC, amyshwang commented on docs/get-started/docker.md
> +    volumePath: "/opt/homebrew/var/questdb",
```suggestion
    volumePath: "/usr/local/var/questdb",
```

2023-04-03 08:26 UTC, amyshwang commented on docs/get-started/docker.md
> +    volumePath: "\\Windows\\System32\\qdbroot",
This one I am less sure about as your version might be for Docker command?

```suggestion
    volumePath: "\Windows\System32\qdbroot",
```

2023-04-03 08:38 UTC, argshook commented on docs/get-started/docker.md
> +    volumePath: "\\Windows\\System32\\qdbroot",
a backslash is a special escape character used to indicate other special characters such as new lines (\n), tabs (\t), or quotation marks (\\"). In order to display a backslash `\` we must escape itself. That's why i used two: `\\`

2023-04-03 08:41 UTC, argshook commented on docs/get-started/docker.md
> +  { label: "Linux", value: "linux", volumePath: "/var/lib/questdb" },
is this suggestion correct? in other docs (e.g. [here](https://questdb.io/docs/reference/configuration/#docker)) the path suggested is `/var/lib/questdb/`

2023-04-03 22:10 UTC, amyshwang commented on docs/get-started/docker.md
> +  { label: "Linux", value: "linux", volumePath: "/var/lib/questdb" },
Yes - it was used here - https://questdb.io/docs/concept/root-directory-structure/
And I asked @puzpuzpuz to confirm and approve this PR - https://github.com/questdb/questdb.io/pull/1511

2023-04-04 00:34 UTC, amyshwang commented
@argshook Apologies - I realise that the path should remain the same because it's the path running within the container!
I will close the ticket. Sorry for the trouble caused!!

2023-04-04 00:34 UTC, closed without merging

2023-04-04 06:21 UTC, puzpuzpuz commented on docs/get-started/docker.md
> +  { label: "Linux", value: "linux", volumePath: "/var/lib/questdb" },
My bad. I haven't spotted the elephant in the room - Docker. On Docker our root dir is `/var/lib/questdb` (unless it's an old deployment where we were running under `root` - then it's `/root/.questdb`).

@amyshwang my apologies. I'll submit a fix PR.