feat(blog): explain with basic scan types
questdb/questdb.io pull request #1535
Opened 2023-04-11 09:32 UTC by bziobrowski

2023-04-11 09:37 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
@amyshwang I included "backward" version for table scan only because I felt it would be too repetitive . 
Let me know if you think we should include it for all scan types .

2023-04-11 09:42 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
I'm mixing terms here a bit because the common term is "Table scan" or "Full table scan" while explain's output shows "Frame forward scan" . Do you think it's ok as is or should I change it

2023-04-12 06:22 UTC, amyshwang requested changes
I think we need to:
- Contextualise how we are using EXPLAIN to showcase scan types
- Headers may need to be more descriptive in order to tell a story (and using our focused keywords
- Article title is not using solid keywords
- SQL query capitalisation

2023-04-12 06:22 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +What are scan types  ?
"scan type" or "access mode" does not seem to be a mainstream keywords. 
I googled some terms like database scan but it does not convey the same thing. Is there a better term widely used that we could use here?

If not, we could use a cluster of strong keywords to describe the concept in the header.

We need a good level twl header here before jumping into each type.

2023-04-12 06:22 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
I think it is important to be logical so:

- (full) table scan
    - Frame forward scan
    - Frame backward scan

This is very clear.
What we should consider more is to add more descriptive headers because Frame forward/backward scan is QuestDB terms.

2023-04-12 06:22 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +Same as forward scan but runs from last row of last interval to first row of first interval.
This applies elsewhere too - I'd use complete sentences.

2023-04-12 06:22 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +explain select * from trades
Let's use the correct syntax and capitalisation?

2023-04-12 08:12 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
I meant that diagram-wise . Do you think I should add separate diagram for interval backward scan, index backward scan, ... ?

2023-04-12 09:00 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
Maybe a bit of explanation would do ? 
The problem is that our terms don't entirely match the standard ones and EXPAIN's output is custom . 
Normally "Full table scan" is done from start to end of table because data is not ordered and direction doesn't matter . Qdb tables that have designated timestamp are ordered by it so direction matters a lot . 

Interval scan : 
- conceptually is a sub-type of full table scan 
- can be done in forward or backward direction
- is specific to qdb . 

Index scans are more straightforward, expect that our indexes aren't the usual b-trees but hash-map-like .

2023-04-12 09:12 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +There are two basic scan types in QuestDB, table and index scan.
If we use standard terms then interval scan is like a sub-type of full table scan but if we use ours then we can organize it like this : 

- Table scans 
  - Frame forward/backward scan 
  - Interval forward/backward scan 
- Index scans 
  - Index forward/backward scan in index order 
  - Index forward/backward scan in table order 

What do you think ?

2023-04-13 04:49 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
I guess we could do a diagram for each scan type with both directions added to the diagrams? For example:

![Screenshot 2023-04-13 at 12 46 03](https://user-images.githubusercontent.com/107401731/231656391-0c22ef48-5cf1-419e-a9e1-954e656365fd.png)

2023-04-13 04:53 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +There are two basic scan types in QuestDB, table and index scan.
We may not want to keep the headers exactly the same but I think overall this structure works better:
- Table scans
   - Frame (forward/backward) scan
   [diagram indicating both directions]
      - text and examples
   - Interval (forward/backward) scan
      [diagram indicating both directions]
      - text and examples
- Index scans
   - Index (forward/backward) scan in index order
        [diagram indicating both directions]
      - text and examples
  - Index (forward/backward) scan in table order
     [diagram indicating both directions]
      - text and examples

2023-04-13 06:37 UTC, amyshwang commented
I pushed commit `[e57622b](https://github.com/questdb/questdb.io/pull/1535/commits/e57622b378fe678819e4c9fc97d3d64bb3cbd6de)` for editorial changes - it is important that the changes do no alter the meaning.

I think this will then allow us to focus on terms and headers to use.

2023-04-13 06:43 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
UUnderstood.
But is this clear in the article?

> expect that our indexes aren't the usual b-trees but hash-map-like

2023-04-13 06:43 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
I moved the existing diagrams to places that I think suitable and they can be combined to one diagram for both directions.

2023-04-13 06:43 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +Note that while technically we're doing an interval forward scan, it doesn't really matter because there's just one interval to scan. While this makes sense with a single partition, it doesn't extend
I don't understand this because the plan says "Index backward scan"...Why is it technically a forward scan? Because it's sequential to the key?

2023-04-13 06:43 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +/>
I forgot to move this to L313

2023-04-13 11:38 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
For table scans it should be fine but wouldn't we need to change indices on index scan diagrams to show rows being read in backward direction ?

2023-04-13 23:47 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +There are two basic scan types in QuestDB, table and index scan.
Apologies - the structure I made in [e57622b](https://github.com/questdb/questdb.io/pull/1535/commits/e57622b378fe678819e4c9fc97d3d64bb3cbd6de) is what I think would work - I did keep the single key part!

2023-04-14 06:44 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
For table order and index order scan, I don't think the arrows for forward scan makes sense because (if I understand it correctly) you have numbered the scan sequence.

We could use the diagram, remove the arrow and add:

Index forward scan -multiple keys, table order]: scanning from (1) to (6) sequentially
Index forward scan -multiple keys, table order]: scanning from (6) to (1) in decreasing order

2023-04-14 06:48 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +Note that while technically we're doing an interval forward scan, it doesn't really matter because there's just one interval to scan. While this makes sense with a single partition, it doesn't extend
You did say:
> In the EXPLAIN output, a table forward scan is represented on the table level as Frame forward scan, and on the partition level, Row forward scan.

But it's under Table scan and by the time I am at Index scan, I don't remember that piece of info anymore @@ 

Maybe moving that line to the intro, before "Table scan" and after:

> QuestDB supports two main scan types, table and index scan. The difference is that the former touches table data directly, while the latter goes through the index first. Both types include sub-types and variants.

So in the intro we talk about:
- scan types
- scan levels

2023-04-14 09:14 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +
The arrow is not necessary, it just shows the scan direction on partition level .

2023-04-17 05:11 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +Note that while technically we're doing an interval forward scan, it doesn't really matter because there's just one interval to scan. While this makes sense with a single partition, it doesn't extend
I think this paragraph has not been updated and is still a bit confusing.

2023-04-17 05:25 UTC, amyshwang reviewed
Further comments about diagrams.

2023-04-17 05:25 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +
Is it right to insert a diagram here? It should be in "Index scan with a single key"?

2023-04-17 05:25 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +/>
The arrow only shows a forward scan. I wonder if my previous suggestion [here](https://github.com/questdb/questdb.io/pull/1535/files/57ea3e9071d825d181ee4297adca22c7993694c6#r1166356099) still applies?
> 
> We could use the diagram, remove the arrow and add:
> 
> Index forward scan -multiple keys, table order]: scanning from (1) to (6) sequentially
> Index forward scan -multiple keys, table order]: scanning from (6) to (1) in decreasing order

And the same for the index order diagram, where the arrow does not make sense.

2023-04-17 10:19 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +/>
I removed arrows but netlify still shows old diagrams.

2023-04-18 03:00 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +/>
Probably due to the cache.
I am not sure if it is obvious that the number in parenthesis indicates the order though. It took me a while to figure that out and I am still not sure if that's correct. Could you add some text to explain it?

2023-04-19 08:23 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +  `intervals: [("1970-01-01T00:00:00.000000Z","1970-01-01T23:59:59.999999Z")]`
I feel this important info should be in the intro as it is not just for Table scan?

2023-04-19 08:23 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +We hope you enjoy this tutorial.
Could we add an ending highlighting the benefit of using EXPLAIN to refine SQL queries?

2023-04-19 08:23 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +title: "EXPLAIN scan types"
We will need to change the title and slug

2023-04-19 08:23 UTC, amyshwang commented on docs/reference/sql/explain.md
> +- [EXPLAIN Basic Scans ](/blog/explain-sql-index-table-scan/)
This needs to change depending on the final title

2023-04-19 08:57 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +  `intervals: [("1970-01-01T00:00:00.000000Z","1970-01-01T23:59:59.999999Z")]`
I put it here because it makes them most sense with an example .

2023-04-20 08:37 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +We hope you enjoy this tutorial.
Added in latest commit .

2023-04-21 06:35 UTC, amyshwang reviewed
One final question!

2023-04-21 06:35 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +second index key, and so on.
The description and the diagram seem to be contradictory to each other.

<img width="674" alt="Screenshot 2023-04-21 at 14 31 49" src="https://user-images.githubusercontent.com/107401731/233558572-1bda42b3-b8f5-446e-9a86-8f13e68fa9f0.png">


>Index scans with multiple keys in index order scan table rows using row ids
associated with the first index key, followed by those associated with the
second index key, and so on.

The diagram shows scanning table rows using row ids
associated with the first index key in the first partition, followed by the table row ids with the second index key in the same partition. The scan then continues to the second partition.

2023-04-21 07:22 UTC, bziobrowski commented on blog/2023-04-20-explain-basic-scans.md
> +second index key, and so on.
I guess the explanation on two levels of iteration/scanning isn't clear enough . 
Indexes are partitioned  and scanning on the top level happens on partitions or intervals and for each such 'Frame' runs a  row or index scan .

2023-04-21 08:59 UTC, amyshwang requested changes

2023-04-21 08:59 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +partition or interval, the output still in timestamp order.
```suggestion
partition or interval, with the output still in timestamp order.
```

2023-04-21 08:59 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +Frame forward scans start at the first row of the oldest partition (one with lowest timestamp partition key value)
the one with the lowest timestamp, and the one with the highest timestamp in L86

2023-04-21 08:59 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +- A list of scan boundaries in `Interval scan`, e.g.\
```suggestion
- A list of scan boundaries in `Interval scan`, e.g.
```

2023-04-21 08:59 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +`timestamp BETWEEN '2023-01-19T23:59:00.000000Z' AND '2023-01-20T23:59:00.000000Z'`\
```suggestion
Rewriting the `WHERE` condition to
`timestamp BETWEEN '2023-01-19T23:59:00.000000Z' AND '2023-01-20T23:59:00.000000Z'`
```

2023-04-21 09:09 UTC, amyshwang commented on blog/2023-04-20-explain-basic-scans.md
> +second index key, and so on.
Might it be better to update this paragraph too?
```suggestion
Multiple-key-index-order scans iterate one partition after another,  scanning table rows using row ids associated with the first index key, followed by those associated with the second index key, and so on.
```

2023-04-25 08:07 UTC, amyshwang approved these changes
Thank you @bziobrowski for your patience!

2023-04-25 08:28 UTC, merged