updated footer, changed spacing
questdb/questdb.io pull request #1565
Opened 2023-04-14 14:54 UTC by saikrishnatbijil

made footer more good by adjusting some spacing 
**before:**
![Screen Shot 2023-04-14 at 8 19 29 PM](https://user-images.githubusercontent.com/98866798/232078640-7069ef60-b557-467a-b0cf-3caad9a97b8c.png)
**after:**
![Screen Shot 2023-04-14 at 8 19 06 PM](https://user-images.githubusercontent.com/98866798/232078759-52bd0851-ca23-4591-a76a-5f9a9b32bb7a.png)
now it looks more good and gives more space to breath.

2023-04-14 16:59 UTC, argshook requested changes
Hey, thanks for contribution!

We can add this change but the suggested code is too bulky for a little tweak.

All that's needed for this layout is to use these rules on the `div` in line `123`:

```
display: grid;
grid-template-columns: auto min-content min-content;
```

please add it as a new class and we can merge!

2023-04-14 17:29 UTC, saikrishnatbijil commented
@argshook requested changes are added

2023-04-14 17:54 UTC, argshook commented
@saikrishnatbijil 

> @argshook requested changes are added

thanks! sorry i should have mentioned, now your previously done changes should be reverted. For example, there's no longer class name like `styles.margin` that you added previously

2023-04-14 18:08 UTC, saikrishnatbijil commented
@argshook i have added margin back

2023-04-14 18:16 UTC, argshook commented
@saikrishnatbijil 

pardon me for not being clear enough!

the code should be like so:

at the bottom of `src/theme/Footer/index.tsx`:
```
      <div className={clsx(styles.border, styles.bottom)}>
        {customFields.copyright}
        <a className={styles.link} href="/privacy-notice/">
          Privacy
        </a>
        <a className={styles.link} href="/terms/">
          Terms
        </a>
      </div>
```

and `src/theme/Footer/styles.module.css`:
```
.bottom {
  display: grid;
  grid-template-columns: auto min-content min-content;
  align-items: center;
  padding: 1rem 1rem 2rem;
  gap: 2rem;
  color: var(--palette-white);
}
```

and that's it! The desired effect should be done.

Please notice how the only `className` used is `styles.bottom`, there's no `styles.spacing` nor `styles.margin`.

This change also reduces the number of nested `div`s which is always a nice thing to do.

2023-04-15 04:19 UTC, saikrishnatbijil commented
@argshook i have changed the code that it is more efficient. Thank you for the suggestion

2023-04-17 09:55 UTC, argshook requested changes
Hey, pardon for being so nit-picky, however, we constantly want to improve code quality, including doing design changes.

I'm putting my code changes as code suggestions, so it should be easy to get them in, there should be no need for you to open a new PR or something.

If you're not familiar with code suggestions, here's a [1 minute guide](https://egghead.io/lessons/github-add-suggestions-in-a-github-pr-review)

2023-04-17 09:55 UTC, argshook commented on src/theme/Footer/styles.module.css
> +  grid-template-columns: auto min-content min-content;
```suggestion
  grid-template-columns: auto min-content min-content;
  max-width: var(--ifm-container-width);
  margin: 0 auto;
```

2023-04-17 09:55 UTC, argshook commented on src/theme/Footer/index.tsx
> +        <div className={clsx(styles.border, styles.bottom)}>
```suggestion
      <div className={styles.border}>
        <div classNames={styles.bottom}>
```

2023-04-17 10:14 UTC, saikrishnatbijil commented
So sorry @argshook i am just starting out in open source and learning how git and github works. Thank you for your great support. Does everything look good now

2023-04-17 10:48 UTC, argshook commented
> So sorry @argshook i am just starting out in open source and learning how git and github works. Thank you for your great support. Does everything look good now

no need to apologise, i think you're doing great!

It looks good, thanks for being patient with my review. I'll merge once build is complete

2023-04-17 10:49 UTC, argshook approved these changes

2023-04-17 10:51 UTC, merged