Blog post options taxi
questdb/questdb.io pull request #162
Opened 2020-10-16 13:29 UTC by TheTanc

2020-10-16 13:43 UTC, mpsq requested changes

2020-10-16 13:43 UTC, mpsq commented on blog/2020-09-24-peformance-matters.md
> +---
This file should not be new, did you rebase against master?

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +tags: [nyc taxi dataset, options]
```suggestion
tags: [deep-dive, story]
```

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +description: An experiment analyzing the NYC taxi dataset through the eye of an options trader.
```suggestion
description: An experiment analyzing the NYC taxi dataset through the eyes of an options trader.
```

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +A couple of weeks ago, I was preparing data for the demo we are hosting of QuestDB which you can try [here](http://try.questdb.io:9000/).
Could you rename the [here] link? This is not optimal for good user experience.

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +  alt="A chart of call option payoff showing how cab drivers earnings increase with their average realised driving speed"
```suggestion
  alt="A chart of call option payoff showing how cab drivers earnings increase with their average realized driving speed"
```

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +  alt="A chart of call option payoff showing how cab drivers earnings increase with their average realised driving speed broken down between fixed and variable"
```suggestion
  alt="A chart of call option payoff showing how cab drivers earnings increase with their average realized driving speed broken down between fixed and variable"
```

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +We made this dataset and the database available online. You can query it directly from your browser [here](http://try.questdb.io:9000/).
Same as above, [here] links are not recommanded

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +We normalise it as an `hourly rate` assuming drivers are constantly driving a customer.
```suggestion
We normalize it as an `hourly rate` assuming drivers are constantly driving a customer. 
```

2020-10-16 13:43 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +Let’s visualise this by plotting  the values for our game in the following chart:
```suggestion
Let’s visualize this by plotting  the values for our game in the following chart:
```

2020-10-16 13:45 UTC, mpsq commented on blog/2020-10-16-taxi-drivers-are-options-traders.md
> +## Customers are losing too.
```suggestion
## Customers are losing too
```

2020-10-16 20:23 UTC, TheTanc commented on blog/2020-09-24-peformance-matters.md
> +---
I did but nevermind. Deleted the file

2020-10-19 15:53 UTC, mpsq approved these changes

2020-10-21 16:39 UTC, merged