chore(docs) - updating Python scripts to use psycopg3
questdb/questdb.io pull request #1658
Opened 2023-05-05 09:53 UTC by amyshwang

2023-05-31 11:21 UTC, amyshwang commented on docs/concept/geohashes.md
> +      cur.execute('''INSERT INTO geo_data values(now(), 'device_1', 'u', 'u33d8b12');''')
I don't understand this but INSERT INTO needs triple quotation marks; otherwise, I get a syntax error. Other query is fine with single quotation mark...

2023-05-31 11:46 UTC, amunra commented on docs/concept/geohashes.md
> +      cur.execute('''INSERT INTO geo_data values(now(), 'device_1', 'u', 'u33d8b12');''')
You can just use double quotes, but triple singles are also fine.

Single quotes can hold double quotes without escaping.
Double quotes can hold single quotes without escaping.

Triple single/double quotes allow nesting of individual single/double quote chars too.

```python
>>> 'a'
'a'
>>> "a"
'a'
>>> '"'
'"'
>>> "'"
"'"
>>> '\''
"'"
>>> "\""
'"'
>>> """a"b"""
'a"b'
>>> '''a'b'''
"a'b"
```

2023-05-31 11:55 UTC, amunra requested changes
Minor clean-up required.

2023-05-31 11:55 UTC, amunra commented on docs/concept/geohashes.md
> +python3 -m pip install "psycopg[binary]" -U questdb
You don't need the `-U questdb` part for this: The `questdb` package is just for ILP.
Just `python3 -m pip install "psycopg[binary]"` will do.

2023-05-31 11:55 UTC, amunra commented on docs/concept/geohashes.md
> +# the connection is now closed
You can remove this comment regarding the closed connection.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +    # Update records
Indent comment to line below.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +    #Query the database to show the updated values.
Indent comment to line below.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +        #Query the database and obtain data as Python objects.
Add space after `#`.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +    #Query the database to show the updated values.
Add space after `#`.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +# the connection is now closed
Remove comment.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +
Remove blank line.

2023-05-31 11:55 UTC, amunra commented on docs/develop/update-data.md
> +
Do the same with other blank lines around comments.

2023-05-31 19:32 UTC, amunra submitted a review, later dismissed
:+1:

2023-06-02 13:58 UTC, amunra approved these changes

2023-06-02 14:24 UTC, merged