chores(docs): improve workflow for Superset
questdb/questdb.io pull request #1690
Opened 2023-05-18 14:33 UTC by amyshwang

I was able to start Superset following the new steps. However, when I log in Superset via http://localhost:8088/ + admin sign in, it was linking to my previous trial.
As a result, also database connection tested okay, I was not able to connect to a new questdb instance.
I can also see the previous dataset but I cannot delete it.

2023-05-19 08:35 UTC, amyshwang commented on docs/third-party-tools/superset.md
> +
I got an invalid decryption key when connecting to the database although the connection test was successful.
I could access the UI seeing my previous dataset but when adding new one following the tutorial, I got "invalid decryption key" error.

2023-05-19 09:49 UTC, javier commented on docs/third-party-tools/superset.md
> +
This is because your volumnes for these docker containers were previously created and used a different key. 
You can start completely from scratch by executing

```
docker compose down -v
```
That will remove your docker volumes for your superset docker containers. Next time you start volumes will be empty (and initialized by superset with the default admin user). That will also solve the decryption key error

2023-05-19 11:26 UTC, amyshwang commented on docs/third-party-tools/superset.md
>  - Python from 3.8.x to 3.10.x
Quick note: 
stand alone
pip install qdb connect 
installing superset - https://superset.apache.org/docs/installation/installing-superset-from-scratch

Docker

2023-05-29 11:45 UTC, javier requested changes
I am not too happy with the current flow yet. Pushed a commit directly with my proposed changes

2023-05-31 11:33 UTC, marregui commented on docs/third-party-tools/superset.md
> +1. Update the requirement:
fixed in a700779988a32092ad17ecfd5bbd2205946cf7d5

2023-05-31 11:54 UTC, marregui approved these changes
LGTM I have tested these exact steps, it all works for me.

2023-06-01 16:10 UTC, javier commented on docs/third-party-tools/superset.md
> +- Psycopg2 for connectivity
not needed. Superset will install it as a dependency

2023-06-01 16:11 UTC, javier commented on docs/third-party-tools/superset.md
> +- SQLAlchemy for ORM and easy interaction
same as above. Not needed. Superset will install it

2023-06-01 16:11 UTC, javier approved these changes
Looking good. Still two requirements that we can remove (from the stand alone section) but already looking good to me

2023-06-01 16:16 UTC, javier approved these changes
All good!

2023-06-01 16:18 UTC, merged