ILP blog post
questdb/questdb.io pull request #180
Opened 2020-10-20 17:00 UTC by patrickSpaceSurfer

2020-10-20 17:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=180) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=180) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=180) it.</sub>

2020-10-21 09:33 UTC, mpsq requested changes
Minor tweaks, it looks good overall!

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +Line protocol is a simple and convenient way to add data points to QuestDB. Now with [autentication](/docs/reference/api/influxdb/#authentication) your end point is more secure.
```suggestion
InfluxDB line protocol is a simple and convenient way to add data points to QuestDB. Now with [authentication](/docs/reference/api/influxdb/#authentication), your endpoint is more secure.
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +  QuestDB has added authentication for line protocol over TCP
```suggestion
  QuestDB has added authentication for InfluxDB line protocol over TCP
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +title: Authentication for line protocol
```suggestion
title: Authentication for InfluxDB line protocol
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +[Line protocol](/docs/reference/api/influxdb) is popular becuase its a simple text based format, you just open a socket and send data points line by line. Implementation is easy because encoding is t
```suggestion
[InfluxDB line protocol](/docs/reference/api/influxdb) is popular because it is a simple text based format, you simply open a socket and send data points line by line. Implementation is easy because encoding is trivial and there is no response to parse. The protocol can be used over UDP or TCP with minimal overhead.
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +This is all great as long as your end point can not be accessed by unauthorised actors that could send your database junk. If your end point is not secure then you can secure it by encapsulating it i
```suggestion
This is all great as long as your end point can not be accessed by unauthorised actors that could send junk to your database. If your endpoint is public, then you could secure it by encapsulating it in a secure transport layer such as [TLS](https://en.wikipedia.org/wiki/Transport_Layer_Security), adding complexity to your infrastructure that needs to be managed. This is something we sought to avoid. Our goals when implementing authentication were:
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +To these ends we decided to provide authentication for line protocol over TCP with a simple [challenge/response](https://en.wikipedia.org/wiki/Challenge%E2%80%93response_authentication) mechanism, wh
```suggestion
To these ends we decided to provide authentication for the InfluxDB line protocol over TCP with a simple [challenge/response](https://en.wikipedia.org/wiki/Challenge%E2%80%93response_authentication) mechanism, where the challenge is a [nonce](https://en.wikipedia.org/wiki/Cryptographic_nonce) and the response a signature. [Elliptic curve cryptography](https://en.wikipedia.org/wiki/Elliptic-curve_cryptography) (ECC curve P-256) with [SHA-256](https://en.wikipedia.org/wiki/SHA-2) was chosen for the signature algorithm, this ensures strong authentication that is hopefully future proof. The elliptic curve cryptographic keys have a public and secret component, it is possible to configure QuestDB with just the public part, thereby mitigating any risks of storing secret information on the server. Languages such as [JavaScript and Go](/docs/develop/insert-data/#influxdb-line-protocol) have standard libraries that implement ECC, the [JSON Web Key](https://tools.ietf.org/html/rfc7517) standard can be used to store and distribute the keys in a clear and ubiquitous manner.
```

2020-10-21 09:33 UTC, mpsq commented on blog/2020-10-20-authentication-for-influx-line-protocol.md
> +The authentication challenge/response mechanism was chosen to minimise the impact on the line protocol, it works as follows:
```suggestion
The authentication challenge/response mechanism was chosen to minimise the impact on the protocol, it works as follows:
```

2020-10-21 14:35 UTC, mpsq approved these changes
LGTM

2020-10-21 16:40 UTC, bluestreak01 approved these changes

2020-10-21 16:41 UTC, merged