[WIP] feat(pages): Redesign pricing page
questdb/questdb.io pull request #1802
Opened 2023-07-14 20:17 UTC by oliver-daniel

Feature branch documenting changes to the pricing page, primarily surrounding the movement of focus from different cloud pricing plans to three streams of QuestDB products.

2023-07-17 14:25 UTC, argshook commented on src/modules/cloud/ContactForm/index.tsx
> +  interestedIn?: ProductInfo["type"] | "custom" | "cloud" | "sla"
need to make sure that contact forms still need this `interestedIn` value

2023-07-18 09:24 UTC, insmac commented on src/modules/cloud/ContactForm/index.tsx
> +  interestedIn?:
Feel free to remove `interestedIn` altogether. It's not used anymore, as the AWS API route used only covers the Cloud CTA.

2023-07-18 11:43 UTC, argshook commented
hey @oliver-daniel, i opened a PR to your PR with some suggested changes. Tried to make the code a bit more simple where possible.

https://github.com/questdb/questdb.io/pull/1804

2023-07-24 17:28 UTC, argshook requested changes

2023-07-24 17:28 UTC, argshook commented on src/components/Slider/index.tsx
> +  // name: string
```suggestion
```

2023-07-24 17:28 UTC, argshook commented on src/components/Slider/style.module.css
> +  --thumb-size: 1.8rem;
```suggestion
  --thumb-size: 1.5rem;
```

1.8 is a bit too much IMO

2023-07-24 17:28 UTC, argshook commented on src/components/Slider/style.module.css
> +  padding: 1rem;
```suggestion
  padding: 0.3rem 0.5rem;
```

2023-07-24 17:28 UTC, argshook commented on src/components/Toggle/index.tsx
> +type Labellable = string | { label: string }
is there a good reason to have union type? maybe it's enough to support just `string`?

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/index.tsx
> +  // const [provider /*, setProvider */] = useState<ProviderKey>("aws")
```suggestion
```

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/prices.ts
> +// the actual possible regions
```suggestion
```

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/prices.ts
> +type AvailableRegion = Extract<typeof regions[number], { available: true }>
is it useful to have a type with only available regions?
maybe there can be just `Regions` and runtime (not typescript type check) decides whether they're available?

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/prices.ts
> +  // _0 to preserve trailing zeroes
```suggestion
```

IMO this should be a job for the view. The numbers here should not include information needed for view. Maybe [Number.prototype.toFixed() - JavaScript | MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed) can help here

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/prices.ts
> +}, {} as {})
the `as` casting should be used sparsely, only when really really needed. It's ok now, don't sweat this line, we'll figure it out later on.

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/style.module.css
> +  width: 100%;
```suggestion
```

maybe not needed?

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/products/products.ts
> +        // * 25 GB storage
useful comment :+1:

2023-07-24 17:28 UTC, argshook commented on src/modules/pricing/pricing-calculator/style.module.css
> +    width: 50ch;
```suggestion
    width: 50ch;
```

maybe this can be expressed via percentage?

2023-07-24 17:44 UTC, oliver-daniel commented on src/components/Toggle/index.tsx
> +type Labellable = string | { label: string }
Fair point; no guarantee that an object type with a `label` prop would even satisfy the `selected === option` predicate on L27.

2023-07-24 17:46 UTC, oliver-daniel commented on src/modules/pricing/pricing-calculator/index.tsx
> +  // const [provider /*, setProvider */] = useState<ProviderKey>("aws")
Do you recommend leaving a more "English" comment for posterity (i.e., asserting that the `region` value is only fixed as `aws` until the other providers are implemented), or just trust future programmers' common sense?

2023-07-24 17:48 UTC, oliver-daniel commented on src/modules/pricing/pricing-calculator/prices.ts
> +type AvailableRegion = Extract<typeof regions[number], { available: true }>
This was more useful in an older version of the PR, where the `pricesByRegion` object would more aggressively assert that it contained pricings for all available regions. Doing it at runtime sounds fine.

2023-07-24 17:50 UTC, oliver-daniel commented on src/modules/pricing/pricing-calculator/prices.ts
> +  // _0 to preserve trailing zeroes
Fair point; I was looking at this from a purely DX perspective, to make it explicit that yes, the thousands place of this price *is* a zero and not an accidentally deleted digit. Prettier wasn't too happy about that, so this was a clunky workaround. Will remove.

2023-07-24 17:51 UTC, argshook commented on src/modules/pricing/pricing-calculator/index.tsx
> +  // const [provider /*, setProvider */] = useState<ProviderKey>("aws")
Let's implement it when/if needed. Until then a comment can be considered noise. 

https://en.m.wikipedia.org/wiki/You_aren%27t_gonna_need_it

2023-07-24 17:55 UTC, oliver-daniel commented on src/components/Toggle/index.tsx
> +type Labellable = string | { label: string }
The main point was to have a distinction between latent values and user-friendly strings (think country codes vs names), but that's a future problem.

2023-07-24 18:16 UTC, oliver-daniel commented on src/modules/pricing/pricing-calculator/style.module.css
> +    width: 50ch;
The main issue I'm encountering is that when the width is anything other than a fixed constant, there's a weird interplay between the length of this content and the overall width of the card as sliders move, resulting in a really disorienting jitter effect. Fixes are very welcomed if you have ideas.

2023-07-25 15:50 UTC, argshook commented on src/components/Toggle/index.tsx
> +type Labellable = string | { label: string }
`Toggle` as a reusable component just gets a list of `options` and calls `onClick` with whichever option was clicked. It doesn't need to know if the option is country name or code or something else.

p.s. `onClick` should really be `onChange`

2023-07-26 09:25 UTC, argshook submitted a review, later dismissed

2023-07-26 10:43 UTC, argshook approved these changes

2023-07-26 10:49 UTC, merged