Add 3rd party tool - qStudio.
questdb/questdb.io pull request #1827
Opened 2023-07-31 12:44 UTC by ryanhamilton

A free SQL querying tool that allows time-series charting.

2023-07-31 12:44 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=1827) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=1827) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=1827) it.</sub>

2023-08-01 10:25 UTC, javier commented on docs/third-party-tools/qstudio.md
> +user:user
user needs to be `admin`

2023-08-01 10:34 UTC, quankaroo commented on docs/third-party-tools/qstudio.md
> +user:user
Good catch. Fixed.

2023-08-01 10:46 UTC, javier approved these changes
Thanks!

2023-08-01 11:05 UTC, argshook requested changes
hey @ryanhamilton thanks a lot for contributing!

there's one issue with screenshot image path, i have pushed a code suggestion. Once fixed, we can merge this PR.

Thank you!

2023-08-01 11:05 UTC, argshook commented on docs/third-party-tools/qstudio.md
> +![Screenshot of the qStudio UI query](/img/docs/guide/qstudio/qstudio-query.png)
```suggestion
![Screenshot of the qStudio UI query](/img/guides/qstudio/qstudio-query.png)
```

2023-08-02 07:59 UTC, ryanhamilton commented
Merged your suggestion, thanks Arijus. 
I also just learnt about github suggestions today, very cool.

2023-08-02 08:22 UTC, argshook approved these changes

2023-08-02 08:22 UTC, merged

2023-08-02 08:25 UTC, argshook commented
> Merged your suggestion, thanks Arijus.

awesome, thanks!

> I also just learnt about github suggestions today, very cool.

If you don't know about the dot yet, it should be impress you!

try pressing `.` on your keyboard when browsing some github page (like this one)