IPv4 documentation
questdb/questdb.io pull request #1832
Opened 2023-08-01 20:21 UTC by goodroot

Supports https://github.com/questdb/questdb/pull/3523.

2023-08-10 16:34 UTC, goodroot commented on docs/reference/sql/datatypes.md
> +| `ipv4`         | `4`          | Yes       | String argument may be in the form `23.62.200.1` (ip address without netmask), `5.43.11.8/2` (ip address with netmask), or `2.232/16` (subnet with netmas
@allegraharris 🆘

2023-08-10 16:37 UTC, goodroot commented on docs/reference/api/ilp/columnset-types.md
> +?? TODO
@allegraharris 🆘

2023-08-10 17:18 UTC, allegraharris requested changes

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/api/ilp/columnset-types.md
> +Explicit type cast functions, including `cast` and `::`.
Explicit cast ipv4 <-> int, ipv4 <-> string

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/api/ilp/columnset-types.md
> +Explicit type cast functions, including `cast` and `::`.
I just found a bug with ipv4 -> string cast which I'll fix now btw

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +### << Strict IP address contained by?
Maybe take away the ? as it's no longer phrased as a question + same for contained by or equal below

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Returns an IPv4 address (string).
To print it to the console in dotted format (1.1.1.1) we have to print it as a string but given that internally ipv4 is an int, I think it is confusing/misleading to say that the return value is a string so I think it would be better to change all occurrences to just be "returns an ipv4 address"

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +### + Add off set to an IP address
Delete space between 'off' and 'set'

2023-08-10 17:18 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Random address generator for a single address.
What do you mean by 'for a single address'? rnd_ipv4() will generate random ips within the full valid range of ip addresses 0.0.0.1-255.255.255.255

2023-08-10 17:26 UTC, allegraharris commented on docs/reference/api/ilp/columnset-types.md
> +?? TODO
Example: 
```
test col=\"255.255.255.254\" 631150000000000000\n 
test col=\"255.255.255.255\" 631150000000000000\n
```

2023-08-10 20:54 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +### << Strict IP address contained by?
👍

2023-08-10 21:01 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +Random address generator for a single address.
Typo!

2023-08-10 21:12 UTC, goodroot commented on docs/reference/api/ilp/columnset-types.md
> +Explicit type cast functions, including `cast` and `::`.
@allegraharris Thanks for the review!

Applied all changes, however left this one open.

Let me know if we're OK.

2023-08-11 11:25 UTC, allegraharris requested changes

2023-08-11 11:25 UTC, allegraharris commented on docs/reference/sql/datatypes.md
> +| `ipv4`         | `4`          | Yes       | Signed integer `0.0.0.1` to `255.255.255. 255`
```suggestion
| `ipv4`         | `32`          | Yes       | `0.0.0.1` to `255.255.255. 255`                                                                                                                                                                                 |
```

2023-08-11 17:40 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +Returns a range of IPv4 addresses.
No worries! Writing is hard. :)

2023-08-11 17:45 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +Returns an IPv4 address.
Pedantry thrives in documentation. 

Returns an IPv4 says:

Returns an Internet Protocol version 4.

Returns an IPv4 address says:

Returns an Internet Protocol version 4 address.

2023-08-11 17:46 UTC, goodroot commented on docs/reference/api/ilp/columnset-types.md
> +Explicit cast `ipv4 <-> int`, `ipv4 <-> string`.
You're right -- I don't think we need this section at all. 💣

2023-08-11 18:05 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +Argument may contain a netmask.
OK -- added more to the introduction, to wrap all these datatypes:

Specified:

* expected ranges
* storage as integers
* trailing & leading docs

Also elaborated each section to clarify string/int relationship per item.

2023-08-11 18:06 UTC, goodroot commented on docs/reference/sql/datatypes.md
> +| `ipv4`         | `0.0.0.0` or `0`                                                 | IPv4 addresses are stored as `int`. |
Agreed!

2023-08-11 18:12 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +## Limitations
Put this here to leave the other pages be.

They need a general overhaul, so will save that for another day.

2023-08-14 10:20 UTC, allegraharris requested changes

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are **passed** as string, but are **stored** as 32bit integers.
```suggestion
IPv4 addresses are **passed** as string, but are **stored** as 32-bit integers.
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +As a result, string arguments can accept IPv4 addresses with a subnet mask.
```suggestion
The string argument can accept IPv4 addresses with a subnet mask.
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +As a result, string arguments can accept IPv4 addresses with a subnet mask.
```suggestion
The string argument can accept IPv4 addresses with a subnet mask.
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Therefore they cannot contain a subnet mask.
```suggestion
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Therefore they cannot contain a subnet mask.
```suggestion
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Therefore the argument cannot contain a subnet mask.
```suggestion
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Therefore they cannot contain a subnet mask.
```suggestion
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/sql/datatypes.md
> +| `ipv4`         | `32`          | Yes       | Signed integer `0.0.0.1` to `255.255.255. 255`
```suggestion
| `ipv4`         | `32`          | Yes       | `0.0.0.1` to `255.255.255. 255`                                                                                                                                                                                 |
```

2023-08-14 10:20 UTC, allegraharris commented on docs/reference/sql/insert.md
> +String arguments must be an ip address without a netmask: `23.62.200.1`
```suggestion
String arguments must be in dotted decimal notation: `23.62.200.1` 
```

2023-08-14 14:59 UTC, allegraharris approved these changes
Looks good to me!

2023-08-14 15:00 UTC, allegraharris commented on docs/reference/api/ilp/columnset-types.md
> +Explicit type cast functions, including `cast` and `::`.
Made the change, just waiting for it to be merged into master so I'll resolve the conversation now

2023-08-14 15:07 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Argument may contain a netmask.
Great! Thanks

2023-08-14 15:12 UTC, merged