doc(chore) update ipv4 content and add doc links
questdb/questdb.io pull request #1861
Opened 2023-08-14 15:35 UTC by goodroot

* clarity re: ipv4
* docs for ipv4 & `to_uuid()`

2023-08-14 15:52 UTC, insmac submitted a review, later dismissed

2023-08-14 16:28 UTC, allegraharris requested changes

2023-08-14 16:28 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
Lines 115-134 need some reworking

2023-08-14 16:28 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
Lines 115-119 should be cut

2023-08-14 16:28 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
127-134 should be changed to this: 

```sql
* `<<`: is an ip address strictly contained by subnet? (`boolean`)
* `<<=`: is an ip address contained by or equal to subnet? (`boolean`)
* `&`: computes bitwise AND (`ipv4`)
* `~`: computes bitwise NOT (`ipv4`)
* `|`: computes bitwise OR (`ipv4`)
* `+`: adds an offset to an ip address (`ipv4`)
* `-`: `ipv4-int`: subtracts an offset from an ip address (`ipv4`)
* `-`: `ipv4 - ipv4`: computes the difference between two ip addresses (`long`)
```

2023-08-14 16:28 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
Line 107 - we don't provide native support for subnets / netmasks 
We do provide validity checking + ipv4 specific functions which would be better to discuss here

2023-08-14 17:14 UTC, allegraharris requested changes

2023-08-14 17:14 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* add more..
Supported SQL funcs: 

- case e.g., `select ip, bytes, case when ip << '2.65.32.1/2' then 1 else 0 end from test`
- count e.g., `select count(ip), bytes from test`
- first e.g., `select first(ip) from test`
- last e.g., `select last(ip) from test`
- full join e.g., `select a.count, a.ip, b.ip2, b.count2 from '*!*test' a join '*!*test2' b on b.ip2 = a.ip`
- group by e.g., `select count(count), ip from test group by ip`
- count_distinct e.g., `select count_distinct(ip) from test`
- distinct e.g., `select distinct ip from test order by ip`
- select e.g., `select ip from x except select ip2 from y`
- intersect e.g., `select ip from x intersect select ip2 from y`
- isOrdered e.g., `select isOrdered(ip) from test`
- nullif e.g., `select k, nullif(ip, '0.0.0.5') from test`
- rank e.g., `select ip, bytes, rank() over (order by ip asc) rank from test order by rank`
- union eg., `select ip from x union select ip2 from y`
- union all e.g., `select ip from x union all select ip2 from y`
- inner join e.g., `select test.count, test2.count2 from test inner join test2 on test2.ip2 = test.ip`
- latest by e.g., `select * from test latest by ip`
- left join e.g., `select test.ip, test2.ip2, test.count, test2.count2 from test left join test2 on test2.ip2 = test.ip`
- max e.g., `select max(ip) from test`
- min e.g., `select min(ip) from test`
- order by e.g., `select * from test order by ip, bytes, ts`
- sample by e.g., `select ip, ts, sum(bytes) from test sample by 1y order by 2,1`
- where e.g., `select * from test where ip = '0.0.0.1'`

2023-08-14 17:15 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `netmask()` needs more
```suggestion
* `netmask(string)` : returns an ip address' subnet mask (`ipv4`)
```

2023-08-14 21:25 UTC, goodroot commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* add more..
@allegraharris Thanks!

Release posts are more at-a-glance, so instead of lining all of this out here, created a new ipv4 page under functions. It made sense in a table, and is now part of this PR.

2023-08-14 21:28 UTC, goodroot commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +### QuestDB IPv4 vs PostegreSQL inet
@allegraharris Going to pull this out for now, too, and we can add it into the docs. IMO we're covered at-a-glance.

2023-08-15 09:29 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* add more..
Great, thank you!

2023-08-15 09:33 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +IPv4 addresses are a common data type with their own unique numerical convention. We often hear from teams who are tracking the activity of users, servers or sensors, that managing IP addresses witho
```suggestion
IPv4 addresses are a common data type with their own unique numerical convention. We often hear from teams who are tracking the activity of users, servers or sensors, that managing IP addresses without validity checks and type-specific functions can be frustrating. 
```

2023-08-15 09:37 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +Yes! IPv4 addresses are stored as integers on disk, and passed as strings.
```suggestion
Yes! IPv4 addresses are stored as integers on disk, and passed as strings. IPv4 addresses may not contain netmasks when being stored on disk, however, when they are being passed as a string argument to a function (e.g., subnet inclusion operators: <<=, <<) they may also take the form of ip address with netmask or subnet with netmask (see below).
```

2023-08-15 09:38 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `<<`: is an ip address strictly contained by subnet? (`boolean`)
```suggestion
* `<<`: is an ip address strictly contained by a subnet? (`boolean`)
```

2023-08-15 09:40 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
>  There are also two additional functions for testing:
```suggestion
There are also two additional random functions for testing as well as a netmask function:
```

2023-08-15 09:41 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +The IPv4 data type supports SQL functions, like `CASE`, `NULLIF`, `UNION ALL` and many more. For a full list, [checkout our documentation](/docs/reference/function/ipv4/).
```suggestion
The IPv4 data type supports SQL functions, like `ORDER BY`, `SAMPLE BY`, `LATEST BY` and many more. For a full list, [checkout our documentation](/docs/reference/function/ipv4/).
```

2023-08-15 09:43 UTC, allegraharris commented on docs/reference/function/ipv4.md
> +| **UNION EG.** | `SELECT ip FROM x UNION SELECT ip2 FROM y` |
```suggestion
| **UNION** | `SELECT ip FROM x UNION SELECT ip2 FROM y` |
```

2023-08-15 09:45 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
Might be worth adding a heading and link here redirecting users to a page on the similarities/differences between ipv4 and inet like for the SQL functions - I'll start working on the content for that table now

2023-08-15 17:07 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `-`: `ipv4 - ipv4`: computes the difference between two ip addresses (`long`)
Could you update the operators to reflect this pr https://github.com/questdb/questdb/pull/3650 please? Thanks!

2023-08-15 17:20 UTC, goodroot commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `-`: `ipv4 - ipv4`: computes the difference between two ip addresses (`long`)
On it now, in a separate PR I am also adding them to docs.

2023-08-15 17:45 UTC, goodroot commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `-`: `ipv4 - ipv4`: computes the difference between two ip addresses (`long`)
Included in our our list.

& to merge after: https://github.com/questdb/questdb.io/pull/1865

2023-08-15 19:16 UTC, goodroot commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
We'll tackle in separate PR. 👍

2023-08-15 19:25 UTC, allegraharris commented on blog/2023-08-07-questdb-release-7.3-deduplication-ipv4.mdx
> +* `-`: `ipv4 - ipv4`: computes the difference between two ip addresses (`long`)
Great!

2023-08-15 19:29 UTC, tris0laris approved these changes

2023-08-15 19:35 UTC, merged