chore(docs) IPv4 clarity
questdb/questdb.io pull request #1877
Opened 2023-08-17 15:12 UTC by goodroot

Alters language regarding string/int & its relevance to how IPv4 is passed.

2023-08-17 15:29 UTC, allegraharris requested changes

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/function/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255` and are stored as `int`. However, some IPv4 Operators allow IPv4 addresses to pass as `string` and contain a subnet and/or n
```suggestion
For IPv4 operators, see the [IPv4 Operators page](/docs/reference/operators/ipv4/).
```

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/function/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255` and are stored as `int`. However, some IPv4 Operators allow IPv4 addresses to pass as `string` and contain a subnet and/or n
There aren't any general SQL functions that take a string IPv4 arg so perhaps best to revert to what it was before

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
```suggestion
IPv4 addresses are stored as `int` but are passed as `string` in dotted decimal notation.
```

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
I think it might be better to only mention netmask stuff with the specific operators/functions that support it so as to avoid confusion

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
I can't add comments on those lines as they were not changed in this pr but would it be possible to add examples of string arguments under <<. <<=, rnd_ipv4(string, int) and netmask() as those are the only operators/functions that support string args? 

Also, just noticed that we don't have netmask() on this page - would it be possible to add it please? See this pr for detail https://github.com/questdb/questdb/pull/3624

2023-08-17 15:29 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
And also maybe an example for rnd_ipv4() as it's the only one that doesn't have one? Thanks!

2023-08-17 16:15 UTC, goodroot commented on docs/reference/function/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255` and are stored as `int`. However, some IPv4 Operators allow IPv4 addresses to pass as `string` and contain a subnet and/or n
Some of the function examples contain operators.

That made me feel they need some additional context.

Thoughts?

2023-08-17 16:20 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
If we don't have anything about subnets/netmasks/strings at the top of this page, we don't discuss them until they appear in the examples. I'd say it's okay to intro them, especially because they do appear in the function examples too:

```
SELECT ip, bytes, CASE WHEN ip << '2.65.32.1/2' THEN 1 ELSE 0 END FROM example
```

I'll defer to you if you feel strongly enough, but IMO this is fair balance.

---

Will also add the additions. 👍

2023-08-17 16:28 UTC, allegraharris commented on docs/reference/function/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255` and are stored as `int`. However, some IPv4 Operators allow IPv4 addresses to pass as `string` and contain a subnet and/or n
Yeah I see what you mean - maybe add a clarifying sentence about the fact that string args are distinct from ipv4 args that are passed as strings?

2023-08-17 16:44 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
@allegraharris Okay -- that's probably better.

WDYT?

2023-08-17 16:46 UTC, goodroot commented on docs/reference/function/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255` and are stored as `int`. However, some IPv4 Operators allow IPv4 addresses to pass as `string` and contain a subnet and/or n
Ah after rolling through the 3 pages, I think the advice was solid. I'll resolve this one.

2023-08-17 16:46 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +### Return netmask - netmask()
```suggestion
### Return netmask - netmask(string)
```

2023-08-17 16:47 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are stored as `int`, but can be passed as `string`. When passed as `string`, they may contain a subnet mask (`35.24.65.2/16`) or a subnet with a netmask(`2.232/16`). See below to see w
Great! Thank you

2023-08-17 16:51 UTC, allegraharris approved these changes

2023-08-17 16:56 UTC, jerrinot commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
> Within a column, all addresses are stored as a 32-bit int, for example: 255.255.255.255.
I don't get the example. How is `255.255.255.255` related to 32 bits int? It feels unfinished. What is the example supposed to show?

2023-08-17 17:00 UTC, jerrinot commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255`.
I would be explicit about the address `0.0.0.0` being interpreted as `null`. 
_What a strange range! Why not 0.0.0.0?_ <-- This was the first thing on my mind whilst reading this.

2023-08-17 17:01 UTC, allegraharris commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
I'm unsure whether we should specify that it's stored as a 32-bit int because it might just confuse a user because no one thinks of an ip address in terms of an int. E.g., `255.255.255.255` is stored internally as -1. Do you think we should remove the example of the 32-bit int info? @jerrinot

2023-08-17 17:02 UTC, goodroot commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
The maximum statement of an IPv4 address. Between `0.0.0.1-255.255.255.255`.

Would this be better?

```
They are - as one would imagine - very useful when dealing with IP addresses.

Within a column, all addresses are stored as a 32-bit `int`.

IPv4 addresses exist within the range of `0.0.0.1` - `255.255.255.255`.
```

2023-08-17 17:02 UTC, jerrinot commented on docs/reference/operators/ipv4.md
> +When passed, they may contain trailing and leading dots: `...1.1.1.1...`.
do we really want to document this? what is it good for? maybe it could stay as an _undocumented implementation detail_ so we have the freedom to change it if this is not desirable for any reason?

2023-08-17 17:03 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +IPv4 addresses are presented between the range `0.0.0.1 - 255.255.255.255`.
Good call! Adding.

2023-08-17 17:04 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +When passed, they may contain trailing and leading dots: `...1.1.1.1...`.
I can't think of a practical use case other.

If we were voted I'd vote "not document".

2023-08-17 17:05 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +When passed, they may contain trailing and leading dots: `...1.1.1.1...`.
This was implemented because browsers are tolerant of leading and trailing dots. I'm happy to keep/remove from docs

2023-08-17 17:06 UTC, goodroot commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
Or rather:

```
They are - as one would imagine - very useful when dealing with IP addresses.

IPv4 addresses exist within the range of `0.0.0.1` - `255.255.255.255`.

Within a column, all addresses are stored as a `int`.
```

If we'd rather never reference the bits, makes sense to me.

2023-08-17 17:07 UTC, goodroot commented on docs/reference/operators/ipv4.md
> +When passed, they may contain trailing and leading dots: `...1.1.1.1...`.
Huh - TIL! 

Okay, pushed up.

2023-08-17 17:14 UTC, jerrinot commented on docs/reference/operators/ipv4.md
>  ipv4 '44.8.9.10' != ipv4 '6.2.90.1' -> T
not directly related to this PR, but perhaps worth fixing too. 
this section is non-obvious. for 2 reasons:
## the first reason
`ipv4 '44.8.9.10' != ipv4 '6.2.90.1' -> T`
What is `T`? I figured out it's `true`, but it took me some effort to realize it. That's not good. 

Compare IPv4 example:
<img width="508" alt="image" src="https://github.com/questdb/questdb.io/assets/158619/b3d54d36-f0af-4999-ade4-8d551ec7093a">


With an existing example at https://deploy-preview-1877--unruffled-blackwell-31bfb2.netlify.app/docs/reference/operators/comparison/ 
<img width="610" alt="image" src="https://github.com/questdb/questdb.io/assets/158619/aa648f92-46cf-4800-b9ca-a0aa3b8864b4">

Differences: The 2nd example does not force me to think. It's very obvious. Also, it gives me a proper SQL I can actually execute. Instead of an abstract syntax. I think that makes it better documentation. 

## The 2nd reason
How is IP address comparison defined? I am too ignorant to be aware of any IP comparison standard. And my intuition is failing me: `127.0.0.1 > 127.0.1.0` is this `true` or `false`? I am not sure.

2023-08-17 17:16 UTC, goodroot commented on docs/reference/operators/ipv4.md
>  ipv4 '44.8.9.10' != ipv4 '6.2.90.1' -> T
👍 Saved these notes for new PR, as broad pass is needed to address many quality-of-life changes.

Thanks!

2023-08-17 19:02 UTC, jerrinot commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
I would simplify it furher:
```
They are useful when dealing with IP addresses. 
The  IP addresses can be in the range of `0.0.0.1` - `255.255.255.255`. The address - `0.0.0.0` is interpreted as null.
```

2023-08-17 19:49 UTC, goodroot commented on docs/reference/sql/datatypes.md
> +Within a column, all addresses are stored as a 32-bit `int`, for example: `255.255.255.255`.
💥

2023-08-18 06:29 UTC, jerrinot submitted a review, later dismissed
good improvements, thanks to both @allegraharris and @goodroot !

2023-08-18 09:09 UTC, allegraharris submitted a review, later dismissed

2023-08-18 09:09 UTC, allegraharris commented on docs/reference/operators/ipv4.md
> +Takes a `string` argument in the format `22.59.138.9/8`.
I think we should note that we also accept subnet + netmask e.g., `2.2/16'

2023-08-23 18:53 UTC, goodroot commented
@jerrinot Hey! Mind re-approving?

2023-08-29 15:14 UTC, bluestreak01 approved these changes

2023-08-29 15:16 UTC, merged