docs: health monitoring
questdb/questdb.io pull request #248
Opened 2020-12-01 17:59 UTC by bluestreak01

2020-12-01 18:34 UTC, mpsq requested changes
A few changes.
You also need to remove the `package-lock.json` from the PR.

2020-12-01 18:34 UTC, mpsq commented on docs/operations/health-monitoring.md
> +```
You need to set a language otherwise by default it is `questdb-sql`.
In this case, `shell`.

2020-12-01 18:34 UTC, mpsq commented on docs/operations/health-monitoring.md
> +```
Same here (language)

2020-12-01 18:34 UTC, mpsq commented on sidebars.js
> +	"operations/health-monitoring"
Would it be possible to not mix tabs and spaces? This repo uses exclusively spaces, we can add an `.editorconfig` if that makes this easier.

2020-12-01 18:34 UTC, mpsq commented on docs/operations/health-monitoring.md
> +The `min` HTTP server [configuration is documented](reference/configuration.md#minimal-http-server) in the reference section
Would it be possible to format that file with `prettier`?

2020-12-02 12:02 UTC, mpsq requested changes
Change on link

2020-12-02 12:02 UTC, mpsq commented on docs/operations/health-monitoring.md
> +the reference section
```suggestion
The configuration section for the `min` HTTP server is available in the 
[reference section](/docs/reference/configuration#minimal-http-server).
```

A few things about links, please always use absolute (`/`) links, also do not set the file extension `.md`, it is not retained in the URL in production.

2020-12-02 13:44 UTC, bluestreak01 commented on docs/operations/health-monitoring.md
> +the reference section
👍

2020-12-02 14:11 UTC, mpsq approved these changes

2020-12-02 14:11 UTC, merged