docs: Kafka docs page improvements
questdb/questdb.io pull request #267
Opened 2020-12-08 16:48 UTC by bsmth

__Changes:__
* Removed Postgres config section
* Clean up one-liner example for publishing JSON messages with pretty example to demonstrate the schema
* Add better instructions for making `.jar` files available to Kafka

2020-12-08 17:43 UTC, mpsq commented
LGTM

2020-12-09 09:23 UTC, mpsq requested changes
minor change

2020-12-09 09:23 UTC, mpsq commented on docs/third-party-tools/kafka.md
> +```
You need to set a language here, if you omit it, it is by default `questdb-sql`

2020-12-09 10:32 UTC, bsmth commented on docs/third-party-tools/kafka.md
> +```
gotcha, thanks

2020-12-09 10:47 UTC, bluestreak01 submitted a review, later dismissed

2020-12-09 10:52 UTC, mpsq requested changes

2020-12-09 10:52 UTC, mpsq commented on docs/third-party-tools/kafka.md
> +name=local-jdbc-sink
```suggestion
```shell
name=local-jdbc-sink
```

2020-12-09 10:53 UTC, mpsq approved these changes

2020-12-09 10:55 UTC, merged