docs: add Data retention page
questdb/questdb.io pull request #329
Opened 2021-01-22 16:54 UTC by bsmth

__Additions:__
* data retention with examples for generating test data and dropping by date

__CSS Change:__
* Proposed reduction of vertical whitespace to improve readability

2021-01-25 10:17 UTC, bsmth commented
@mpsq there are some style changes here, feedback welcome

2021-01-25 10:50 UTC, mpsq requested changes
minor tweaks

2021-01-25 10:50 UTC, mpsq commented on docs/operations/data-retention.md
> +---
Could you also add that page to the list on "introduction"?

2021-01-25 10:50 UTC, mpsq commented on docs/operations/data-retention.md
> +[designated timestamp](/docs/concept/designated-timestamp) assigned and a
```suggestion
[designated timestamp](/docs/concept/designated-timestamp/) assigned and a
```

2021-01-25 10:50 UTC, mpsq commented on docs/operations/data-retention.md
> +[ALTER TABLE DROP PARTITION](/docs/reference/sql/alter-table-drop-partition)
```suggestion
[ALTER TABLE DROP PARTITION](/docs/reference/sql/alter-table-drop-partition/)
```

2021-01-25 10:53 UTC, bsmth commented
> @mpsq there are some style changes here, feedback welcome

reverted in 62b17e9

2021-01-25 11:24 UTC, bsmth commented on docs/operations/data-retention.md
> +---
done

2021-01-25 12:30 UTC, mpsq submitted a review, later dismissed
LGTM

2021-01-25 15:48 UTC, mpsq approved these changes

2021-01-26 10:29 UTC, bluestreak01 approved these changes

2021-01-26 10:35 UTC, merged