Added .NET Example Code
questdb/questdb.io pull request #340
Opened 2021-01-29 11:03 UTC by TimBo93

Examples for .NET are missing and the required
```
 ServerCompatibilityMode=NoTypeLoading;
```
might be a pitfalf.

2021-01-29 11:03 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/questdb/questdb.io?pullRequest=340) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/questdb/questdb.io?pullRequest=340) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/questdb/questdb.io?pullRequest=340) it.</sub>

2021-01-29 11:20 UTC, bsmth commented
Thanks Tim, added example looks good, we'll enable syntax highlighting for csharp, this can be done after merging though

2021-01-29 12:31 UTC, ideoma commented
ServerCompatibilityMode=NoTypeLoading; is not necessary on latest version in master, incompatibility is fixed

2021-02-02 13:57 UTC, mpsq requested changes

2021-02-02 13:57 UTC, mpsq commented on docs/develop/connect.md
> +  { label: ".NET", value: "csharp" },
```suggestion
  { label: "C#", value: "csharp" },
```

2021-02-02 13:58 UTC, mpsq approved these changes

2021-02-02 14:03 UTC, mpsq commented
@TimBo93 Thanks for the contribution!
@ideoma Would it be possible to test the snippet and confirm that it works before I merge it?

2021-02-02 14:03 UTC, mpsq requested changes
testing

2021-02-02 14:05 UTC, mpsq requested changes
This still needs some work before merging it: 

1. The snippet should be moved to develop/query-data
2. Some of the code in the snippet could be used to add an example to "develop/connect"
3. "C#" in the list of languages should be moved next to "Java"
4. The snippet should run the query "SELECT x FROM long_sequence(5);" like other snippets do, this is easier for the users since they can just copy/paste the code and run it without having to create a schema

2021-02-17 17:07 UTC, mpsq approved these changes

2021-02-17 17:08 UTC, mpsq commented
Thanks to @TimBo93 and @bsmth :tada:

2021-02-17 17:09 UTC, merged