chore: improve readability of TOC in functions pages
questdb/questdb.io pull request #359
Opened 2021-02-08 16:10 UTC by bsmth

__Description:__
* Removed `Description` sections in favor of including this in the top-level description of a function to reduce redundant information
* Replaced section headings with bold text for:
  * Examples
  * Arguments
  * Return Values

2021-02-08 18:13 UTC, mpsq requested changes
minor changes, it looks good otherwise

2021-02-08 18:13 UTC, mpsq commented on docs/reference/function/random-value-generator.md
> +  `NaN` values along with int values. **Arguments:**
```suggestion
  `NaN` values along with int values.
  
  **Arguments:**
```

2021-02-08 18:13 UTC, mpsq commented on docs/reference/function/row-generator.md
> +## Examples
```suggestion
**Examples:**
```

2021-02-09 09:21 UTC, bsmth commented on docs/reference/function/random-value-generator.md
> +  `NaN` values along with int values. **Arguments:**
thanks, good catch

2021-02-09 09:30 UTC, bsmth commented
Closes #345

2021-02-09 09:51 UTC, mpsq approved these changes
lgtm

2021-02-09 09:51 UTC, merged