docs: revision of CREATE TABLE page
questdb/questdb.io pull request #362
Opened 2021-02-10 14:41 UTC by bsmth

__Changes:__
* Readability improvements on the `symbol` type which may have multiple optional parameters passed - this section needs to be easily navigated with attention to the overall document hierarchy.
* Minor typo fixes

2021-02-10 17:30 UTC, mpsq requested changes
Minor typo

2021-02-10 17:30 UTC, mpsq commented on docs/reference/sql/create-table.md
> +now we want to turn this data into time series though ordering trips by
```suggestion
now we want to turn this data into time series through ordering trips by
```

2021-02-10 20:18 UTC, bsmth commented on docs/reference/sql/create-table.md
> +now we want to turn this data into time series though ordering trips by
thanks 👍🏻

2021-02-11 12:30 UTC, mpsq approved these changes

2021-02-11 12:31 UTC, merged