docs: add Slack alerting tutorial from Kovid
questdb/questdb.io pull request #398
Opened 2021-03-10 13:44 UTC by bsmth

__Description:__
This PR adds a tutorial from Kovid Rathee which describes how to set up Slack notifications based on realtime market data via Grafana.

2021-03-11 19:19 UTC, the-sheev requested changes

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +1. Log into Grafana at [localhost:3000](http://localhost:3000) using the default
`Log in to`

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +5. In the **Notification settings** dropdown, check the **Include image**
`enable the` instead of `check the`

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +6. Click **Test** to verify that the configuration is correct and click **Save**
`and click` should become `and then click`

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +- `IS ...` allows specifying a comparison to a value or a range
`to a value or range`

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +In this tutorial, we have learned how Grafana and QuestDB can be quite powerful
`we have learned how` to `we've shown how`

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +[submit a PR](https://github.com/bsmth/questdb-slack-grafana-alerts) if you have
Again: repository on employee's account

2021-03-11 19:19 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +```
Language is not set.

2021-03-11 19:25 UTC, bluestreak01 requested changes

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +```
language type

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +  and configure Slack alerts based on changes in time series data using Grafana
```suggestion
  and configure Slack alerts based on changes in time series data using Grafana.
```

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +title: Realtime stock price alerts using Python, Grafana and QuestDB
```suggestion
title: Real-time stock price alerts using Python, Grafana and QuestDB
```

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +realtime stock prices, but first, we can verify the configuration is correct by
```suggestion
real-time stock prices, but first, we can verify the configuration is correct by
```

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +## Query realtime stock prices
```suggestion
## Query real-time stock prices
```

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +making requests to an API for live market data and query realtime stock prices.
```suggestion
making requests to an API for live market data and query real-time stock prices.
```

2021-03-11 19:25 UTC, bluestreak01 commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +If the markets are open, realtime prices will be sent to QuestDB:
```suggestion
If the markets are open, real-time prices will be sent to QuestDB:
```

2021-03-11 19:32 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +git clone git@github.com:bsmth/questdb-slack-grafana-alerts.git
Could you say why or is this personal preference?

2021-03-11 19:32 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +In this tutorial, we have learned how Grafana and QuestDB can be quite powerful
```suggestion
In this tutorial, we've shown how Grafana and QuestDB can be quite powerful
```

2021-03-11 19:32 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +git clone git@github.com:bsmth/questdb-slack-grafana-alerts.git
I have moved this to a questdb repo

2021-03-11 19:32 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +[list supported of notifiers](https://grafana.com/docs/grafana/latest/alerting/notifications/#list-of-supported-notifiers).
good catch

2021-03-11 19:35 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +questdb_alerts   /app/bin/java --add-export ...   Up      0.0.0.0:8812->8812/tcp, 0.0.0.0:9000->9000/tcp, 9009/tcp
this is verbatim console output on my machine when running `docker-compose up`

2021-03-11 19:36 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +git clone git@github.com:bsmth/questdb-slack-grafana-alerts.git
https is the default for repositories you do not have access to

2021-03-11 19:37 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +questdb_alerts   /app/bin/java --add-export ...   Up      0.0.0.0:8812->8812/tcp, 0.0.0.0:9000->9000/tcp, 9009/tcp
ok

2021-03-11 19:37 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +| `stockListed`     | name of the stock, e.g., `TSLA` for Tesla             |
This is correct in American style guides

2021-03-11 19:37 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +| `stockPrice`      | price of the stock in USD in double                   |
thanks

2021-03-11 19:43 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +| `stockListed`     | name of the stock, e.g., `TSLA` for Tesla             |
Yes but it is widely used without the comma.

2021-03-11 20:02 UTC, the-sheev requested changes

2021-03-11 20:02 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +The next step is to create an incoming webhook in Slack to send alerts as
```suggestion
The next step is to create an incoming webhook in Slack to which send alerts as
```

2021-03-11 20:11 UTC, bsmth commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +The next step is to create an incoming webhook in Slack to send alerts as
This would be wrong. It's correct as it is, or an alternative would be

> The next step is to create an incoming webhook in Slack, to which Grafana sends alerts as HTTP(S) requests.

2021-03-11 20:23 UTC, the-sheev commented on tutorial/2021-03-09-realtime-stock-alerts-python-grafana-questdb.mdx
> +The next step is to create an incoming webhook in Slack to send alerts as
You choose.

2021-03-11 20:35 UTC, the-sheev approved these changes

2021-03-12 09:02 UTC, bluestreak01 approved these changes

2021-03-12 09:02 UTC, merged