docs: clarify use of fill options for returning null values
questdb/questdb.io pull request #400
Opened 2021-03-11 16:09 UTC by bsmth

__Description:__
The documentation showed examples mixing multiple fill options, i.e. the following is not yet supported:

* `FILL(PREV, LINEAR, ...)` - more than one keyword / strategy
* `FILL(123, LINEAR)` - a constant with a keyword
* `FILL(123)` - a constant when there are more than one aggregate columns

Currently, only one fill keyword may be specified and if a constant is provided, a constant value must be specified for each aggregate column:

```
select avg(col1), avg(col2), avg(col3)
FROM table 
SAMPLE BY 1h
FILL(1, 2.5, 100);
```

2021-04-07 09:18 UTC, ideoma approved these changes

2021-04-09 12:01 UTC, ideoma requested changes

2021-04-09 12:04 UTC, bsmth commented on docs/reference/sql/fill.md
> +[coalesce() function](http://localhost:3000/docs/reference/function/conditional/#coalesce)
nice catch!

2021-04-09 12:47 UTC, ideoma approved these changes

2021-04-09 16:57 UTC, tris0laris approved these changes

2021-04-09 16:57 UTC, merged