chore: add DATRON case study
questdb/questdb.io pull request #401
Opened 2021-03-12 18:08 UTC by bsmth

__Description:__
* Adds a DATRON case study
* Improve quote section style on Toggle's case study
* wider jumbotron area for article title on single page

2021-03-15 18:27 UTC, the-sheev requested changes

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +            Wide compatiblility and simple configuration
```suggestion
            Wide compatibility and simple configuration
```

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +            with less hardware, more efficiently.
```suggestion
            with less hardware.
```
is more impressive and reads better.

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +            <img
`InfluxDB line Protocol` should be `InfluxDB line protocol`.

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +            feature addition or a bug fix.
```suggestion
            feature addition or bug fix.
```

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +            The developer and community support meant that questions get
```suggestion
            The developer and community support means that questions get
```

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/toggle.tsx
> +    "Toggle switched from InfluxDB to QuestDB for and benefited from faster queries, massive cost reduction, and performance improvements on ingestion."
```suggestion
    "Toggle switched from InfluxDB to QuestDB and benefited from faster queries, massive cost reduction, and performance improvements on ingestion."
```

2021-03-15 18:27 UTC, the-sheev commented on src/pages/customers.tsx
> +              alt="TODO"
TODO

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/datron.tsx
> +              alt="Chart showing the average transaction duration for QuestDB on a given day"
Wrong.

2021-03-15 18:27 UTC, the-sheev commented on src/pages/case-study/toggle.tsx
>  const Toggle = () => {
Where are this file and the following file displayed? I don't see them when building the project.

2021-03-15 18:50 UTC, bluestreak01 requested changes

2021-03-15 18:50 UTC, bluestreak01 commented on src/pages/case-study/datron.tsx
> +            Wide compatiblility and simple configuration
```suggestion
            Wide compatibility and simple configuration
```

2021-03-15 19:35 UTC, bsmth commented on src/pages/case-study/toggle.tsx
>  const Toggle = () => {
Which files? The case study pages are rendered to `/case-study/datron/` and `/case-study/toggle/`, does that answer the question?

2021-03-15 19:38 UTC, bsmth commented on src/pages/case-study/datron.tsx
> +            <img
Needs to be updated in the diagram also - can do as follow-up

2021-03-16 15:06 UTC, the-sheev approved these changes

2021-03-16 15:33 UTC, bluestreak01 approved these changes

2021-03-16 15:33 UTC, merged