docs: detached partitions must have explicit naming convention
questdb/questdb.io pull request #404
Opened 2021-03-15 18:14 UTC by bsmth

__Description:__
Detached partitions must be named `<partition_name>.detached` before executing SQL to attach.

2021-03-15 18:28 UTC, ideoma approved these changes

2021-03-16 15:38 UTC, bluestreak01 requested changes

2021-03-16 15:38 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
>  ### Examples
should be `##`

2021-03-16 15:40 UTC, bsmth commented on docs/reference/sql/alter-table-attach-partition.md
>  ### Examples
👍🏻

2021-03-17 13:23 UTC, bluestreak01 approved these changes

2021-03-17 13:24 UTC, merged