chore: Add GKE Autopilot tutorial
questdb/questdb.io pull request #407
Opened 2021-03-19 13:25 UTC by bsmth

__Description:__
This tutorial comes courtesy of @yitaek and describes how to run QuestDB on Kubernetes with Prometheus and Valero for automated backups

2021-03-19 13:28 UTC, patrickSpaceSurfer approved these changes

2021-03-19 21:41 UTC, the-sheev requested changes

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +features became available.
```suggestion
features become available.
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +[prometheus community](https://prometheus-community.github.io/helm-charts/):
```suggestion
[Prometheus Community](https://prometheus-community.github.io/helm-charts/):
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +add annotations specify our scrape port. Create another YAML file called
Between `annotations` and `specify our scrape port`.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +  disableDefaultMetrics: trueannotations:
```suggestion
  disableDefaultMetrics: true
  annotations:
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +  prometheus.io/scrape: 'true'
Maybe this line and the next one should be children of `annotations:`.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +  kubectl --namespace default port-forward $POD_NAME 9090
```suggestion
kubectl --namespace default port-forward $POD_NAME 9090
```
Maybe. Or maybe it should be inside the value of `POD_NAME`.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +[Practical monitoring with Prometheus and Grafana](https://yitaek.medium.com/practical-monitoring-with-prometheus-grafana-part-i-22d0f172f993).)
```suggestion
[Practical monitoring with Prometheus and Grafana](https://yitaek.medium.com/practical-monitoring-with-prometheus-grafana-part-i-22d0f172f993).
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +four-part series
```suggestion
four-part series,
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +cluster and integrates with various storage providers (e.g., AWS S3, GCP
```suggestion
cluster and integrates with various storage providers (e.g. AWS S3, GCP
```
The comma kills reading flow for me.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> + — display-name "Velero service account"
```suggestion
  display-name "Velero service account"
```
Maybe?

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +  --format 'value(email)')ROLE_PERMISSIONS=(
```suggestion
  --format="value(email)")
ROLE_PERMISSIONS=(
```
Maybe?

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +gsutil iam ch serviceAccount:$SERVICE_ACCOUNT_EMAIL:objectAdmin gs://${BUCKET}
```suggestion
gsutil iam ch serviceAccount:$SERVICE_ACCOUNT_EMAIL:objectAdmin gs://$BUCKET
```
Maybe this does not need `{}` since it does not have expressions inside.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +Download the service account key and save it as `credential-velero`:
```suggestion
Download the service account key and save it as `credentials-velero`:
```
Like below, I guess.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +Finally, we can create a schedule using a `cron`-like string:
```suggestion
Finally, we can create a schedule using a `cron`-like expression:
```
https://en.wikipedia.org/wiki/Cron#CRON_expression

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +For more information on Valero, my article about
```suggestion
For more information on Velero, [my article about
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +### Valero configuration
```suggestion
### Velero configuration
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +[Disaster recovery on Kubernetes](https://medium.com/dev-genius/disaster-recovery-on-kubernetes-98c5c78382bb)
```suggestion
disaster recovery on Kubernetes](https://medium.com/dev-genius/disaster-recovery-on-kubernetes-98c5c78382bb)
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +features (e.g., replication, high-availability, recovery from snapshot) and
```suggestion
features (e.g. replication, high-availability, recovery from snapshot) and
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +and Velero, we can configure a production-ready QuestDB on Kubernetes. I look
```suggestion
and Velero, we can configure a production-ready QuestDB instance on Kubernetes. I look
```

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +monitoring and ops features.
```suggestion
monitoring and DevOps features.
```
Avoid uncommon abbreviations.

2021-03-19 21:41 UTC, the-sheev commented on tutorial/2021-03-18-questdb-and-prometheus-on-gke-autopilot.mdx
> +  alt="The status dashboard for Kubernetes services in Google Cloud console"
```suggestion
  alt="The status dashboard for Kubernetes services in Google Cloud Console"
```

2021-03-22 13:02 UTC, bluestreak01 approved these changes

2021-03-22 17:20 UTC, merged