Light theme
questdb/questdb.io pull request #669
Opened 2022-01-07 16:47 UTC by argshook

This PR implements light theme

2022-01-10 08:35 UTC, insmac commented
Let's fix the following issues before we roll this PR out, since they effectively block from using the site once you switch to the light theme. 

I wouldn't go very deep on this, just make sure we get proper text colors across.

**Documentation**
<img width="1961" alt="CleanShot 2022-01-10 at 09 21 13 2@2x" src="https://user-images.githubusercontent.com/1871646/148736747-54fe8562-ec1f-4eca-a3ec-8ff6eb68f7f0.png">

**About**
<img width="1961" alt="CleanShot 2022-01-10 at 09 21 01@2x" src="https://user-images.githubusercontent.com/1871646/148736780-93a4b325-a1e3-48d9-bf90-62c87da3142d.png">

**Cloud**
<img width="1955" alt="CleanShot 2022-01-10 at 09 20 28@2x" src="https://user-images.githubusercontent.com/1871646/148736810-b358f07c-146c-4d3f-8740-f4dedd94c218.png">

**Enterprise**
<img width="1959" alt="CleanShot 2022-01-10 at 09 20 41@2x" src="https://user-images.githubusercontent.com/1871646/148737195-bf2006b0-42a5-4934-b5ab-87e37d576bcc.png">

One minor UI issue at the end - let's separate search and theme switcher on mobile:
![CleanShot 2022-01-10 at 09 19 06@2x](https://user-images.githubusercontent.com/1871646/148737332-2c8eb144-c2ff-4ec7-8ac9-e4b717b0773b.png)

2022-01-12 17:03 UTC, bluestreak01 requested changes
website flickers on reload and browser navigation buttons, irrespective of the selected mode (light or dark)

2022-01-13 13:36 UTC, bsmth approved these changes
Looks good, thanks 🙌🏻

2022-01-13 15:21 UTC, bluestreak01 approved these changes

2022-01-13 15:21 UTC, merged