chore: ILP docs refresh
questdb/questdb.io pull request #710
Opened 2022-02-03 10:13 UTC by bsmth

2022-02-05 22:37 UTC, bluestreak01 requested changes

2022-02-07 14:53 UTC, bsmth commented on docs/reference/api/influxdb.md
> +table_name[,symbolset][ columnset] timestamp
done in https://github.com/questdb/questdb.io/pull/710/commits/62638fc465e977636b6ff7cd54ba0c12784b5f89

2022-02-07 14:53 UTC, bsmth commented on docs/reference/api/influxdb.md
> +to ingest data. This enables you to use QuestDB as a replacement for InfluxDB
done in https://github.com/questdb/questdb.io/pull/710/commits/62638fc465e977636b6ff7cd54ba0c12784b5f89

2022-02-07 14:53 UTC, bsmth commented on docs/reference/api/influxdb.md
> +If field values are passed string types, the field values must be double-quoted.
Clarified in https://github.com/questdb/questdb.io/pull/710/commits/62638fc465e977636b6ff7cd54ba0c12784b5f89

2022-02-07 15:45 UTC, bsmth commented on docs/reference/api/influxdb.md
> +### Table schema
added in https://github.com/questdb/questdb.io/pull/710/commits/f9267f62f09b0b798d93addf77ab73031ca9b7c1

2022-02-07 16:10 UTC, glasstiger approved these changes

2022-02-07 16:18 UTC, bluestreak01 requested changes

2022-02-07 16:29 UTC, bluestreak01 requested changes

2022-02-07 16:29 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +| string (not quoted)      | Sensor14                | symbol       | no      | no   | no    | cast | no   | no    | default | no      | no      | no   | no        | no      | no     | no      | cast
not quoted string will not be cast to `string`?

2022-02-07 16:29 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +| float                    | 167, 3.0, -2.31, 1.E+78 | double       | no      | no   | no    | no   | no   | cast  | no      | no      | no      | no   | no        | default | no     | no      | no
we should elaborate what "no" means, this is perhaps error that constitutes malformed input ?

2022-02-07 17:02 UTC, bluestreak01 requested changes

2022-02-07 17:02 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +# buffer size to process messages at one time, cannot be less than measurement size
This comment makes no sense.

```
line.tcp.msg.buffer.size - TCP receive buffer size. It should be big enough to accommodate batches of ILP messages. The size it typically a multiple of `line.tcp.max.measurement.size` and should be a nearest power of 2
```

2022-02-07 17:02 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +#### CPU affinity
I will provide a blurb on how to configure thread model for max throughput

2022-02-07 17:07 UTC, glasstiger commented on docs/reference/api/influxdb.md
> +| float                    | 167, 3.0, -2.31, 1.E+78 | double       | no      | no   | no    | no   | no   | cast  | no      | no      | no      | no   | no        | default | no     | no      | no
yes, "no" means error (exception on the log)

2022-02-07 17:29 UTC, glasstiger commented on docs/reference/api/influxdb.md
> +| string (not quoted)      | Sensor14                | symbol       | no      | no   | no    | cast | no   | no    | default | no      | no      | no   | no        | no      | no     | no      | cast
no, it will fail.
i do not think it will convert to anything.

2022-02-08 11:56 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +| string (not quoted)      | Sensor14                | symbol       | no      | no   | no    | cast | no   | no    | default | no      | no      | no   | no        | no      | no     | no      | cast
we should perhaps add this conversion, otherwise it doesn't make sense

2022-02-08 11:56 UTC, bluestreak01 commented on docs/reference/api/influxdb.md
> +| float                    | 167, 3.0, -2.31, 1.E+78 | double       | no      | no   | no    | no   | no   | cast  | no      | no      | no      | no   | no        | default | no     | no      | no
i mean, we should elaborate in the documentation, not on PR :)

2022-02-09 15:44 UTC, bsmth commented on docs/reference/api/influxdb.md
> +| string (not quoted)      | Sensor14                | symbol       | no      | no   | no    | cast | no   | no    | default | no      | no      | no   | no        | no      | no     | no      | cast
added in https://github.com/questdb/questdb.io/pull/710/commits/1de86189249f18b9f5e331c87674334548230e9a

2022-02-09 15:44 UTC, bsmth commented on docs/reference/api/influxdb.md
> +| float                    | 167, 3.0, -2.31, 1.E+78 | double       | no      | no   | no    | no   | no   | cast  | no      | no      | no      | no   | no        | default | no     | no      | no
added in https://github.com/questdb/questdb.io/pull/710/commits/1de86189249f18b9f5e331c87674334548230e9a

2022-02-09 15:44 UTC, bsmth commented on docs/reference/api/influxdb.md
> +[capacity planning section](/#capacity-planning).
fixed in https://github.com/questdb/questdb.io/pull/710/commits/1de86189249f18b9f5e331c87674334548230e9a

2022-02-09 15:46 UTC, bsmth commented on docs/reference/api/influxdb.md
> +### Constructing messages
Going to omit this change for now as it would require a full document rewrite; we heavily rely on examples to illustrate expected message format.

2022-02-09 15:46 UTC, bsmth commented on docs/reference/api/influxdb.md
> +#### Committing records
removed in https://github.com/questdb/questdb.io/pull/710/commits/1de86189249f18b9f5e331c87674334548230e9a

2022-02-09 15:46 UTC, bsmth commented on docs/reference/api/influxdb.md
> +# buffer size to process messages at one time, cannot be less than measurement size
fixed in https://github.com/questdb/questdb.io/pull/710/commits/1de86189249f18b9f5e331c87674334548230e9a

2022-02-10 11:19 UTC, glasstiger commented on docs/reference/api/influxdb.md
> +| string (not quoted)      | Sensor14                | symbol       | no      | no   | no    | cast | no   | no    | default | no      | no      | no   | no        | no      | no     | no      | cast
working on this, STRING column will take any ILP type.
doc can be prepared with that in mind.
updated the doc: [ILP type conversions](https://docs.google.com/spreadsheets/d/19wRfLNUwESzVG_ubf1-BzGuxb3fdFEXCY2lMdkagPGw/edit#gid=0)

2022-02-18 18:33 UTC, closed without merging