feat(docs): document unhandled error detection in health check endpoint and new metrics
questdb/questdb.io pull request #728
Opened 2022-02-16 06:56 UTC by puzpuzpuz

Follow-up for this core PR: https://github.com/questdb/questdb/pull/1872

2022-02-16 20:15 UTC, bluestreak01 requested changes

2022-02-16 20:15 UTC, bluestreak01 commented on docs/operations/health-monitoring.md
> +When metrics subsystem is [enabled](/docs/third-party-tools/prometheus/) on the
it would be better to link this to an anchor: /docs/third-party-tools/prometheus/#scraping-prometheus-metrics-from-questdb

to direct user exactly where promethius metrics are enabled

2022-02-17 06:41 UTC, puzpuzpuz commented on docs/operations/health-monitoring.md
> +When metrics subsystem is [enabled](/docs/third-party-tools/prometheus/) on the
Changed in 05d0220eff47ead44cbff2eba50f2d2854a37b4a

2022-02-18 18:34 UTC, bluestreak01 approved these changes

2022-02-21 15:41 UTC, merged