feat(sql): Add support for dropping symbol column index
questdb/questdb.io pull request #876
Opened 2022-06-02 12:10 UTC by marregui

Closes https://github.com/questdb/questdb/issues/2148
Documents https://github.com/questdb/questdb/pull/2183

2022-06-02 21:36 UTC, bluestreak01 requested changes

2022-06-02 21:36 UTC, bluestreak01 commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +![Flow chart showing the syntax of the ALTER TABLE keyword](/img/docs/diagrams/alterTable.svg)
this diagram feels misplaced, pls check the preview

2022-07-14 07:58 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +Removes and existing index from a column of type `symbol`.
done

2022-07-14 07:58 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +![Flow chart showing the syntax of the ALTER TABLE keyword](/img/docs/diagrams/alterTable.svg)
I have regenerated the image to make it clear

2022-08-08 14:45 UTC, bziobrowski approved these changes

2022-08-09 12:04 UTC, puzpuzpuz commented
Would be great to merge this one. We have this feature in place for a while, but not having it in docs means that it stays under the radar for our users.

2022-08-10 08:51 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +
hola, nope. This operation is equivalent to `update table tab column=column` where column is a symbol column that has an index before the operation, an no index afterwards. Readers of the table might be using the index in txn A, and they can happily carry on doing that while a writer creates txn B containing the new version of the column, minus the index (metadata is set to not have index, and the files are not copied across to the newer version).

2022-08-10 09:02 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +
I have amended the documentation to explain this, I am sure there will be readers wondering.

2022-08-10 09:04 UTC, marregui commented
ready for review

2022-08-10 09:58 UTC, puzpuzpuz commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +This operation is equivalent to `update table tab set column=column`, where
```suggestion
This operation is equivalent to `UPDATE tab SET column = column`, where
```

2022-08-10 09:59 UTC, puzpuzpuz commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +complete, the SQL optimizer will stop using the index for SQL executions and
nit: "engine" is better fit here
```suggestion
complete, the SQL engine will stop using the index for SQL executions and 
```

2022-08-10 09:59 UTC, puzpuzpuz commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +afterwards. Readers of the table might be using the index in txn A, and they
We should be using "transaction" instead of the in-house "txn"

2022-08-10 10:05 UTC, amyshwang requested changes
Minor editorial review.

2022-08-10 10:05 UTC, amyshwang commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +afterwards. Readers of the table might be using the index in txn A, and they
Is this a file name? Should it be:
```suggestion
afterwards. Readers of the table might be using the index in `txn A`, and they
```

Applies to later cases too.

2022-08-10 10:05 UTC, amyshwang commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +column in txn A (we use hardlinks internally to avoid an actual copy operation
```suggestion
column in txn A (QuestDB uses hardlinks internally to avoid an actual copy operation 
```

2022-08-10 10:05 UTC, amyshwang commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +all its associated files are deleted.
```suggestion
Removing an index is an atomic, non-blocking, and non-waiting operation. Once
the operation is completed, the SQL optimizer stops using the index for SQL executions and 
all its associated files are deleted.
```

2022-08-10 11:07 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +This operation is equivalent to `update table tab set column=column`, where
I have taken this approach, except I am not going to link UPDATE. This drop index op is similar to update, but not the same, so linking to update might distract the reader?

2022-08-10 11:08 UTC, marregui commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +afterwards. Readers of the table might be using the index in txn A, and they
txn -> transaction, so now making it stand out makes less sense.

2022-08-18 14:42 UTC, amyshwang requested changes
A small typo!

2022-08-18 14:42 UTC, amyshwang commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +Where `column` is a symbol column that has an index before the operation, an no
```suggestion
Where `column` is a symbol column that has an index before the operation, and no 
```

2022-08-18 14:42 UTC, amyshwang commented on docs/reference/sql/alter-table-alter-column-drop-index.md
> +and they can carry on doing so while a writer creates transaction B containing the
```suggestion
in the meantime, a writer creates transaction B containing the 
```
I am not sure about this but in the original version, it is not super clear who "they" are (readers?).

2022-08-26 08:02 UTC, amyshwang approved these changes
Ready to be merged.

2022-09-06 23:00 UTC, bluestreak01 approved these changes

2022-09-06 23:00 UTC, merged