chore(docs) Adding known issue for Grafana alert query(#917)
questdb/questdb.io pull request #919
Opened 2022-06-29 12:10 UTC by amyshwang

Addressing a few queries on Slack and Stackoverflow, this commit adds a workaround for alert query.
Corresponding tutorial has a note added linking to the new section too.

Adding TBD for Grafana GH issue which Andrey will create.

2022-06-29 12:23 UTC, argshook requested changes

2022-06-29 12:23 UTC, argshook commented on tutorial/2020-10-19-grafana.mdx
> +For existing Grafana query known issue, see [Known issue](/third-party-tools/grafana/#known_issue)
the `#hash-link` should be in the [`kebab-case`](https://en.wikipedia.org/wiki/Letter_case#Kebab_case). `hash-link` should have the same characters as in the header its linking to.

For example, a heading like
```
## Known issues
```

can be linked with `#known-issues`

```suggestion
For existing Grafana query known issue, see [Known issue](/docs/third-party-tools/grafana/#known-issues)
```

2022-06-29 12:23 UTC, argshook commented on tutorial/2020-10-19-grafana.mdx
> +For Grafana known issues and workaround, see [Known issue](/docs/third-party-tools/grafana).
```suggestion
For Grafana known issues and workaround, see [Known issue](/docs/third-party-tools/grafana#known-issues).
```

2022-06-29 12:32 UTC, amyshwang commented on tutorial/2020-10-19-grafana.mdx
> +For Grafana known issues and workaround, see [Known issue](/docs/third-party-tools/grafana).
Tried this locally but the page is not found.
```For Grafana known issues and workaround, see [Known issue](/docs/third-party-tools/grafana#known-issues).
```
Is there anything wrong in my target?
`## Known issues`

Also, I have removed the note block but the local build is still:
<img width="474" alt="image" src="https://user-images.githubusercontent.com/107401731/176436935-d7b277a3-6be8-4283-99af-29602fde2f41.png">

2022-06-29 13:48 UTC, argshook commented on tutorial/2020-10-19-grafana.mdx
> +For existing Grafana query known issue, see [Known issue](/docs/third-party-tools/grafana/#known-issues)
oops, my mistake in the previous suggestion :facepalm:

there should be no forward slash between URL and hash, pardon

```suggestion
For existing Grafana query known issue, see [Known issue](/docs/third-party-tools/grafana#known-issues)
```

2022-06-29 15:05 UTC, puzpuzpuz commented on docs/third-party-tools/grafana.md
> +SELECT sum(users) as users,
I'd better use one of the queries from the Grafana tutorial or a query on the `trades` table rather than a query reported by one of the users.

2022-06-29 15:05 UTC, puzpuzpuz commented on tutorial/2020-10-19-grafana.mdx
> +For Grafana known issues and workaround, see [Known issue](/docs/third-party-tools/grafana#known-issues).
nit: do we need two identical notes with the link to the Known issues section?

2022-06-29 15:05 UTC, puzpuzpuz commented on docs/third-party-tools/grafana.md
> +For Grafana alert queries, the macro `$__timeFilter(timestamp)` generates timestamp with nanosecond precision, while the expected precision is millisecond precision. As a result, the alert queries ar
```suggestion
For alert queries generated by certain Grafana versions, the macro `$__timeFilter(timestamp)` produces timestamps with nanosecond precision, while the expected precision is millisecond precision. As a result, the alert queries are not compatible with QuestDB and lead to an `Invalid date` error. To resolve this, we recommend the following workaround:
```

2022-06-29 15:59 UTC, javier commented on docs/third-party-tools/grafana.md
> +SELECT sum(users) as users,
Agree with Andrey. Adding the same query we had above in the page but with this filter

```
SELECT
  pickup_datetime AS time,
  avg(trip_distance) AS distance
FROM taxi_trips
WHERE
pickup_datetime BETWEEN cast($__unixEpochFrom()*1000000L as timestamp) and cast($__unixEpochTo()*1000000L as timestamp)
```

2022-06-29 17:30 UTC, puzpuzpuz approved these changes
Left a couple of nits

2022-06-29 17:30 UTC, puzpuzpuz commented on tutorial/2020-10-19-grafana.mdx
> +For existing Grafana query known issue, see [Known issue](/docs/third-party-tools/grafana/#known-issues)
```suggestion
For existing Grafana query known issue, see [Known issue](/docs/third-party-tools/grafana/#known-issues).
```

2022-06-29 17:30 UTC, puzpuzpuz commented on docs/third-party-tools/grafana.md
> +```
```suggestion
```questdb-sql
```

2022-06-30 12:56 UTC, argshook approved these changes

2022-06-30 14:03 UTC, javier approved these changes

2022-06-30 14:04 UTC, merged