feat: Docs for Java client
questdb/questdb.io pull request #945
Opened 2022-07-18 12:31 UTC by jerrinot

2022-07-19 12:54 UTC, amyshwang requested changes
It's likely that I misunderstand some stuff and mis-interpret things. We could discuss together too.

Some general concept I am not sure:

* Sender: the sender? a sender? Sender? How many could there be?
* Client: I am guess that it should be a/the client.

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +This configuration also works with [QuestDB Cloud](https://questdb.io/cloud/). If you are using a self-managed QuestDB
Should we hide this for later when Cloud is launch?

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +add all remaining columns
I'd consider use a list.
```suggestion
4. Use the following options to add all the remaining columns:
    * `stringColumn(CharSequence, CharSequence)`
    * `longColumn(CharSequence, long)`
     * `doubleColumn(CharSequence, double)`
     * `boolColumn(CharSequence, boolean)`
     * `timestampColumn(CharSequence, long)`

```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +5. Use `#t(long)` to finish a row with an explicit timestamp. Alternatively, you can use `atNow()` which will add
I'd use present tense. 
```suggestion
5. Use `#t(long)` to finish a row with an explicit timestamp. Alternatively, you can use `atNow()` which adds
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +7. Go to the step no. 2 to start a new row
Step two is about selecting a table? I am not sure I can follow the instructions here...

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +1. Create a client instance via `Sender.builder()`
Here and the rest for the numbered list: I'd add full stops at the end of a complete sentence.

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +## General Usage Pattern
Sentense case:
```suggestion
## General usage pattern
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +## Designated Timestamp Considerations
```suggestion
## Designated timestamp considerations
```

I think sentence case is the norm in our website.

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +a specific timestamp then use `at(long)` instead of `atNow()`.
```suggestion
To assign a timestamp to a row, a client has the following options:

* Assign a [designated timestamp](/docs/concept/designated-timestamp/) explicitly
* Instruct a QuestDB server to automatically assign a timestamp upon receiving a row from the client. 

The code samples above uses QuestDB to assign timestamp automatically: `atNow()` instructs the server to assign a timestamp by using a local wall-clock. 
To assign a specific timestamp, use `at(long)` instead of `atNow()`. 
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +See [this guide](/docs/guides/out-of-order-commit-lag) for more informations
```suggestion
See [Out-of-order commit lag](/docs/guides/out-of-order-commit-lag) for more informations.
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +for more details.
```suggestion
Please note that he client does not interpret the timestamp in any way. It merely passes the timestamp
to a server, and it is up to a server to interpret the timestamp. 
The default behavior of a QuestDB server is to treat the timestamp as a number of nanoseconds since 1st Jan 1970 UTC. See [Timestamps](/docs/develop/insert-data/#timestamps) for more details.   
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +the client to authenticate.
```suggestion
This sample configures a client to use TLS encryption for a connection to a QuestDB server. It also instructs
the client to authenticate.  
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +
```suggestion

By default, QuestDB's engine treats a designated timestamp as nanoseconds, but this does not mean that `System.nanoTime()`  can be used to get the current time and pass it to `at(long)`. 
`System.nanoTime()` is only useful for measuring elapsed time,  and it is not related to any notion of system or wall-clock time.   

```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +its own Sender instance. You can also use an object pool to re-use Senders.
```suggestion
- Sender objects are not thread-safe. For multiple threads to send data to QuestDB, each thread should have
its own Sender instance. An object pool can also be used to re-use Senders.
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +thus you can use the try-with-resource pattern to make sure the Sender is closed.
```suggestion
- The Sender objects have to be closed after they are no longer in use. The Sender implements the `java.lang.AutoCloseable` interface, and therefore the try-with-resource pattern can be used to ensure that the Sender is closed. 
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +full yet.
The first part (Client internally buffers row data and sends them to a server in batches when the buffers fill up. ): is it a default setting or if a user configures this way?I am guess the latter.
Also there are more than one buffers? ("when the buffers fill up).
```suggestion
- A client can be configured to buffer row data internally and sends them to a server in batches when the buffers are full.  This configuration improves
performance significantly, but it also means that during a period of quiescence, some written
rows may be retained in the buffers and are not sent  to a server until the buffers are full [TBD buffer or buffers]. The function `flush()` can be called to force sending internal buffers to a server, even when the buffers are not full yet.
```

2022-07-19 12:54 UTC, amyshwang commented on docs/reference/clients/overview.md
> +favourite language!
I tend to use US English for tech content:
```suggestion
favorite language! 
```

2022-07-19 13:27 UTC, jerrinot commented on docs/reference/clients/overview.md
> +favourite language!
I'm happy I can write in _some_ English! :-DD
so thanks for catching it, I will change it.

2022-07-19 13:37 UTC, jerrinot commented on docs/reference/clients/java_ilp.md
> +1. Create a client instance via `Sender.builder()`
that's one thing I wanted to ask you. I'm never sure whether full stops should be at the end of an item or not. so now I know. I will know it. at least some time. thank you!

2022-07-19 14:54 UTC, jerrinot commented
ad Sender/sender/Senders/client/clients: The overall solution is a client. Client is a general concept, not specific to QuestDB at all: You have a server and want to pass some data from a business application to a server. That's what clients are for. 

In our case, a business application's main interface to interact with QuestDB ILP client is called `Sender`.  There is a single interface called `Sender`, but a business application can and will create multiple instances of this interface. 

I know it sounds complicated. Is there any specific area you are thinking about changing? Or is it just the general inconsistency in terminology you would like to fix?

2022-07-19 16:09 UTC, argshook commented on docs/reference/clients/overview.md
> +- **.NET**:
is there a reason to have `C#` and `.NET` separately? They link to the same place

2022-07-21 13:00 UTC, amyshwang requested changes
One minor change required and one comment/observation!

2022-07-21 13:31 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +This configuration also works with [QuestDB Cloud](https://questdb.io/cloud/). If you are using a self-managed QuestDB
Let's stick to the current version then :)

2022-07-21 13:38 UTC, amyshwang commented on docs/reference/clients/java_ilp.md
> +## Other Considerations
```suggestion
## Other considerations
```
Sorry I missed this.

2022-07-21 13:38 UTC, amyshwang commented on docs/reference/clients/overview.md
> +title: Clients Overview
```suggestion
title: Clients overview
```

2022-07-21 13:55 UTC, amyshwang approved these changes
Editorial review completed.

2022-07-21 13:57 UTC, merged