docs: add document for 'substring' function
questdb/questdb.io pull request #963
Opened 2022-07-27 11:49 UTC by HeZean

ref: questdb/questdb#2251

2022-08-04 15:21 UTC, amyshwang requested changes
Thank you for the contribution! I have a couple of comments and I hope it makes sense!

2022-08-04 15:21 UTC, amyshwang commented on docs/reference/function/text.md
> +returns `null`.
```suggestion
Returns a string with the extracted characters. If any part the arguments is `null`,
the function returns `null`.
```

2022-08-04 15:21 UTC, amyshwang commented on docs/reference/function/text.md
> +`length + start` if the end position is greater than 1, otherwise empty string.
-5+9=4 but the output stops at position 3? I may have missed something but having played around I observes the  behaviours:

```suggestion
If the `start` argument is negative, the output depends on the value of `start+length`:
- If `start+length` is greater than 1, the substring stops at position `start+length - 1`.
- If `start+length` is zero, the output is empty string.
- If `start+length` is less than zero, the output is `null`.
```
And in this way the example makes sense.

2022-08-04 15:25 UTC, HeZean commented
@amyshwang thanks a lot, that did make the doc easier to understand

2022-08-04 15:26 UTC, HeZean commented on docs/reference/function/text.md
> +`length + start` if the end position is greater than 1, otherwise empty string.
well, characters here are 1-indexed

2022-08-04 15:46 UTC, HeZean commented
Hi @amyshwang, could you please help to check the CI failings? I checked the log but didn't get the point.

2022-08-05 14:55 UTC, amyshwang commented
It is probably a known problem in our checks. Let me re-trigger.

2022-08-05 15:12 UTC, amyshwang approved these changes
Thank you for your contribution :)

2022-08-05 15:19 UTC, merged