docs: Add Java example ILP authentication
questdb/questdb.io pull request #966
Opened 2022-08-02 14:10 UTC by jerrinot

Also: Moved the nodejs example to the last tab,
because the example does not use the nodejs client
and the code with row sockets is long and scary.

2022-08-23 07:34 UTC, amyshwang requested changes

2022-08-23 07:34 UTC, amyshwang commented on docs/reference/api/ilp/authenticate.md
> +
Maybe adding the URL to the Java github here as a comment, like the one in Python?

2022-08-23 07:34 UTC, amyshwang commented on docs/reference/api/ilp/authenticate.md
> +                    .symbol("born", "Austrian Empire")
I don't understand enough to tell but this seems to be very different from the examples in other language. Does it matter? Other language does not use this dummy names?

2022-08-23 11:36 UTC, jerrinot commented on docs/reference/api/ilp/authenticate.md
> +                    .symbol("born", "Austrian Empire")
I will have at the other languages and will make it consistent. thanks for catching it!

2022-08-24 11:41 UTC, jerrinot commented on docs/reference/api/ilp/authenticate.md
> +
I think it makes sort of sense for Python, because https://github.com/questdb/py-questdb-client is a repo with Python client and Python client only. readme of the repo has instructions specific to Python client. There is nothing else. 

But https://github.com/questdb/questdb is both server and a client. Client is only a small part for the repo. So I don't think linking from this place makes much sense. What would be the use-case?

2022-08-24 13:00 UTC, amyshwang commented on docs/reference/api/ilp/authenticate.md
> +
You're right - maybe a link to /docs/reference/clients/java_ilp?

2022-08-25 11:40 UTC, jerrinot commented on plugins/remote-repo-example/index.js
> +  "questdb/c-questdb-client/auth-example",
this is just temporary, to see the effect before corresponding PRs are merged

2023-02-22 10:27 UTC, amyshwang commented
SHould I close this for now?

2023-02-27 08:25 UTC, jerrinot commented
closing a stale PR, will send a new one

2023-02-27 08:25 UTC, closed without merging