chore(doc): added section on copy command to "Importing data in bulk …
questdb/questdb.io pull request #967
Opened 2022-08-03 15:36 UTC by bziobrowski

…via CSV" page

2022-08-04 09:12 UTC, amyshwang requested changes
I can make all the small changes but L150 needs some confirmation, thanks!

2022-08-04 09:12 UTC, amyshwang commented on docs/guides/importing-data.md
> +It's possible to choose a different location via  `cairo.sql.copy.work.root` setting.
Are there two settings, or should it be:
```suggestion
It's possible to choose a different location via  `cairo.sql.copy.root` setting.
```

2022-08-04 09:12 UTC, amyshwang commented on docs/guides/importing-data.md
> +
I am migrating this to the COPY page so I think this can go?

2022-08-04 09:12 UTC, amyshwang commented on docs/guides/importing-data.md
>  ## Large datasets with out-of-order data
I will move this to the start of the whole page as this is the preferred way?

2022-08-04 10:15 UTC, amyshwang commented on docs/guides/importing-data.md
> +It's possible to choose a different location via  `cairo.sql.copy.work.root` setting.
Pretty sure it should be `cairo.sql.copy.root` based on the configuration page https://questdb.io/docs/reference/configuration.

2022-08-05 08:26 UTC, bziobrowski commented on docs/guides/importing-data.md
> +It's possible to choose a different location via  `cairo.sql.copy.work.root` setting.
cairo.sql.copy.work.root is a new setting that allows user to choose different location for temporary import files . 

For example - if user imports from csv on a temporarily attached FS (filesystem) he/she would want to set work.root to some location on the same FS as target database. If work.root is on the same FS astarget database then files can be moved (which is a small metadata change), otherwise files need to be copied (and that might take time for big files).

2022-08-05 08:26 UTC, bziobrowski commented on docs/guides/importing-data.md
>  ## Large datasets with out-of-order data
👍

2022-08-05 09:02 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +Import status table contains only coarse grained, top-level data. Import phase run times vary a lot (e.g. partition_import often takes 80% of the whole run time), and therefore the log file provides
```suggestion
Import status table contains only coarse grained, top-level data. Import phase run times vary a lot (e.g. `partition_import` often takes 80% of the whole import execution time), and therefore the server log provides an alternative to follow more details of import:
```

2022-08-05 09:02 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +## INSERT: large datasets with out-of-order data (superseded by COPY)
nit: I'd better place an info panel here suggesting users to use COPY instead of the REST API for large O3 files.

2022-08-05 10:35 UTC, bziobrowski commented on docs/guides/importing-data.md
> +It quickly returns a hexadecimal import id of asynchronous import process running in the background:
import is repeated a bit later  in the same line so 'returns id of' should suffice .

2022-08-05 10:38 UTC, bziobrowski commented on docs/guides/importing-data.md
> +select * from sys.text_import_log where id = '55020329020b446a' order by ts desc
Why 'sys.text_import_log' ? It's not really correct sql . Did you mean "sys.text_import_log" ?

2022-08-05 11:27 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +select * from sys.text_import_log where id = '55020329020b446a' order by ts desc
> It's not really correct sql

We support this flavor and tend to use it in the docs.

2022-08-05 13:19 UTC, amyshwang commented on docs/guides/importing-data.md
> +It's possible to choose a different location via  `cairo.sql.copy.work.root` setting.
Thanks - updated.

2022-08-05 13:21 UTC, amyshwang commented on docs/guides/importing-data.md
> +## INSERT: large datasets with out-of-order data (superseded by COPY)
I will add it to the REST API section.

2022-08-05 15:20 UTC, puzpuzpuz approved these changes
Left a couple of minor comments. LGTM

2022-08-05 15:20 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +Importing into existing partitioned tables containing data is not yet supported .
Redundant space:
```suggestion
Importing into existing partitioned tables containing data is not yet supported. 
```

2022-08-05 15:20 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +This location is used for storing temporary files like indexes or temporary partitions. It is possible to choose a different temporary storage location via  `cairo.sql.copy.work.root` setting.
```suggestion
This location is also used for storing temporary files like indexes or temporary partitions. It is possible to choose a different temporary storage location via  `cairo.sql.copy.work.root` setting.
```

2022-08-05 15:36 UTC, amyshwang approved these changes
All comments addressed.

2022-08-05 17:46 UTC, bluestreak01 requested changes
REST API is also superseded by `COPY`.

There are three methods:
- COPY (new)
- REST
- INSERT

REST and INSERT are both superseded and should be labelled consistently. INSERT is labelled in title, REST in a note

2022-08-05 17:59 UTC, bluestreak01 commented
Please consider the following:
- advising user of using separate disks
- advising user of IOPS requirements
- advising user of relevant database configuration (properties to set, how to set them, what is the default behaviour, why?)
- consider numbering steps pointing steps that could be recurrent (schema, formats)
- describe what happens when table is missing (partition requirement) or link to the information
- describe troubleshooting (cannot find file etc)
- add example of how to create small file (head command)
- add examples on how to drop table, or truncate table etc

Since this is a guide - it should be unambiguous, we should not encourage user to use anything other than the new copy

2022-08-08 13:14 UTC, amyshwang commented on docs/guides/importing-data.md
> +| cairo.sql.copy.max.index.chunk.size | 100MiB  | Maximum size of index chunk file used to limit total memory requirements of import . Indexing phase should use roughly threads_count * cairo.sql.copy
Should we list the property keys here only and add the details to the main config page?
https://questdb.io/docs/reference/configuration

2022-08-08 13:14 UTC, amyshwang commented on docs/guides/importing-data.md
> +#### I'm getting "[2] could not open read-only [file=C:\path\to\import.csv]" error message
```suggestion
#### I'm getting "[1] could not open read-only [file=C:\path\to\import.csv]" error message
```

2022-08-08 13:14 UTC, amyshwang commented on docs/guides/importing-data.md
> +#### I'm getting "[2] could not open read-only [file=C:\path\to\import.csv]" error message
I mean, [1] is what I got...

2022-08-08 13:14 UTC, amyshwang commented on docs/guides/importing-data.md
> +
Adding notes for Mac OS user: to save the file outside of /Users to avoid permission issues.

2022-08-08 13:19 UTC, bziobrowski commented on docs/guides/importing-data.md
> +#### I'm getting "[2] could not open read-only [file=C:\path\to\import.csv]" error message
The error number within square brackets depends on the filesystem and could be any number .

2022-08-08 13:20 UTC, bziobrowski commented on docs/guides/importing-data.md
> +| cairo.sql.copy.max.index.chunk.size | 100MiB  | Maximum size of index chunk file used to limit total memory requirements of import . Indexing phase should use roughly threads_count * cairo.sql.copy
It might make sense to keep them in both places without user having to jump between pages . @bluestreak01  ?

2022-08-08 13:36 UTC, amyshwang commented on docs/guides/importing-data.md
> +| cairo.sql.copy.max.index.chunk.size | 100MiB  | Maximum size of index chunk file used to limit total memory requirements of import . Indexing phase should use roughly threads_count * cairo.sql.copy
Maybe create a separate table in config for bulk import settings, and link from the current guide to that section? Duplicating content is not the best practice...

2022-08-08 14:20 UTC, bziobrowski commented on docs/guides/importing-data.md
> +
Did you add something here ?

2022-08-08 14:51 UTC, amyshwang commented on docs/guides/importing-data.md
> +
Added to COPY ref in [5692b75](https://github.com/questdb/questdb.io/pull/967/commits/5692b7545b3e22b16b8a4f8811c179033b498fed)

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +- An ordered table may be created by setting `commitLag` and `maxUncommittedRows` via
What do we mean here by "ordered table"? The text also suggests that an "ordered table" can be only created via REST API?

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +To get best performance, temporary import files (governed by `cairo.sql.copy.work.root` setting) should be set to the same filesystem as the database data files.
The previous paragraph started with "To optimize performance". This one starts with "To get best performance", so probably we can merge them.

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +Please set `cairo.iouring.enabled` setting to false, restart QuestDB instance, and try again.
```suggestion
Please set `cairo.iouring.enabled` setting to `false`, restart QuestDB instance, and try again. 
```

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +SELECT * FROM sys.text_import_log LIMIT -10;
nit: we should suggest users to filter the table via a known import id instead of LIMIT -10

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/reference/configuration.md
> +| cairo.sql.copy.queue.capacity       | 32      | Size of copy task queue. Should be increased if there's more than 32 import workers .
```suggestion
| cairo.sql.copy.queue.capacity       | 32      | Size of copy task queue. Should be increased if there's more than 32 import workers.                                                                                                                |
```

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/reference/configuration.md
> +| cairo.iouring.enabled               | true    | Enable or disable io_uring implementation . Can be used to switch it off if there's a kernel bug affecting it.
```suggestion
| cairo.iouring.enabled               | true    | Enable or disable io_uring implementation. Applicable to newer Linux kernels only. Can be used to switch io_uring interface usage off if there's a kernel bug affecting it.                                                                                        |
```

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/reference/configuration.md
> +| cairo.sql.copy.max.index.chunk.size | 100MiB  | Maximum size of index chunk file used to limit total memory requirements of import . Indexing phase should use roughly threads_count * cairo.sql.copy
```suggestion
| cairo.sql.copy.max.index.chunk.size | 100m  | Maximum size of index chunk file used to limit total memory requirements of import. Indexing phase should use roughly thread_count * cairo.sql.copy.max.index.chunk.size of memory.               |
```

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/reference/configuration.md
> +| cairo.sql.copy.work.root            | null    | Temporary import file directory . Same as `cairo.sql.copy.root` if not set explicitly.
```suggestion
| cairo.sql.copy.work.root            | null    | Temporary import file directory. Same as `cairo.sql.copy.root` if not set explicitly.                                                                                                                |
```

2022-08-08 14:52 UTC, puzpuzpuz commented on docs/reference/sql/copy.md
> +For Mac OS users, using a directory under /Users may prevent import due to permission problem. It is preferable to save the CSV file in a folder outside of the /Users tree and set the root directory
```suggestion
For Mac OS users, using a directory under `/Users` may prevent import due to permission problem. It is preferable to save the CSV file in a folder outside of the `/Users` tree and set the root directory accordingly.
```

2022-08-09 08:49 UTC, bziobrowski commented on docs/guides/importing-data.md
'input file analysis' doesn't create file but once could say that it's created in 'analyze_file_structure' import phase . 
Maybe this would look better : 
'QuestDB analyzes input file, detects schema and creates target table .`

2022-08-09 08:51 UTC, bziobrowski commented on docs/guides/importing-data.md
> +
'input file analysis' doesn't create file but once could say that it's created in 'analyze_file_structure' import phase .
Maybe this would look better :
'QuestDB analyzes input file, detects schema and creates target table .`

2022-08-09 08:53 UTC, bziobrowski commented on docs/reference/sql/copy.md
>    - If the target table does not exist, both `TIMESTAMP` and `PARTITION BY` options must be defined to create a partitioned table. The `PARTITION BY` value should not be `NONE`.
Parallel import will return error if target table is not empty . We don't support it yet .

2022-08-09 08:59 UTC, bziobrowski commented on docs/guides/importing-data.md
> +
successful rate -> success rate ?

2022-08-09 09:02 UTC, bziobrowski commented on docs/guides/importing-data.md
> +
"Extract the first 1000 lines of the table" and 
"Extract from the large table a smaller dataset"
should mention file instead of table .

I feel one of them can be removed because they're almost the same .

2022-08-09 09:04 UTC, bziobrowski commented on docs/guides/importing-data.md
> +
Checking -> Check ?

2022-08-09 09:07 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +For third-arty cloud providers, the fastest source option for the import is NVME disks.
```suggestion
For third-party cloud providers, the fastest source option for the import is an NVMe SSD.
```

2022-08-09 09:08 UTC, bziobrowski commented on docs/guides/importing-data.md
> -timestamp format, this may be included with the call as follows:
There are : missing before excerpts and . at end of sentences below .

2022-08-09 09:09 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +If the user is familiar with QuestDB data type, the target table can be created manually:
```suggestion
If the user is familiar with QuestDB data types, the target table can be created manually:
```

2022-08-09 09:12 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +| 2022-08-03T15:00:40.907224Z | 42d31603842f771a | weather_unordered | weather1mil.csv | null  | started  | null    | null         | null          | 0      |
Where do `weather_unordered` and `weather1mil.csv` come from? All examples seem to use different table and file names.

2022-08-09 09:13 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +## Monitoring the log
nit: Should we call it "Monitoring the import"?

2022-08-09 09:17 UTC, amyshwang commented on docs/reference/sql/copy.md
>    - If the target table does not exist, both `TIMESTAMP` and `PARTITION BY` options must be defined to create a partitioned table. The `PARTITION BY` value should not be `NONE`.
This is included in:

> - If the target table exists and is partitioned, the target table must be empty.

In the guide, we have:
![image](https://user-images.githubusercontent.com/107401731/183612466-f4fd3971-de7c-48bf-b8b5-c2fa8095e5f5.png)
So I think it is covered?

2022-08-09 09:20 UTC, argshook reviewed
just leaving some suggestions for code formatting.

I find it easiear to read `curl`s when they're indented

2022-08-09 09:20 UTC, argshook commented on docs/guides/importing-data-rest.md
> +]' -F data=@trades.csv 'http://localhost:9000/imp'
```suggestion
curl \
  -F schema='[ \
    {"name":"ts", "type": "TIMESTAMP", "pattern": "yyyy-MM-dd - HH:mm:ss"}, \
    {"name":"ticker_name", "type": "SYMBOL"} \
  ]' \
  -F data=@trades.csv 'http://localhost:9000/imp'
```

2022-08-09 09:20 UTC, argshook commented on docs/guides/importing-data-rest.md
> +]' -F data=@my_file.csv 'http://localhost:9000/imp'
```suggestion
curl \
  -F schema='[ \
    {"name":"ts", "type": "TIMESTAMP", "pattern": "yyyy-MM-ddTHH:mm:ss.SSSUUUNNNZ"} \
  ]' \
  -F data=@my_file.csv \
  http://localhost:9000/imp
```

2022-08-09 09:25 UTC, puzpuzpuz commented on docs/guides/importing-data.md
> +7. Repeat the steps to narrow down to a correct schema
```suggestion
7. Repeat the steps to narrow down to a correct schema.
```

2022-08-09 09:33 UTC, amyshwang commented on docs/guides/importing-data.md
> +| 2022-08-03T15:00:40.907224Z | 42d31603842f771a | weather_unordered | weather1mil.csv | null  | started  | null    | null         | null          | 0      |
Added more text to introduce an un-ordered table.

2022-08-09 09:48 UTC, bluestreak01 requested changes

2022-08-09 09:48 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +The [`COPY` SQL command](/docs/reference/sql/copy/) is the preferred way to import large (especially out-of-order) CSV files into partitioned tables. This is the best way to migrate data from another
```suggestion
The [`COPY` SQL command](/docs/reference/sql/copy/) is the preferred way to import large CSV files into partitioned tables. It should be used to migrate data from another database into QuestDB.
```

2022-08-09 09:48 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +This guide outlines the pre-requisites to use the command, and the configuration and steps to successfully import data into QuestDB.
```suggestion
This guide describes the method of migrating data to QuestDB via CSV files. For the time being this is the only way to get the existing data into QuestDB
```

2022-08-09 09:48 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +This section outlines pre-requisites and considerations before starting an import.
```suggestion
Preparation is the key. Copy is a multi-step process, which consists of:
- exporting the existing database as CSV
- enabling and configuring `COPY` command to be optimal for your system
- preparing target schema in QuestDB
```

2022-08-09 09:48 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +Ideally, each table in an existing database should be exported as one CSV file for the import. There is no limit to the size of the CSV file.
```suggestion
Export data using one CSV file per table. Make sure you export a column, which can be used as timestamp. Data in CSV is not expected to be in any particular order. If it is not possible to export table as one CSV, you can export multiple and concatenate these files before importing into QuestDB.

Make sure you export somewhere, which is on fast network. Large CSV file will have to be copied to QuestDB instance.
```

2022-08-09 10:03 UTC, amyshwang commented on docs/guides/importing-data.md
> +Ideally, each table in an existing database should be exported as one CSV file for the import. There is no limit to the size of the CSV file.
The rest of the docs does not use "you" so I will re-write this to:
```suggestion
Export data using one CSV file per table. Make sure to export a column, which can be used as timestamp. Data in CSV is not expected to be in any particular order. If it is not possible to export table as one CSV, export multiple files and concatenate these files before importing into QuestDB.
```

2022-08-09 10:12 UTC, amyshwang commented on docs/guides/importing-data.md
> -timestamp format, this may be included with the call as follows:
Clarified the section is on ### Import CSV file using a smaller table and has updated it.

2022-08-09 10:34 UTC, tris0laris commented on docs/guides/importing-data.md
> +To optimize performance, it is preferable to place the input CSV file on a high-IOPS disk (especially, if the file is unordered); otherwise, import may slow down while doing random requests for each
```suggestion
To optimize performance, it is preferable to place the input CSV file on a high-IOPS disk (especially if the file is unordered); otherwise, import may slow down while doing random requests for each input row.
```

2022-08-09 10:36 UTC, tris0laris commented on docs/guides/importing-data.md
> +To get best performance, temporary import files (governed by `cairo.sql.copy.work.root` setting) should be set to the same filesystem as the database data files.
```suggestion
For optimal performance, temporary import files (governed by `cairo.sql.copy.work.root` setting) should be set to the same filesystem as the database data files.
```

2022-08-09 10:38 UTC, tris0laris commented on docs/guides/importing-data.md
> +QuestDB analyzes input file, detects schema and creates target table. However, there are elements that the CSV analysis cannot decide, e.g. which column should be of symbol type or indexed.
Analysis cannot decide: "Decide" is not precise nor clear, use something else

2022-08-09 10:39 UTC, tris0laris commented on docs/guides/importing-data.md
> +- Importing CSV file using a smaller table: Infer schema from data during dry-run using a smaller table repeatedly in order to modify the schema until all expectations are met.
"from data during dry-run" > this sounds a bit funky to me

2022-08-09 10:40 UTC, tris0laris commented on docs/guides/importing-data.md
> +- Create table schema manually: This is useful when the user is familiar with QuestDB data types and understand how to translate existing database data types into QuestDB types.
```suggestion
- Create table schema manually: This is useful when the user is familiar with QuestDB data types and understands how to translate existing database data types into QuestDB types.
```

2022-08-09 10:41 UTC, bluestreak01 requested changes

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +## Preparing the import
```suggestion
## Prepare the import
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +### Exporting existing database
```suggestion
### Export the existing database
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +### Understanding the QuestDB import
```suggestion
### Things to know about `COPY`
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +Importing CSV file is disabled by default, in order not to expose the host file system to potential attackers. Import can be enabled by configuring the target disk using the `cairo.sql.copy.root` set
```suggestion
- `COPY` is disabled by default, as a security precaution. We are going to need to enable and configure it
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +The `COPY` command works more efficiently when source and target disks are different.
```suggestion
- `COPY` is more efficient when source and target disks are different.
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +The import operation attempts to sort CSV file by timestamp on the source disk and can benefit from SSD with large number of IOPS.
```suggestion
- `COPY` indexes CSV file. This operation responds well to a disk with high IOPS. If source and target disks are different, faster source disk has the most impact. NVME source disk is the best option.
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +To optimize performance, it is preferable to place the input CSV file on a high-IOPS disk (especially, if the file is unordered); otherwise, import may slow down while doing random requests for each
I would remove this paragraph, it overlaps with the one above

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +For third-party cloud providers, the fastest source option for the import is an NVMe SSD.
and this one

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +The [`COPY` SQL command](/docs/reference/sql/copy/) outlines more details for parallel and serial import.
```suggestion
- [`COPY`](/docs/reference/sql/copy/) outlines more details for parallel and serial import.
```

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +- It may also be possible to create tables by setting `commitLag` and `maxUncommittedRows` via
remove this section, it is confusing - we're focusing on "import" only, commit lag has nothing to do with it

2022-08-09 10:41 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +- Importing into existing partitioned tables containing data is not yet supported. Import can only target blank tables. Please vote for the existing [GH issue](https://github.com/questdb/questdb/issu
Remove the "info" blurb, there is no need to emphasise one thing over the other. It is important user understand all information is this section
```suggestion
- `COPY` will only work when target table is blank or does not exist.
```

2022-08-09 10:42 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +### Configure QuestDB settings
### Configure `COPY`

2022-08-09 10:42 UTC, tris0laris commented on docs/guides/importing-data.md
> +The following sections show steps to import an example unordered CSV file, `weather.csv`:
```suggestion
The following sections show steps to import the dataset `weather.csv`, which is an unordered CSV file:
```

2022-08-09 10:42 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +### Configure QuestDB settings
```suggestion
### Configure `COPY`
```

2022-08-09 10:44 UTC, tris0laris commented on docs/guides/importing-data.md
> +    or dropping of target table:
```suggestion
    or dropping the target table:
```

2022-08-09 10:53 UTC, amyshwang commented on docs/guides/importing-data.md
> +- Importing CSV file using a smaller table: Infer schema from data during dry-run using a smaller table repeatedly in order to modify the schema until all expectations are met.
```suggestion
- Importing CSV file using a smaller table: Infer schema from importing a smaller table repeatedly in order to modify the schema until all expectations are met.
```

2022-08-09 10:54 UTC, amyshwang commented on docs/guides/importing-data.md
> +## Preparing the import
Already changed.

2022-08-09 10:58 UTC, amyshwang commented on docs/guides/importing-data.md
> +Importing CSV file is disabled by default, in order not to expose the host file system to potential attackers. Import can be enabled by configuring the target disk using the `cairo.sql.copy.root` set
```suggestion
- `COPY` is disabled by default, as a security precaution. Configuration is required.
```
Given that the configuration section is just below, I think we can leave it like the above.

2022-08-09 11:01 UTC, amyshwang commented on docs/guides/importing-data.md
> +- Importing into existing partitioned tables containing data is not yet supported. Import can only target blank tables. Please vote for the existing [GH issue](https://github.com/questdb/questdb/issu
```suggestion
- `COPY` only works when the target table is blank or does not exist.
```

2022-08-09 11:06 UTC, amyshwang commented on docs/guides/importing-data.md
> +- It may also be possible to create tables by setting `commitLag` and `maxUncommittedRows` via
Retaining the first point but deleting the second one.

2022-08-09 11:14 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +## Create the table schema
```suggestion
## Create the target table schema
```

2022-08-09 11:19 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +:::info
we don't need "info" emphasis here

2022-08-09 11:20 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +- It may also be possible to create tables by setting `commitLag` and `maxUncommittedRows` via
what is "first" and "second" ?

2022-08-09 11:24 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +See [`COPY` configuration settings](/docs/reference/configuration#bulk-csv-import) for all the configuration options.
Lets remove this entire section and replace it with:

Enable `COPY` via [configuration](/docs/reference/configuration#bulk-csv-import).

2022-08-09 11:26 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +Once the source data is exported and QuestDB configuration is set, the user can start an import.
```suggestion
Once the source data is exported and QuestDB configuration is set, we can start an import.
```

2022-08-09 11:36 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +
For example, create smaller file:

```bash
head -100000 my_table.csv > my_table_small.csv
```

2022-08-09 12:04 UTC, puzpuzpuz commented on docs/reference/configuration.md
> +| cairo.sql.copy.max.index.chunk.size | 100MiB  | Maximum size of index chunk file used to limit total memory requirements of import . Indexing phase should use roughly threads_count * cairo.sql.copy
```suggestion
| cairo.sql.copy.max.index.chunk.size | 100m  | Maximum size of index chunk file used to limit total memory requirements of import. Indexing phase should use roughly `thread_count * cairo.sql.copy.max.index.chunk.size` of memory.               |
```

2022-08-09 16:55 UTC, bluestreak01 approved these changes

2022-08-09 16:56 UTC, merged

2022-08-10 11:11 UTC, amunra commented on docs/guides/importing-data.md
> +
A new section for "Handling import errors". It should say what to do in case of errors.
* Does the whole need to be restarted from scratch?
* Can it be resumed?
* On data issues, is it possible to skip and write out bad data to a file so it can be corrected manually and re-inserted, say, via the REST API?
* What happens in a database crash or OS reboot? Will the table be there but partially written? Will the table be absent?
* How does one find the log file?

2022-08-10 11:11 UTC, amunra commented on docs/guides/importing-data.md
> +   using the id (see also [Monitor the log](/docs/guides/importing-data/#monitoring-the-log)
Audit all links to ensure there is NO trailing backslash as this breaks crawling.

In other words, `/docs/guides/importing/data/#monitoring-the-log` should read `/docs/guides/importing/data#monitoring-the-log`

2022-08-10 11:11 UTC, amunra commented on docs/guides/importing-data.md
> +   and [FAQ](/docs/guides/importing-data/#faq)):
Ditto here on the trailing slash: This creates a larger sitemap when crawled and de-ranks the pages.

2022-08-10 11:15 UTC, bluestreak01 commented on docs/reference/configuration.md
> +| cairo.sql.copy.work.root            | null    | Temporary import file directory. Same as `cairo.sql.copy.root` if not set explicitly.
@amunra yes, paths are validated thoroughly for jailbreaks and overlaps with other paths

2022-08-10 11:17 UTC, amunra commented on docs/reference/sql/copy.md
>  Copies tables from a delimited text file saved in the defined root directory into QuestDB. `COPY` has the following import modes:
Further reading the other documents it's now clear that this isnt' a selectable mode, but rather parallelism is only applied if the destination table is partitioned.

This was not at all clear here: The section above should be reworded, and arguably de-emphasized as it's a technical detail.

2022-08-10 11:19 UTC, bluestreak01 commented on docs/guides/importing-data.md
> +- `COPY` is _serial_ when target table is non-partitioned, out-of-order timestamps will be rejected
@amunra your understanding is correct, we don't support inserting out of order data into non-partitioned table _with timestamp_. Without timestamp - not a problem.

2022-08-10 12:59 UTC, amyshwang commented on docs/guides/importing-data-rest.md
> +While REST API is convenient for importing small tables, `COPY` is optimized for importing large out-of-order tables. See [COPY command documentation](/docs/reference/sql/copy/) and [Guide on bulk CS
Addressing in #979

2022-08-10 13:02 UTC, amyshwang commented on docs/guides/importing-data-rest.md
> +timestamp format, this may be included with the call as follows:
The REST API section is a migration of existing content to a new page. In the guide, some pages are very neutral and does not use "you", some does (e.g. Modifying data). Just changing the style risk missing the big picture so I would part this for now but start discussion elsewhere...

2022-08-10 13:15 UTC, amyshwang commented on docs/guides/importing-data.md
> +   using the id (see also [Monitor the log](/docs/guides/importing-data/#monitoring-the-log)
Fixed.

2022-08-10 13:21 UTC, amyshwang commented on docs/guides/importing-data-rest.md
> +:::
- More info on HTTP REST has bee added in https://github.com/questdb/questdb.io/pull/979.
- I am adding a point to [Configure COPY section](https://questdb.io/docs/guides/importing-data)docs/guides/importing-data#configure-copy
- I don't have an answer re cutoff point...Will add an internal note