feat: document partition detach/attach
questdb/questdb.io pull request #981
Opened 2022-08-10 15:21 UTC by marregui

2022-08-10 15:21 UTC, marregui commented
still working on it

2022-08-12 12:01 UTC, marregui commented
ready for review

2022-08-18 13:16 UTC, amyshwang requested changes
Editorial review.

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +in `server.conf` by means of attribute:
```suggestion
in `server.conf` by using the attribute:
```

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +Partitions lacking these files will still be attachable, however no checks are performed on the
```suggestion
Partitions without the  metadata files will still be attachable, but no checks are performed on the
```

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +but not rename them).
```suggestion
Detaching a partition, however, allows for the table's structure to mutate (add/remove columns, 
but not rename them).
```

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +but not rename them).
I am not sure why "however" is used here...

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaching a partition just tells QuestDB that it no longer is accessible for *reads*.
```suggestion
For QuestDB's engine, detaching a partition means that it is no longer accessible for *reads*.
```

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +However if you insert new data under the detached partition's time range, the partition
```suggestion
However, if you insert new data under the detached partition's time range, the partition
```

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +first we rename the the above file system to:
Same as the other file - could we specify the suffix?

2022-08-18 13:16 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +attaching detached partitions by means of query [ALTER TABLE DETACH PARTITION](alter-table-detach-partition.md),
```suggestion
attaching detached partitions by means of query [ALTER TABLE DETACH PARTITION](alter-table-detach-partition),
```
Please could we remove all the suffix in hyperlinks for consistency?

2022-08-25 10:07 UTC, amunra commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaches one or more partitions from a table. This feature is designed to support
What does detaching mean?
* Does the table get deleted?
* Is it kept, but archived?
* Is the format changed?
* Is this to move data from one database (e.g. holding the latest data) and reattach to another database instance (e.g. the archive database) without having to change format?
* Is this to correct data while it's detached?
* More generally, what is the feature for?

2022-08-25 10:39 UTC, amunra commented on docs/reference/sql/alter-table-attach-partition.md
> +ALTER TABLE sensors DETACH PARTITION LIST '1970-01-01T00', '1970-01-01T06', '1970-01-01T12', '1970-01-01T18', '1970-01-02T00';
Is there a SQL command to list partitions for a table?

2022-08-25 10:40 UTC, amunra commented on docs/reference/sql/alter-table-attach-partition.md
> +ALTER TABLE sensors DETACH PARTITION LIST '1970-01-01T00', '1970-01-01T06', '1970-01-01T12', '1970-01-01T18', '1970-01-02T00';
Also, are these hourly partitions in UTC?

2022-08-25 10:48 UTC, amunra commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaches one or more partitions from a table. This feature is designed to support
Now that I'm reading further, this maybe these questions would be better answered as a guide on data backup and migration (which I think - but I'm not sure - this feature fulfills).

2022-08-25 10:49 UTC, amunra commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaches one or more partitions from a table. This feature is designed to support
Confusingly the "attach" guide states "Moving partitions between tables or database instances is not supported.". I'm pretty lost now.

2022-08-25 15:55 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaches one or more partitions from a table. This feature is designed to support
Quick notes from discussion with @bluestreak01 

Purpose - Decouple partitions from the QuestDB instance. Content not manipulated. Allowing users to deposit partitions to cold storage.
Constraint - only to the same table.
Detached partition treatment: QuestDB does not do anything - it leaves room for manual intervention.

2022-08-25 15:58 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +ALTER TABLE sensors DETACH PARTITION LIST '1970-01-01T00', '1970-01-01T06', '1970-01-01T12', '1970-01-01T18', '1970-01-02T00';
- I think it is just a directory so you won't need SQL to show them?
- I am making an educated guess that the partitions are decided by the designated timestamp of the table, but I am not very well-educated so maybe I am talking nonsense...

2022-08-30 14:07 UTC, marregui commented on docs/reference/sql/alter-table-attach-partition.md
> +ALTER TABLE sensors DETACH PARTITION LIST '1970-01-01T00', '1970-01-01T06', '1970-01-01T12', '1970-01-01T18', '1970-01-02T00';
hola, no, there are no commands to list partitions per table, nor their status (attached, live, detached), nor to manage them, i.e. rename detached to attachable or move them about. It all needs to be done by hand (in cloud is different).
Timestamps are UTC, these partition names are UTC as well, they are created as data turns up for the specific bucket (defined by the timestamp)

2022-08-30 14:10 UTC, marregui commented on docs/reference/sql/alter-table-detach-partition.md
> +Detaches one or more partitions from a table. This feature is designed to support
The use case, in general, is:
- I have lots of data in my table, and it is partitioned by some granularity that makes me happy (by HOUR say).
- If only I could simply use the last 5 items of said granularity, instead of all my data, i.e. only the last 5 hours...
- oh, wait, I can detach partitions older than 5 hours from now and just focus on "hot data"
- later on I can attach whatever partitions I want if I need more data

2022-08-30 14:36 UTC, bluestreak01 requested changes

2022-08-30 14:36 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +The root file system location where QuestDB stores detached partitions is configurable
this paragraph is not relevant for attaching partitions. I would remove it or rephrase it somehow. I would suggest we outline sequence of events first to make it look simpler:

1. Copy partition inside table and make sure partition name has suffix `.attachable`. For example `2020.attachable`
2. Execute SQL `alter table x attach partition list '2020'`. Notice how SQL does not include the suffix.

After SQL is executed, QuestDB will rename partition to its correct name and make it available to reading.

2022-08-30 14:37 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +## Configuration
I would separate description and configuration, in this section both are mixed up

2022-08-30 14:41 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +which defaults to false. When set to true detached partitions are copied to the *detached storage*
factually incorrect.

remember that `alter table x attach partition list '2020'` will rename `2020.attachable` to something like `2020.201` where `201` is current transaction number of the table.

when

```
cairo.attach.partition.copy=true
```
is set, instead of renaming directory, questdb will copy it, e.g. after SQL both `2020.attachable` and `2020.201` will be present. It might be needed in some niche cases.

2022-08-30 14:42 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +This operation is only supported if the partition was detached, or has been copied
i would also add that operation will also fail when partition already exists, which might happen when someone inserted out of order records into "detached" partition

2022-08-30 14:44 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +the format `<partition_name>.SUFFIX` to the *detached storage* directory of
I would remove this paragraph. It is factually incorrect. The partition must be copied not to *detached storage* but rather inside the table

2022-08-30 14:45 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +## Examples
Before that I would create configuration section and add link to the relevant configuration properties and their description

2022-08-30 15:21 UTC, amyshwang commented on docs/reference/configuration.md
> +| cairo.sql.detached.root                        | db                | Detached storage directory for `ALTER TABLE ATTACH PARTITION` and `ALTER TABLE DETACH PARTITION`
I figure that this has been removed and changed to `cairo.detach.root`?

2022-08-30 15:21 UTC, amyshwang commented on docs/reference/configuration.md
> +| cairo.attach.partition.suffix                  | .attachable       | Suffix in `<partition-name><suffix>`, e.g. 2022-08-30.attachable, to identify a detached partition directory before performing a
This is a background setting that I don't think that a user needs to reset - do we really need it here?

2022-08-30 15:21 UTC, amyshwang commented on docs/reference/configuration.md
> +| cairo.attach.partition.copy                    | false             | When `true` detached partition folders are copied to the location defiled by `cairo.detach.root` (instead of being linked).
I am not sure if I understand. Vlad has some concerns about the content added to this setting below...

2022-08-30 16:52 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +which defaults to false. When set to true detached partitions are copied to the *detached storage*
We agree that this is not for general users so removed.

2022-08-30 16:52 UTC, amyshwang commented on docs/reference/sql/alter-table-attach-partition.md
> +## Examples
Config now removed.

2022-09-01 15:28 UTC, bluestreak01 requested changes

2022-09-01 15:28 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +Given a table `sensors` that has previously [detach](alter-table-detach-partition.md) partitions, if we want to attach one or more of these partitions back, for instance `1970-01-01T18` and `1970-01-
```suggestion
Given a table `sensors` that has previously [detached](alter-table-detach-partition.md) partitions, if we want to attach one or more of these partitions back, for instance `1970-01-01T18` and `1970-01-02T00`:
```

2022-09-01 15:28 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +--
why do we have this comment ?

2022-09-01 15:28 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +3. Run the `ALTER TABLE ATTACH PARTITION` command.
it is a matter of opinion perhaps, but since we asked to rename directory first and then run SQL, should we be specific that partition name reference from SQL should not include `.attachable` suffix?

2022-09-01 15:28 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
> +### Example 2
This is really bad example. Did this example work for you?

`DETACH` SQL writes metadata into partition, therefor `ATTACH` only works with `DETACHED` partitions. Partitions from a backup are not `DETACHED` per se and probably won't work

2022-09-01 15:28 UTC, bluestreak01 commented on docs/reference/sql/alter-table-attach-partition.md
>  The partitions are attached by providing a comma-separated list of partitions:
this example is redundant, example 1 shows how to attach multiple partitions

2022-09-01 16:14 UTC, bluestreak01 requested changes

2022-09-01 16:14 UTC, bluestreak01 commented on docs/reference/sql/alter-table-detach-partition.md
> +The operation saves global metadata files `_dmeta` and `_dcv` alongside column-related files to
This is very heavy. I would not mix-in `backups` here nor divulge details of how `detach` works under the hood.

What we should explain instead is that `.detached` directories can be moved elsewhere. 

I would suggest we do not talk about modifying content of the directories. We should discourage that.

2022-09-01 16:14 UTC, bluestreak01 commented on docs/reference/sql/alter-table-detach-partition.md
> +## Steps
Another example, we talk at bottom of the page what detaching means. This can be in the description of the SQL. We also should answer `why` anyone would want to detach partition. Why can't they move partitions without detaching?

2022-09-01 16:14 UTC, bluestreak01 commented on docs/reference/sql/alter-table-detach-partition.md
> +For QuestDB's engine, detaching a partition means that it is no longer accessible for *reads*.
This note ultimately belongs to `attach` page. The reason is that `DETACH` SQL will never fail, only if table is "busy".

On other hand `ATTACH` may fail because partition could have been recreated by O3

2022-09-01 17:49 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +), INDEX(id2 capacity 32) TIMESTAMP(ts) PARTITION BY HOUR;
```suggestion
), TIMESTAMP(ts) PARTITION BY HOUR;
```
The existing query works but when I updated it to the above I hit an error "unexpected token"...

2022-09-01 18:03 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +## Steps
why anyone would want to detach partition:

> This feature is designed to allow users to manipulate detached partitions and migrate them to a cold storage. 

Why can't they move partitions without detaching?
My answer would be something like:
Using `ALTER TABLE DETACH PARTITION` ensures relevant metadata is saved with the partition files, and the partitions can be attached back to the same table in the future. Deleting the partition files directly from the table directory means that the detached partitions won't be able to be attached back to the table.

2022-09-02 07:57 UTC, amyshwang commented on docs/reference/sql/alter-table-detach-partition.md
> +), INDEX(id2 capacity 32) TIMESTAMP(ts) PARTITION BY HOUR;
Removed the comma and it worked.

2022-09-02 08:22 UTC, bluestreak01 commented on docs/reference/sql/alter-table-detach-partition.md
> +## Steps
We could keep the first sentence only. Explaining that detach does something extra is enough to explain “why”

2022-09-02 15:54 UTC, bluestreak01 approved these changes

2022-09-02 15:55 UTC, amyshwang approved these changes

2022-09-02 15:56 UTC, merged